<?php

function pegasus_publications_permission() {
  return array(
    'access pegasus publications settings' => array(
      'title' => t('Change Pegasus publications settings')
    )
  );
}

function pegasus_publications_admin() {
  $form = array();

  $form['pegasus_publications_bibtex'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to bibtex file'),
    '#default_value' => variable_get('pegasus_publications_bibtex', ''),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t("This is the path to the bibtex file used to generate the publications page."),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

function pegasus_publications_admin_validate($form, &$form_state) {
    $values = $form_state['values'];

    $file = $values['pegasus_publications_bibtex'];
    if (!is_file($file)) {
        form_set_error('pegasus_publications_bibtex', t('Invalid file'));
    }

    // Clear any previously cached value
    //cache_clear_all('pegasus_publications_result', 'cache', TRUE);
}

/**
 * Implements hook_menu().
 */
function pegasus_publications_menu() {
    $items = array();

    $items['admin/pegasus/publications/settings'] = array(
        'title' => 'Pegasus Publications Settings',
        'description' => 'Configure pegasus publications module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pegasus_publications_admin'),
        'access arguments' => array('access pegasus publications settings'),
        'type' => MENU_CALLBACK
        #'type' => MENU_LOCAL_TASK
    );

    $items['publications/papers'] = array(
        'title' => 'Pegasus Paper',
        'description' => 'Papers by the Pegasus group',
        'page callback' => 'pegasus_publications_view',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    $items['publications/bibtex'] = array(
        'title' => 'Pegasus Bibtex',
        'description' => 'Papers by the Pegasus group',
        'page callback' => 'pegasus_bibtex_view',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    return $items;
}

function pegasus_bibtex_view() {
    $file = variable_get('pegasus_publications_bibtex', '');
    if ($file === '') {
        return '<h1>Bibtex file not configured</h1><p>Set the bibtex file in the module settings page.</p>';
    }

    $fh = fopen($file, 'r');
    $result = fread($fh, filesize($file));
    fclose($fh);

    drupal_add_http_header('Content-type', 'text/plain; charset=UTF-8');
    drupal_add_http_header('Content-Disposition', 'attachment; filename=pegasus.bib');
    echo $result;
}

/**
 * View function callback for publications menu item.
 */
function pegasus_publications_view() {
    // Add the CSS for styling the references
    drupal_add_css(drupal_get_path('module', 'pegasus_publications') . '/bibtex.css', array('group' => CSS_DEFAULT));

    $file = variable_get('pegasus_publications_bibtex', '');
    if ($file === '') {
        return '<h1>Bibtex file not configured</h1><p>Set the bibtex file in the module settings page.</p>';
    }

    $bib = new Bibtex($file);
    $result = $bib->Render();

    return '<p><a href="/publications/bibtex">Bibtex</a></p>' . $result;

    // Cache the result. This saves about 75ms / 180ms on my laptop.
    /*
    if ($cache = cache_get('pegasus_publications_result')) {
        $result = '<h1>Cached</h1>' . $cache->data;
    } else {
        $bib = new Bibtex($file);
        $result = $bib->Render();
        cache_set('pegasus_publications_result', $result, 'cache', time() + 300);
    }
    return $result;
    */
}

