package integrity

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const helloWorldSHA256 = "d2a84f4b8b650937ec8f73cd8be2c74add5a911ba64df27458ed8229da804a26"

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestGenerateSHA256(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")

	sum, err := GenerateSHA256(path)
	if err != nil {
		t.Fatal(err)
	}
	if sum != helloWorldSHA256 {
		t.Fatalf("got %s, want %s", sum, helloWorldSHA256)
	}
}

func TestGenerateSHA256MissingFile(t *testing.T) {
	_, err := GenerateSHA256("/does/not/exist")
	if err == nil {
		t.Fatal("expected error for missing file")
	}
	if !strings.Contains(err.Error(), "does not exist") {
		t.Fatalf("unexpected error text: %v", err)
	}
}

func TestGenerateYAML(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")

	yaml, err := GenerateYAML(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(yaml, "sha256: "+helloWorldSHA256) {
		t.Fatalf("missing sha256 line: %s", yaml)
	}
	if !strings.Contains(yaml, "checksum_timing:") {
		t.Fatalf("missing checksum_timing line: %s", yaml)
	}
}

func TestGenerateFullstatYAML(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")

	yaml, err := GenerateFullstatYAML("data.1", path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`"data.1":`,
		"comment: entry generated by pegasus-integrity",
		"size: 12",
		"output: True",
		"sha256: " + helloWorldSHA256,
	} {
		if !strings.Contains(yaml, want) {
			t.Errorf("missing %q in:\n%s", want, yaml)
		}
	}
}

func TestGenerateFullstatYAMLMissingFile(t *testing.T) {
	_, err := GenerateFullstatYAML("lfn", "/does/not/exist")
	if err == nil {
		t.Fatal("expected error for missing file")
	}
}

func TestReadMetaData(t *testing.T) {
	entries, err := ReadMetaData("../../testdata/data.meta")
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("got %d entries, want 2", len(entries))
	}
	if entries[0].ID != "data.1" {
		t.Fatalf("got id %s", entries[0].ID)
	}
	if v, ok := entries[0].ChecksumValue(); !ok || v != helloWorldSHA256 {
		t.Fatalf("got checksum %s ok=%v", v, ok)
	}
}

func TestReadMetaDataEmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "empty.meta", "[]")
	// "[]" is 2 bytes, matching the Python original's `size <= 2` skip.
	entries, err := ReadMetaData(path)
	if err != nil {
		t.Fatal(err)
	}
	if entries != nil {
		t.Fatalf("expected no entries for a <=2 byte file, got %v", entries)
	}
}

func TestCheckIntegritySuccess(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")
	meta := []MetaEntry{{ID: "data.1", Attributes: map[string]string{"checksum.value": helloWorldSHA256}}}

	stats := &Stats{}
	result := CheckIntegrity(path, "data.1", meta, stats)
	if !result.Success || result.NoMetaEntry {
		t.Fatalf("expected success, got %+v", result)
	}
	if stats.Succeeded != 1 || stats.Failed != 0 {
		t.Fatalf("got stats %+v", stats)
	}
}

func TestCheckIntegrityMismatch(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")
	meta := []MetaEntry{{ID: "data.1", Attributes: map[string]string{"checksum.value": "deadbeef"}}}

	stats := &Stats{}
	result := CheckIntegrity(path, "data.1", meta, stats)
	if result.Success || result.NoMetaEntry {
		t.Fatalf("expected mismatch, got %+v", result)
	}
	if stats.Failed != 1 || stats.Succeeded != 0 {
		t.Fatalf("got stats %+v", stats)
	}
}

func TestCheckIntegrityNoMetaEntry(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")

	stats := &Stats{}
	result := CheckIntegrity(path, "unknown-lfn", nil, stats)
	if !result.NoMetaEntry {
		t.Fatalf("expected NoMetaEntry, got %+v", result)
	}
	// Matches Python: the early-return path touches no counters at all.
	if stats.Succeeded != 0 || stats.Failed != 0 || stats.Duration != 0 {
		t.Fatalf("expected untouched stats, got %+v", stats)
	}
}

func TestCheckIntegrityDefaultsLFNToFilename(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "data.1", "Hello World\n")
	meta := []MetaEntry{{ID: path, Attributes: map[string]string{"checksum.value": helloWorldSHA256}}}

	stats := &Stats{}
	result := CheckIntegrity(path, "", meta, stats)
	if !result.Success {
		t.Fatalf("expected lfn to default to fname, got %+v", result)
	}
}

func TestCheckIntegrityComputationFailureRendersNoneSentinel(t *testing.T) {
	// Matches Python: generate_sha256() failing doesn't short-circuit the
	// comparison — current_sha256 stays Python's None, which is compared
	// (and, if --print-timings, rendered in YAML) as the literal text
	// "None", not treated as a distinct error path.
	meta := []MetaEntry{{ID: "missing", Attributes: map[string]string{"checksum.value": helloWorldSHA256}}}
	stats := &Stats{}
	result := CheckIntegrity("/does/not/exist", "missing", meta, stats)
	if result.Success {
		t.Fatal("expected failure")
	}
	if result.SHA256Valid || result.SHA256 != "None" {
		t.Fatalf("expected None sentinel, got %+v", result)
	}
	if stats.Failed != 1 {
		t.Fatalf("expected the failure to still be counted, got %+v", stats)
	}
}
