// Package integrity implements pegasus-integrity's checksum generation and
// verification logic: a Go port of packages/pegasus-worker/src/Pegasus/cli/
// pegasus-integrity.py.
//
// One deliberate behavior change from the Python original: SHA-256 is
// computed natively via crypto/sha256 instead of shelling out to openssl or
// sha256sum on PATH. This removes a runtime dependency (no external tool
// needs to be present on the worker node) and, as a side effect, removes an
// entire class of shell-quoting concerns the Python version had to handle
// via shlex.quote() for filenames with spaces — there is no shell involved
// here at all. The checksum values produced are identical either way; only
// the computation mechanism differs.
//
// This package independently re-implements packages/pegasus-transfer's
// internal/integrity fullstat-YAML generator rather than importing it — per
// the project's decision record, each worker tool is its own fully separate
// Go module, accepting this small duplication over a cross-module
// dependency. The output format must stay in sync by hand if it ever
// changes (unlikely: it's consumed by kickstart/monitord and is effectively
// frozen).
package integrity

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/user"
	"strconv"
	"strings"
	"time"
)

// GenerateSHA256 computes the SHA-256 checksum of the file at path, returned
// as a lowercase 64-character hex digest. Matches generate_sha256()'s
// contract minus the external-tool detection (see package doc).
func GenerateSHA256(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("File %s does not exist", path)
		}
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// GenerateYAML reproduces generate_yaml(): a checksum-only kickstart YAML
// snippet (sha256 + timing, no stat metadata).
func GenerateYAML(pfn string) (string, error) {
	start := time.Now()
	sum, err := GenerateSHA256(pfn)
	if err != nil {
		return "", err
	}
	elapsed := time.Since(start)
	return fmt.Sprintf("      sha256: %s\n      checksum_timing: %.3f\n", sum, elapsed.Seconds()), nil
}

// GenerateFullstatYAML reproduces generate_fullstat_yaml(): a full stat()
// snapshot plus SHA-256 checksum, keyed by lfn. Matches the Python
// original's behavior of returning ("", nil) — not an error — when the
// checksum succeeds but the subsequent stat() fails.
func GenerateFullstatYAML(lfn, pfn string) (string, error) {
	start := time.Now()
	sum, err := GenerateSHA256(pfn)
	if err != nil {
		return "", err
	}
	elapsed := time.Since(start)

	info, err := os.Stat(pfn)
	if err != nil {
		return "", nil
	}
	st := statInfo(info)

	uname := lookupUser(st.Uid)
	gname := lookupGroup(st.Gid)

	var b strings.Builder
	fmt.Fprintf(&b, "    %q:\n", lfn)
	b.WriteString("      comment: entry generated by pegasus-integrity\n")
	fmt.Fprintf(&b, "      file_name: %q\n", pfn)
	fmt.Fprintf(&b, "      mode: 0o%o\n", st.Mode)
	fmt.Fprintf(&b, "      size: %d\n", info.Size())
	fmt.Fprintf(&b, "      inode: %d\n", st.Ino)
	fmt.Fprintf(&b, "      nlink: %d\n", st.Nlink)
	fmt.Fprintf(&b, "      mtime: %s\n", iso8601(st.Mtime))
	fmt.Fprintf(&b, "      atime: %s\n", iso8601(st.Atime))
	fmt.Fprintf(&b, "      ctime: %s\n", iso8601(st.Ctime))
	fmt.Fprintf(&b, "      uid: %d\n", st.Uid)
	fmt.Fprintf(&b, "      user: %s\n", uname)
	fmt.Fprintf(&b, "      gid: %d\n", st.Gid)
	fmt.Fprintf(&b, "      group: %s\n", gname)
	b.WriteString("      output: True\n")
	fmt.Fprintf(&b, "      sha256: %s\n      checksum_timing: %.3f\n", sum, elapsed.Seconds())

	return b.String(), nil
}

func lookupUser(uid uint32) string {
	u, err := user.LookupId(strconv.FormatUint(uint64(uid), 10))
	if err != nil {
		return ""
	}
	return u.Username
}

func lookupGroup(gid uint32) string {
	g, err := user.LookupGroupId(strconv.FormatUint(uint64(gid), 10))
	if err != nil {
		return ""
	}
	return g.Name
}

// iso8601 matches pegasus-integrity.py's iso8601(): UTC, seconds precision
// via datetime.isoformat() (microseconds included when non-zero).
func iso8601(t time.Time) string {
	t = t.UTC()
	if t.Nanosecond() == 0 {
		return t.Format("2006-01-02T15:04:05+00:00")
	}
	return t.Format("2006-01-02T15:04:05.000000+00:00")
}

// MetaEntry is one entry of a pegasus-transfer-produced .meta file: a plain
// JSON object with the fields check_integrity looks up. Matches the shape
// read by read_meta_data() (json.load with no object_hook — the Python
// original also defines a json_object_decoder object_hook referencing
// Transfer/Mkdir/Remove classes that don't exist anywhere in that file; it's
// dead code, never wired into json.load, and is not ported here).
type MetaEntry struct {
	ID         string            `json:"_id"`
	Attributes map[string]string `json:"_attributes"`
}

// ChecksumValue returns the entry's "checksum.value" attribute, if any.
func (m MetaEntry) ChecksumValue() (string, bool) {
	v, ok := m.Attributes["checksum.value"]
	return v, ok
}

// Stats accumulates verification results across a --verify run, matching
// the module-level count_succeeded/count_failed/total_timing globals in the
// Python original (kept as an explicit struct here instead of package
// globals, since nothing requires process-wide shared state).
type Stats struct {
	Succeeded int
	Failed    int
	Duration  time.Duration
}

// CheckResult carries one --verify comparison's outcome. It deliberately
// mirrors two distinct Python code paths in check_integrity():
//
//   - NoMetaEntry: the early `if expected_sha256 is None: return False` —
//     no timing/succeeded/failed counters are touched, and (importantly)
//     no --print-timings YAML row is emitted for it either.
//   - the checksum-was-looked-up path: always counted (in Duration and
//     Succeeded/Failed) and always YAML-eligible, *even when computing the
//     checksum itself failed* — Python doesn't check generate_sha256()'s
//     return before comparing it, so a failed computation (current_sha256
//     is Python None) still flows through as a logged mismatch with the
//     checksum field literally rendered as the string "None". SHA256Valid
//     distinguishes that case from a real computed digest.
type CheckResult struct {
	LFN            string
	PFN            string
	SHA256         string // real digest, or the literal "None" sentinel — see SHA256Valid
	SHA256Valid    bool
	ExpectedSHA256 string
	Success        bool
	NoMetaEntry    bool
	Elapsed        time.Duration
}

func CheckIntegrity(fname, lfn string, metaData []MetaEntry, stats *Stats) CheckResult {
	if lfn == "" {
		lfn = fname
	}

	var expected string
	found := false
	for _, entry := range metaData {
		if entry.ID == lfn {
			if v, ok := entry.ChecksumValue(); ok {
				expected = v
				found = true
			}
		}
	}
	if !found {
		return CheckResult{LFN: lfn, PFN: fname, NoMetaEntry: true}
	}

	start := time.Now()
	current, err := GenerateSHA256(fname)
	elapsed := time.Since(start)
	stats.Duration += elapsed

	sha256Str, valid := current, true
	if err != nil {
		sha256Str, valid = "None", false
	}
	success := valid && current == expected
	if success {
		stats.Succeeded++
	} else {
		stats.Failed++
	}

	return CheckResult{
		LFN: lfn, PFN: fname, SHA256: sha256Str, SHA256Valid: valid,
		ExpectedSHA256: expected, Success: success, Elapsed: elapsed,
	}
}
