#!/bin/bash

set -e
set -v


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`
TESTNAME=$(basename $TOPDIR)

# generate the input file
echo "This is sample input to KEG" > f.a

# output directory
mkdir -p outputs
mkdir -p staging-site

# build the dax generator
PYTHONPATH=$(pegasus-config --python) $testdir/blackdiamond.py "$(dirname $(dirname $(which pegasus-version)))" > blackdiamond.dax

#set the local scratch for the jobs
LOCALSCRATCH=/scitech/shared/scratch-90-days/bamboo/local-scratch
mkdir -p $LOCALSCRATCH

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "cartman-data"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "/webdav/scratch-90-days/${TESTNAME}/staging-site/scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "webdavs://workflow.isi.edu/webdav/scratch-90-days/${TESTNAME}/staging-site/scratch"
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "localScratch"
    path: "${LOCALSCRATCH}/local-scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://${LOCALSCRATCH}/local-scratch"
  profiles:
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "sharedScratch"
    path: "$TOPDIR/shared-scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/shared-scratch"
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites condorpool \
    --staging-site cartman-data \
    --output-sites local \
    --dir submit \
    --cleanup leaf \
    --submit \
    blackdiamond.dax | tee plan.out
