#!/bin/bash

# LIGO test setup requires the submit
# dir to be on a shared filesystem visible to the condorpool
# nodes, since the site catalog is constructed w.r.t it.

set -e

START_DIR=$(pwd)
TEST_DIR=/scitech/shared/scratch2-90-days/bamboo/$(uuidgen)

# Conda/Python versions
if [ "x$1" = "x" ]; then
    echo "Please specify a Conda version to use (example: py311_26.3.2-2)"
    exit 1
fi
CONDA_VERSION=$1
shift

mkdir -p $TEST_DIR
cd $TEST_DIR

# create a conda environment like LIGO is using
wget -nv -O conda_setup.sh https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh
bash conda_setup.sh -b -p $TEST_DIR/conda-env
rm -f conda_setup.sh
. $TEST_DIR/conda-env/bin/activate
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
conda install fftw --yes
conda install anaconda::mkl --yes
pip3 install --upgrade pip
pip3 install --upgrade pip setuptools

# install the pegasus python dependencies
#pip3 install boto3 certifi GitPython pyjwt pyyaml s3transfer six urllib3

# install pycbc
git clone https://github.com/gwastro/pycbc.git
cd pycbc
pip3 install pylib-fftw3
pip3 install -r requirements.txt
pip3 install -r companion.txt
pip3 install  .

# we are using mixed environment from our conda env
export PYTHONPATH=$(pegasus-config --python)
export PEGASUS_UPDATE_PYTHONPATH=0

# run workflow
cd examples/search/
chmod +x ./master.sh
./master.sh

