<?xml version="1.0" encoding="UTF-8"?>
<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.3.xsd" version="3.3" name="main" index="0" count="1">
   <file name="dax">
      <pfn url="file:///lfs1/scratch/mayani/core/015-shell-hierarchic-workflow/inner.dax" site="local"/>
   </file>
   <dax id="daxid" file="dax"/>
</adag>
