#!/bin/bash

set -e
set -v

testdir=`dirname  $0`
export testdir

$testdir/run-bamboo-test

# wait for workflow to finish
$testdir/../../common/wait-for-workflow

# check success with pegasus-analyzer - does it use exit codes correctly?
cd work/black-diamond-5.0api-*
pegasus-analyzer

# show some stats
pegasus-statistics -s all