#!/bin/bash

set -e
set -v


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`

# generate the input file
echo "This is sample input to KEG" >f.a

# output directory
mkdir -p outputs

# build the dax generator
export CLASSPATH=$testdir:`pegasus-config --classpath`
javac $testdir/BlackDiamondDAX.java

# generate the dax
java BlackDiamondDAX /usr blackdiamond.dax

# create the site catalog
cat >sites.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">
    <site handle="local" arch="x86_64" os="LINUX" osrelease="rhel" osversion="7">
        <directory type="shared-scratch" path="$TOPDIR/scratch">
            <file-server operation="all" url="file://$TOPDIR/scratch"/>
        </directory>
        <directory type="local-storage" path="$TOPDIR/outputs">
            <file-server operation="all" url="file://$TOPDIR/outputs"/>
        </directory>
        <profile namespace="env" key="PATH">$PEGASUS_BIN_DIR:/ccg/software/irods/3.3/bin:/usr/bin:/bin</profile>
    </site>

    <site  handle="fake-site" arch="x86_64" os="LINUX">
        <grid  type="gt5" contact="fake.isi.edu/jobmanager-fork" scheduler="Fork" jobtype="auxillary"/>
        <grid  type="gt5" contact="fake.isi.edu/jobmanager-condor1" scheduler="Condor" jobtype="compute"/>
    </site>

     <site  handle="CCG" arch="x86_64" os="LINUX">
        <grid  type="gt5" contact="obelix.isi.edu/jobmanager-fork" scheduler="Fork" jobtype="auxillary"/>
        <!-- incorrect end point given deliberately -->
        <grid  type="gt5" contact="obelix.isi.edu/jobmanager-condor1" scheduler="Condor" jobtype="compute"/>

        <directory type="shared-scratch" path="/lizard/scratch-90-days/CCG/scratch">
            <file-server operation="all" url="gsiftp://obelix.isi.edu/lizard/scratch-90-days/CCG/scratch"/>
        </directory>
        <directory type="local-storage" path="/lizard/scratch-90-days/CCG/outputs">
            <file-server operation="all" url="gsiftp://obelix.isi.edu/lizard/scratch-90-days/CCG/outputs"/>
        </directory>
        <profile namespace="pegasus" key="clusters.num">1</profile>
        <profile namespace="env" key="PEGASUS_HOME">/usr</profile>        
    </site>


</sitecatalog>
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites fake-site,CCG \
    --dir work \
    --output-sites local \
    --cluster horizontal \
    --dax blackdiamond.dax  | tee $TOPDIR/plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/^pegasus-run[ ]+//'`
cd $WORK_DIR

echo
echo
echo "Starting the workflow..."
pegasus-run $WORK_DIR


