#!/bin/bash

set -e


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`

# determine TEST_NAME to setup site catalog
TESTDIR=$(cd $testdir && pwd)
TEST_NAME=`basename $TESTDIR`

# generate the input file
echo "This is sample input to KEG" >f.a

# output directory
mkdir -p outputs

# build the dax generator
export CLASSPATH=$testdir:$(pegasus-config --classpath)
javac $testdir/BlackDiamondDAX.java

# generate the dax
java BlackDiamondDAX /opt/pegasus blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "fake-site"
  arch: "x86_64"
  os.type: "linux"
  grids:
   -
    type: "gt5"
    contact: "fake.isi.edu/jobmanager-condor1"
    scheduler: "condor"
    jobtype: "compute"
   -
    type: "gt5"
    contact: "fake.isi.edu/jobmanager-fork"
    scheduler: "fork"
    jobtype: "auxillary"
 -
  name: "CCG"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "localStorage"
    path: "/nfs/bamboo/scratch-90-days/CCG/${TEST_NAME}/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "scp://bamboo@slurm-pegasus.isi.edu:2222/nfs/bamboo/scratch-90-days/CCG/${TEST_NAME}/outputs"
   -
    type: "sharedScratch"
    path: "/nfs/bamboo/scratch-90-days/CCG/${TEST_NAME}/scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "scp://bamboo@slurm-pegasus.isi.edu:2222/nfs/bamboo/scratch-90-days/CCG/${TEST_NAME}/scratch"
  grids:
   -
    type: "gt5"
    contact: "obelix.isi.edu/jobmanager-condor1"
    scheduler: "condor"
    jobtype: "compute"
   -
    type: "batch"
    contact: "slurm-pegasus.isi.edu:2222"
    scheduler: "slurm"
    jobtype: "auxillary"
  profiles:
    env:
      PEGASUS_HOME: "/opt/pegasus"
    pegasus:
      change.dir: "true"
      clusters.num: "1"
      ssh_private_key: "/scitech/shared/home/bamboo/.ssh/workflow_id_rsa"
      style: "ssh"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "localStorage"
    path: "$TOPDIR/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/scratch"
  profiles:
    env:
      PATH: "$PEGASUS_BIN_DIR:/ccg/software/irods/3.3/bin:/usr/bin:/bin"
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites fake-site,CCG \
    --dir submit \
    --output-sites local \
    --cluster horizontal \
    blackdiamond.dax  | tee $TOPDIR/plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/^pegasus-run[ ]+//'`
cd $WORK_DIR

echo
echo
echo "Starting the workflow..."
pegasus-run $WORK_DIR
