#!/bin/bash

set -e

# Remove any old pth files that might exist
rm -f /Library/Python/2.*/site-packages/pegasus.pth

# Remove any old Pegasus symlinks
rm -f /Library/Python/2.*/site-packages/Pegasus

