.TH sgsc(1) WCS "14 April 1998"
.SH Name
sgsc \- Find HST GSC stars in a square on the sky
.SH Synopsis
sgsc [options] [-b or -j] ra dec
.SH Description
.I sgsc
is a utility for finding all of the Hubble Space Telescope Guide Star
Catalog objects in a specified region of the sky and listing them with their
sky positions and magnitudes in order of brightness, with the brighter ones
first.
Output is to standard out, unless the -w flag is set, in
which case it goes to objectname.gsc or search.gsc. It is somewhat
similar to RGSC, which can search from lists of coordinates but cannot
sort the output.  It is a link to scat.
.SH Options
.TP
.B \-a
List single closest catalog source
.TP
.B \-b <RA> <Dec>
Output B1950 (FK4) coordinates
.TP
.B \-d
Sort by distance from center instead of flux
.TP
.B \-g <class>
Object class (0=stars 3=galaxies -1=all)
.TP
.B \-h
Print heading, else do not 
.TP
.B \-j <RA> <Dec>
Output J2000 (FK5) coordinates around this center
.TP
.B \-m [<bright magnitude>] <faint magnitude>
Limiting catalog magnitude(s) (default none, bright -2 if only faint is given)
.TP
.B \-n <num>
Number of brightest stars to print 
.TP
.B \-o <name>
Object name used for output file naming
.TP
.B \-r <radius>
Radius of search circle 1in arcsec (default 10)
.TP
.B \-s
Sort by RA instead of flux 
.TP
.B \-t
Tab table to standard output as well as file
.TP
.B \-v
Verbose listing of processing intermediate results
.TP
.B \-w
Write tab table output file imagename.gsc
.SH See Also
scat(1), rgsc(1), suac(1), susac(1), imgsc(1)
.SH Author
Doug Mink, SAO (dmink@cfa.harvard.edu)
