[tox]
envlist = py39, py310, py311, py312, py313, py314
skip_missing_interpreters = True
minversion = 4.0

[testenv]
commands = pytest --junit-xml test-reports/pyunit.xml --cov --cov-branch --cov-report term --cov-report html:test-reports/htmlcov --cov-report xml:test-reports/coverage.xml --cov-fail-under 20 {posargs:test}

passenv =
    USER
    CPATH

setenv =
    PYTHONUNBUFFERED = yes
    PYTHONHASHSEED   = 3104489401
    USER             = {env:USER:nobody}

deps =
    pytest
    pytest-mock
    coverage
    pytest-cov
    pytest-resource-path
    jsonschema
    cwl-utils>=0.11

[testenv:lint]
basepython = python3.9

skipsdist = True
skip_install = True

allowlist_externals = bash

commands =
    ruff check {toxinidir}/src {toxinidir}/test
    ruff format --check {toxinidir}/src {toxinidir}/test

deps =
    ruff
