#!/bin/bash

set -e

echo "Running blackdiamond.py"
export PYTHONPATH=`pegasus-config --python`
python3 blackdiamond.py | tee plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

echo "WORK_DIR is $WORK_DIR"

# check in the submit directory to make sure that noop job exists
set +e
ls $WORK_DIR/*sub | grep -v noop_ | grep -v condor.sub
EC=$?
set -e

if [ $EC -eq 0 ]; then
    echo "ERROR: Test Failed - Submit directory contains jobs other than noop job"
    exit 1
fi

#submit the workflow
pegasus-run $WORK_DIR
