[tox]

default_base_python = 3.14, 3.13, 3.12, 3.11, 3.10

envlist = py310, py311, py312, py313, py314, py315
skip_missing_interpreters = True
minversion = 3.4.0


[testenv]

commands     = pytest --junit-xml test-reports/pyunit.xml --cov --cov-branch --cov-report term --cov-report html:test-reports/htmlcov --cov-report xml:test-reports/coverage.xml --cov-fail-under 25.5 {posargs:test}

passenv      =
    USER
    CPATH

setenv       =
    PYTHONUNBUFFERED = yes
    PYTHONHASHSEED   = 3104489401
    USER             = {env:USER:nobody}

skip_install = {env:SKIP_INSTALL:False}

deps         =
    pytest
    pytest-mock
    coverage
    pytest-cov
    pytest-resource-path
    jsonschema
    py37: bagit<1.9.0
    cwl-utils==0.11
    ../pegasus-common
    ../pegasus-worker
    ../pegasus-api


[testenv:lint]

skipsdist               = True

skip_install            = True

commands                =
    ruff check  --target-version py310
    ruff format --target-version py310

deps                    =
    ruff


[testenv:docs]

changedir           = ../../doc/sphinx

allowlist_externals = make

commands_pre        =
    sphinx-apidoc     --force --implicit-namespaces --output-dir python {toxinidir}/../pegasus-api/src/Pegasus
    # sphinx-apidoc     --force --implicit-namespaces --output-dir python {toxinidir}/src/Pegasus {toxinidir}/{setup,test}.py {toxinidir}/Pegasus/{cluster,command,compat,exitcode,init,s3,submitdir,user}.py {toxinidir}/Pegasus/{test,db,monitoring,catalogs,cli,netlogger,plots_stats,service,tools}
    # javasphinx-apidoc --update --output-dir java   {toxinidir}/../../src {toxinidir}/../../src/edu/isi/pegasus/aws/batch/common/

commands            = make html man latexpdf

skipsdist           = True

deps                =
    sphinx
    recommonmark
    sphinx_rtd_theme
    sphinxcontrib-openapi
    sphinx_tabs
    sphinx-click
    ../pegasus-common
    ../pegasus-worker
    ../pegasus-api
