#!/bin/bash

set -e

TOPDIR=`pwd`

# plan and submit the  workflow
pegasus-plan \
    --conf pegasusrc \
    --dir work \
    --sites Trestles \
    --output-site local \
    --cleanup none \
    --dax workflow.dax \
    --submit

