#!/bin/bash

set -e

pegasus-plan \
    --conf properties \
    -vvvv \
    --dax blackdiamond_dax.xml \
    --sites cloud 

cd $USER/pegasus/blackdiamond/run0001/

echo
echo

for FILE in `ls sls*.in stage*.in`; do
    echo "Cecking $FILE..."
    if ! (cat $FILE | grep s3://) >/dev/null 2>&1; then
       echo "   No s3 URLS found!"
       exit 1
   fi 
done

