#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH
export LD_LIBRARY_PATH=/ccg/software/sqlite/3.8.11.1/lib:$LD_LIBRARY_PATH

rm -rf montage-workflow-v2
git clone https://github.com/pegasus-isi/montage-workflow-v2.git

echo
cd montage-workflow-v2
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.2 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

sqlitedb=`mktemp -p ${PWD} pegasus-XXXX.jdbcrc.sqlite.db`
sqlitedburl=jdbc:sqlite:/${sqlitedb}

cat pegasus.properties >> ../pegasusrc

cat >>../pegasusrc <<EOF
pegasus.stageout.clusters = 20

#we don't want errors for registration to be masked because of retries
dagman.retry 0

pegasus.catalog.replica = JDBCRC
pegasus.catalog.replica.db.driver sqlite
pegasus.catalog.*.timeout = 30

pegasus.catalog.replica.db.url = ${sqlitedburl}
EOF

echo "Creating jdbcrc $sqlitedb"
pegasus-db-admin create ${sqlitedburl}

echo "Inserting input entries in the database..."
pegasus-rc-client -vvv --conf ../pegasusrc --insert data/rc.txt

echo "Planning and submitting the workflow..."
pegasus-plan \
    --conf ../pegasusrc \
    --sites condor_pool \
    --dir work \
    --output-sites local \
    --cleanup leaf \
    --dax data/montage.dax \
    --cluster horizontal \
    --submit | tee $TOP_DIR/plan.out


