#!/bin/bash

set -e

TOPDIR=`pwd`

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./dax-generator.py >dax.xml

# create the site catalog
echo "" >f.a

# plan and submit the  workflow
pegasus-plan \
    --conf pegasusrc \
    --sites USC_HPCC_Bosco \
    --output-site local \
    --dir work \
    --dax dax.xml \
    --cleanup none \
    --submit

