pegasus: "5.0"
name: diamond

hooks:
  shell:
    - _on: start
      cmd: "/pegasus/libexec/notification/email -t notify@example.com"
    - _on: at_end
      cmd: "/pegasus/libexec/notification/email -t notify@example.com"

replicaCatalog:
  replicas:
    - lfn: f.a
      pfns:
        - {site: local, pfn: "file:///Volumes/Work/lfs1/work/pegasus-features/PM-902/f.a"}

transformationCatalog:
  transformations:
    - namespace: pegasus
      name: preprocess
      version: "4.0"
      sites:
        - {name: TestCluster, pfn: "file:///usr/bin/keg", type: installed, arch: x86, os.type: linux}
    - namespace: pegasus
      name: findrange
      version: "4.0"
      sites:
        - {name: TestCluster, pfn: "file:///usr/bin/keg", type: installed, arch: x86, os.type: linux}
    - namespace: pegasus
      name: analyze
      version: "4.0"
      sites:
        - {name: TestCluster, pfn: "file:///usr/bin/keg", type: installed, arch: x86, os.type: linux}

jobs:
  - type: job
    id: j1
    name: preprocess
    namespace: pegasus
    version: "4.0"
    arguments:
      - ""
    hooks:
      shell:
        - _on: start
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
        - _on: at_end
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
    uses:
      - {lfn: f.a, type: input}
      - {lfn: f.b1, type: output, stageOut: true, registerReplica: true}
      - {lfn: f.b2, type: output, stageOut: true, registerReplica: true}
  - type: job
    id: j2
    name: findrange
    namespace: pegasus
    version: "4.0"
    arguments:
      - ""
    hooks:
      shell:
        - _on: start
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
        - _on: at_end
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
    uses:
      - {lfn: f.b1, type: input}
      - {lfn: f.c1, type: output, stageOut: true, registerReplica: true}
  - type: job
    id: j3
    name: findrange
    namespace: pegasus
    version: "4.0"
    arguments:
      - -a findrange -T 60 -i f.b2 -o f.c2
    hooks:
      shell:
        - _on: start
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
        - _on: at_end
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
    uses:
      - {lfn: f.b2, type: input}
      - {lfn: f.c2, type: output, stageOut: true, registerReplica: true}
  - type: job
    id: j4
    name: analyze
    namespace: pegasus
    version: "4.0"
    arguments:
      - "-a analyze -T 60 -if.c1,f.c2 -of.d"
    hooks:
      shell:
        - _on: start
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
        - _on: at_end
          cmd: "/pegasus/libexec/notification/email -t notify@example.com"
    uses:
      - {lfn: f.c1, type: input}
      - {lfn: f.c2, type: input}
      - {lfn: f.d, type: output, stageOut: true, registerReplica: true}
  - type: job
    id: j5
    name: inspiral-full-data
    namespace: ligo
    version: "4.0"
    arguments:
      - "--frame-files --V1:V-HrecV2-967640000-10000.gwf --L1:L-L1_LDAS_C02_L2-967648128-128.gwf --L1:L-L1_LDAS_C02_L2-967648256-128.gwf --output V1H1L1-INSPIRAL_FULL_DATA_JOB0-967648572-1105.xml.gz --bank-file H1L1V1-PREGEN_TMPLTBANK_SPLITTABLE_BANK0-967593543-86400.xml.gz --user-tag FULL_DATA"
    uses:

jobDependencies:
  - id: j1
    children:
      - j2
      - j3
  - id: j2
    children:
      - j4
  - id: j3
    children:
      - j4
