#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH

rm -rf montage-workflow-v2
git clone https://github.com/pegasus-isi/montage-workflow-v2.git

echo
echo

cd montage-workflow-v2
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.5 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

# custom site catalog
echo
echo "Creating the site catalog..."
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "CCG"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "/lizard/scratch-90-days/ptesting"
    fileServers:
     -
      operation: "all"
      url: "gsiftp://obelix.isi.edu/lizard/scratch-90-days/ptesting"
  grids:
   -
    type: "gt5"
    contact: "obelix.isi.edu/jobmanager-condor"
    scheduler: "condor"
    jobtype: "compute"
   -
    type: "gt5"
    contact: "obelix.isi.edu/jobmanager-fork"
    scheduler: "fork"
    jobtype: "auxillary"
  profiles:
    env:
      MONTAGE_HOME: "/ccg/software/montage/current"
      PEGASUS_HOME: "/usr"
      http_proxy: "http://workflow.isi.edu:3128"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "$PWD/scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/scratch"
   -
    type: "sharedStorage"
    path: "$PWD/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/outputs"
  grids:
   -
    type: "gt2"
    contact: "localhost/jobmanager-fork"
    scheduler: "fork"
    jobtype: "auxillary"
  profiles:
    env:
      GLOBUS_LOCATION: "/ccg/software/globus/default"
      GLOBUS_TCP_PORT_RANGE: "40000,50000"
      http_proxy: "http://workflow.isi.edu:3128"
EOF

echo "Planning and submitting the workflow..."
pegasus-plan \
    --conf ../pegasusrc \
    --sites CCG \
    --dir work \
    --output-site local \
    --dax data/montage.dax \
    --cluster horizontal \
    --submit \
    | tee $TOP_DIR/plan.out


