#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH
export PYTHONPATH=`pegasus-config --python`

rm -rf montage-workflow-v3
git clone https://github.com/pegasus-isi/montage-workflow-v3.git

echo
echo

cd montage-workflow-v3
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.5 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

# custom site catalog
echo
echo "Creating the site catalog..."
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "CCG"
  arch: "x86_64"
  os.type: "linux"
  directories:
  - 
    type: "sharedScratch" 
    path: "/nfs/bamboo/scratch-90-days/CCG/scratch/ptesting" 
    fileServers: 
     - 
      operation: "all" 
      url: "scp://bamboo@corbusier.isi.edu:2222/nfs/bamboo/scratch-90-days/CCG/scratch/ptesting" 
  grids: 
   - 
    type: "batch" 
    contact: "corbusier.isi.edu" 
    scheduler: "slurm" 
    jobtype: "compute" 
   - 
    type: "batch" 
    contact: "corbusier.isi.edu" 
    scheduler: "slurm" 
    jobtype: "compute" 
  profiles: 
    env: 
      PEGASUS_HOME: "/opt/pegasus" 
      MONTAGE_HOME: /opt/software/montage/current
      http_proxy: "workflow.isi.edu:3128"
    pegasus: 
      # SSH is the style to use for Bosco SSH submits. 
      style: ssh 
      # Works around bug in the HTCondor GAHP, that does not 
      # set the remote directory 
      change.dir: 'true' 
      # the key to use for scp transfers 
      SSH_PRIVATE_KEY: /scitech/home/bamboo/.ssh/workflow_id_rsa 

 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "$PWD/scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/scratch"
   -
    type: "sharedStorage"
    path: "$PWD/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/outputs"
  grids:
   -
    type: "gt5"
    contact: "localhost/jobmanager-fork"
    scheduler: "fork"
    jobtype: "auxillary"
  profiles:
    env:
      GLOBUS_LOCATION: "/ccg/software/globus/default"
      GLOBUS_TCP_PORT_RANGE: "40000,50000"
      http_proxy: "workflow.isi.edu:3128"
EOF

cp ../pegasus.properties .

echo "Planning and submitting the workflow..."
pegasus-plan \
    --sites CCG \
    --dir work \
    --output-sites local \
    --cluster horizontal \
    --submit \
    data/montage-workflow.yml \
    | tee $TOP_DIR/plan.out


