#!/bin/bash

set -e


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`

export PEGASUS_BIN_DIR=`pegasus-config --bin`

# generate the input file
echo "This is sample input to KEG" >f.a

# output directory
mkdir -p outputs


# build the workflow generator
export CLASSPATH=$testdir:`pegasus-config --classpath`
javac $testdir/BlackDiamondWorkflow.java

# generate the workflow
java BlackDiamondWorkflow /usr blackdiamond.yml

# create the site catalog
cat >sites.yml <<EOF
---
pegasus: "5.0"
sites:
 -
  name: "cartman-data"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "${TOPDIR}/staging-site/scratch"
    fileServers:
     -
      operation: "all"
      url: "gsiftp://bamboo.isi.edu/${TOPDIR}/staging-site/scratch"
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    env:
      PATH: "/ccg/software/irods/3.3/bin:/usr/bin:/bin"
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "localStorage"
    path: "$TOPDIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/scratch"
  profiles:
    env:
      PATH: "$PEGASUS_BIN_DIR:/ccg/software/irods/3.3/bin:/usr/bin:/bin"
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites condorpool \
    --staging-site cartman-data \
    --dir work \
    --output-sites local \
    blackdiamond.yml  | tee $TOPDIR/plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/^pegasus-run[ ]+//'`
cd $WORK_DIR

echo
echo
echo "Starting the workflow..."
pegasus-run $WORK_DIR


