// Package integrity computes the SHA-256 checksums pegasus-transfer emits
// for checksummed transfers, in-process rather than shelling out to the
// standalone pegasus-integrity tool. Output is byte-for-byte compatible with
// pegasus-integrity's --generate-fullstat-yaml, since kickstart and
// downstream integrity verification consume that exact format.
//
// The standalone pegasus-integrity tool itself is unchanged and still used
// by other callers (kickstart, users); this package only replaces the
// callout that used to happen from within pegasus-transfer.
package integrity

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/user"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Generator produces and records fullstat-checksum YAML for LFNs, matching
// transfer.py's TransferHandlerBase._generate_integrity_checksum: each LFN
// is only checksummed once per run.
type Generator struct {
	mu   sync.Mutex
	seen map[string]bool
}

func NewGenerator() *Generator {
	return &Generator{seen: map[string]bool{}}
}

// Generate computes the checksum for path (identified by lfn) and appends
// the resulting YAML block to $KICKSTART_INTEGRITY_DATA, matching
// pegasus-integrity's --generate-fullstat-yaml output destination. A no-op
// if lfn was already checksummed this run.
func (g *Generator) Generate(lfn, path string) error {
	if lfn == "" {
		return fmt.Errorf("lfn is required when enabling checksumming")
	}

	g.mu.Lock()
	defer g.mu.Unlock()

	if g.seen[lfn] {
		return nil
	}

	yaml, err := fullstatYAML(lfn, path)
	if err != nil {
		return err
	}

	if err := emit(yaml); err != nil {
		return err
	}
	g.seen[lfn] = true
	return nil
}

func emit(yaml string) error {
	path, ok := os.LookupEnv("KICKSTART_INTEGRITY_DATA")
	if !ok {
		// pegasus-integrity's CLI prints to stdout when the env var is
		// unset; preserved here for parity, though in practice kickstart
		// always sets it during a real job.
		fmt.Println(yaml)
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(yaml)
	return err
}

// fullstatYAML reproduces pegasus-integrity.py's generate_fullstat_yaml()
// exactly: sha256 first (with timing), then a full stat() snapshot.
func fullstatYAML(lfn, path string) (string, error) {
	start := time.Now()
	sum, err := sha256File(path)
	if err != nil {
		return "", err
	}
	elapsed := time.Since(start)

	info, err := os.Stat(path)
	if err != nil {
		// Matches Python: if stat fails after the checksum succeeded,
		// return an empty (not erroring) result.
		return "", nil
	}
	st := statFile(info)

	uname := lookupUser(st.Uid)
	gname := lookupGroup(st.Gid)

	var b strings.Builder
	fmt.Fprintf(&b, "    %q:\n", lfn)
	b.WriteString("      comment: entry generated by pegasus-integrity\n")
	fmt.Fprintf(&b, "      file_name: %q\n", path)
	fmt.Fprintf(&b, "      mode: 0o%o\n", st.Mode)
	fmt.Fprintf(&b, "      size: %d\n", info.Size())
	fmt.Fprintf(&b, "      inode: %d\n", st.Ino)
	fmt.Fprintf(&b, "      nlink: %d\n", st.Nlink)
	fmt.Fprintf(&b, "      mtime: %s\n", iso8601(st.Mtime))
	fmt.Fprintf(&b, "      atime: %s\n", iso8601(st.Atime))
	fmt.Fprintf(&b, "      ctime: %s\n", iso8601(st.Ctime))
	fmt.Fprintf(&b, "      uid: %d\n", st.Uid)
	fmt.Fprintf(&b, "      user: %s\n", uname)
	fmt.Fprintf(&b, "      gid: %d\n", st.Gid)
	fmt.Fprintf(&b, "      group: %s\n", gname)
	b.WriteString("      output: True\n")
	fmt.Fprintf(&b, "      sha256: %s\n      checksum_timing: %.3f\n", sum, elapsed.Seconds())

	return b.String(), nil
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("file %s does not exist", path)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func lookupUser(uid uint32) string {
	u, err := user.LookupId(strconv.FormatUint(uint64(uid), 10))
	if err != nil {
		return ""
	}
	return u.Username
}

func lookupGroup(gid uint32) string {
	g, err := user.LookupGroupId(strconv.FormatUint(uint64(gid), 10))
	if err != nil {
		return ""
	}
	return g.Name
}

// iso8601 matches pegasus-integrity.py's iso8601(): UTC, seconds precision
// via datetime.isoformat() (microseconds included when non-zero).
func iso8601(t time.Time) string {
	t = t.UTC()
	if t.Nanosecond() == 0 {
		return t.Format("2006-01-02T15:04:05+00:00")
	}
	return t.Format("2006-01-02T15:04:05.000000+00:00")
}
