#!/bin/bash

set -e

VERSION=$1

TOP_DIR=`pwd`

# make sure we are in a source dir
if [ ! -e build.xml ]; then
    echo "This does not look a like a source directory. Exiting..."
    exit 1
fi

mkdir -p build/rpm/BUILD build/rpm/RPMS build/rpm/SOURCES build/rpm/SPECS build/rpm/SRPMS

cp dist/pegasus-$VERSION.tar.gz build/rpm/SOURCES/

# create a new spec file with the custom version
BASEVER=`echo "$VERSION" | perl -p -e 's/([0-9]+\.[0-9]+\.[0-9]+).*/\1/'`
EXTRAVER=`echo "$VERSION" | perl -p -e 's/[0-9]+\.[0-9]+\.[0-9]+//'`
RELEASE_VERSION="1%{?dist}"
if [ "x$EXTRAVER" != "x" ]; then
    # add timestamp - the goal is a version number like:
    # 4.8.1dev-0.1.201709070934
    RELEASE_VERSION="0.1."`date +'%Y%m%d%H%M'`"%{?dist}"
fi

cp pegasus.spec.in pegasus.spec
DATE_RPM=`date +'%a %b %d %Y'`
perl -p -i -e "s/\\@PEGASUS_VERSION\\@/$VERSION/g" pegasus.spec
perl -p -i -e "s/\\@DATE\\@/$DATE_RPM/g" pegasus.spec
perl -p -i -e "s/^Release:.*/Release:        $RELEASE_VERSION/g" pegasus.spec

cp pegasus.spec build/rpm/SPECS/

DIST=`./release-tools/getosid | perl -pe 's/rhel/.el/'`

rpmbuild -ba --define "_topdir $TOP_DIR/build/rpm" --define "dist $DIST" pegasus.spec

find build/rpm -name \*.rpm -exec cp {} dist/ \;
rm -f dist/*debug*
mv dist/pegasus-*.src.rpm dist/pegasus-$VERSION.src.rpm
cd dist
echo "Generated RPMs:"
ls -l *.rpm


