#!/bin/bash

set -e
set -v

VERSION=$1

# make sure we are in a source dir
if [ ! -e build.xml ]; then
    echo "This does not look a like a source directory. Exiting..."
    exit 1
fi

TOP_DIR=`pwd`

mkdir -p dist/pegasus-$VERSION

for ITEM in `ls | grep -E -v '^(build|dist)$'`; do
    cp -a $ITEM dist/pegasus-$VERSION/
done

# remove some stuff we don't want in the source tar
for ITEM in .git .gitignore; do
    find dist/pegasus-$VERSION/ -name $ITEM -exec rm -rf {} \;
done

# create a debian/changelog - this is important to LIGO and other projects
# picking up our source tarball and building Debian packages
cd dist/pegasus-$VERSION/debian
cp changelog.in changelog
DATE_DEB=`date -R`
perl -p -i -e "s/\\@PEGASUS_VERSION\\@/$VERSION/g" changelog
perl -p -i -e "s/\\@DATE\\@/$DATE_DEB/g" changelog
perl -p -i -e "s/\\+\\@OSID\\@//g" changelog
cd $TOP_DIR

# Set the git hash in build.properties so that we have it saved
HASH=$(git rev-parse HEAD)
printf "pegasus.build.git.hash = $HASH\n" > dist/pegasus-$VERSION/build.git.properties

cd dist/
tar czf pegasus-$VERSION.tar.gz pegasus-$VERSION
rm -rf pegasus-$VERSION

