#!/bin/bash

set -e
set -v

VERSION=$1

# make sure we are in a source dir
if [ ! -e build.xml ]; then
    echo "This does not look a like a source directory. Exiting..."
    exit 1
fi

TOP_DIR=$PWD

rm -f lib/pegasus/python/dist/pegasus*.tar.gz
mkdir -p dist

# create the dist package
for pkg in `find packages -type d -depth 1`; do
    if [ -e setup.py ]; then
        continue
    fi

    ( cd ${pkg} && /usr/bin/env python setup.py sdist)

    # python is now normalizing the version (see PEP 440)
    cd ${pkg}/dist
    ls -l
    NORM_VERSION=`ls *.tar.gz | sed 's/pegasus-wms.*-//' | sed 's/\.tar\.gz//'`
    echo "Normalized verison is $NORM_VERSION"

    tar xzf pegasus-wms-$NORM_VERSION.tar.gz
    sed -i.bak -e s/version=read_version\(\)/version=\"${VERSION}\"/g pegasus-wms-${NORM_VERSION}/setup.py
    rm pegasus-wms-${NORM_VERSION}/setup.py.bak

    # create the final tarball
    tar czf $TOP_DIR/dist/pegasus-python-source-${VERSION}.tar.gz pegasus-wms-${NORM_VERSION}
    rm -rf pegasus-wms-${NORM_VERSION}*

done
