#!/bin/bash

set -e

# PEGASUS_PYTHON - allow override for users who really do not
# like the system python

# First look in the PATH for specific versions (3.17 down to 3.10)
I=0
for v in {17..10}; do
    # Try to find the specific version in the user's current PATH
    if TARGET_PATH=$(which "python3.$v" 2>/dev/null); then
        eval PEXE_LIST$I="\$TARGET_PATH"
        I=$((I+1))
    fi
done

# Next, catch a generic python3 from the PATH if no specific versions matched
if TARGET_PATH=$(which python3 2>/dev/null); then
    eval PEXE_LIST$I="\$TARGET_PATH"
    I=$((I+1))
fi

# Has to be last to find user defined environments / system fallbacks
if [ -x "/usr/bin/python3" ]; then
    eval PEXE_LIST$I="/usr/bin/python3"
    I=$((I+1))
fi

# Look for a python in the give list
for i in `seq $I`; do
    VAR=\$PEXE_LIST$((i-1))
    PEXE=`eval echo $VAR`
    if [ -e "$PEXE" ]; then
        break
    fi
done

if [ "x$PEXE" = "x" ]; then
    echo "ERROR: Unable to find python3!" >&2
    exit 1
fi

# determine the version
MAJOR=`$PEXE -V 2>&1 | sed -e 's/^.* \([0-9]*\)\.[0-9].*$/\1/'`
MINOR=`$PEXE -V 2>&1 | sed -e 's/^.* [0-9]*\.\([0-9]*\).*$/\1/'`

if [ $MAJOR = 3 -a $MINOR -lt 10 ]; then
    echo "ERROR: Pegasus requires at least Python 3.10" >&2
    exit 1
fi

# to be specific, expand the path if possible
if [ -e "$PEXE$MAJOR.$MINOR" ]; then
    echo "$PEXE$MAJOR.$MINOR"
    exit 0
fi

echo "$PEXE"
