#!/bin/bash

set -e

# PEGASUS_PYTHON - allow override for users who really do not
# like the system python

# Look for a python in a pre-determined order, prefer Python3
for CANDIDATE in $PEGASUS_PYTHON \
            /usr/bin/python3 \
            /usr/bin/python3.13 \
            /usr/bin/python3.12 \
            /usr/bin/python3.11 \
            /usr/bin/python3.10 \
            `which python3 2>/dev/null` \
    ; do
    if [ -e "$CANDIDATE" ]; then
        # determine the version
        VERSION=$($CANDIDATE -V 2>&1)
        MAJOR=$(echo $VERSION | sed -e 's/^.* \([0-9]*\)\.[0-9].*$/\1/')
        MINOR=$(echo $VERSION | sed -e 's/^.* [0-9]*\.\([0-9]*\).*$/\1/')

        if [ $MAJOR = 3 -a $MINOR -lt 10 ]; then
            continue
        fi

        PEXE=$CANDIDATE
        break
    fi
done

if [ "x$PEXE" = "x" ]; then
    echo "ERROR: Unable to find python3!" >&2
    exit 1
fi

# to be specific, expand the path if possible
if [ -e "$PEXE$MAJOR.$MINOR" ]; then
    echo "$PEXE$MAJOR.$MINOR"
    exit 0
fi

echo "$PEXE"


