#!/bin/bash

TOP_DIR=`(cd ${BASH_SOURCE%/*}/.. && pwd)`

. $TOP_DIR/share/pegasus/sh/pegasus-lite-common.sh

SYSTEM=$(pegasus_lite_get_system)
if [ $? != 0 ]; then
    echo "Unable to determine the system identifier. pegasus_lite_get_system returned: $SYSTEM"
    exit 1
fi

# strip architechture
OSID=$(echo $SYSTEM | grep -E -o '[a-zA-Z]+_[0-9]+$' | sed 's/_//')

echo $OSID
exit 0

