#!/bin/bash

TOP_DIR=`(cd ${BASH_SOURCE%/*}/.. && pwd)`

. $TOP_DIR/share/pegasus/sh/pegasus-lite-common.sh

SYSTEM=$(pegasus_lite_get_system)
if [ $? != 0 ]; then
    echo "Unable to determine the system identifier. pegasus_lite_get_system returned: $SYSTEM"
    exit 1
fi
echo $SYSTEM
exit 0

