#!/bin/bash

# this script figures out the location of the system Python
# modules - note that we are using the python in /usr/bin
# for this, and not the one in the users environment

PYTHON=$($(dirname $0)/get-system-python)

# pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
# Extract        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PIP_LOCATION=$(${PYTHON} -m pip -V | awk '{print $4}')

# Strip out trailing pip dir from path, if present
echo $PIP_LOCATION | grep "pip$" --quiet
if [ $? -eq 0 ]; then
    PIP_LOCATION=`dirname $PIP_LOCATION`
fi

# Get path relative to the Python prefix
PYTHON_PREFIX=$(${PYTHON} -c "import sys; print('${PIP_LOCATION}'.replace(sys.prefix, '').lstrip('/'))")

echo ${PYTHON_PREFIX}
