.\"
.\" This file or a portion of this file is licensed under the terms of
.\" the Globus Toolkit Public License, found in file GTPL, or at
.\" http://www.globus.org/toolkit/download/license.html. This notice must
.\" appear in redistributions of this file, with or without modification.
.\"
.\" Redistributions of this Software, with or without modification, must
.\" reproduce the GTPL in: (1) the Software, or (2) the Documentation or
.\" some other similar material which is provided with the Software (if
.\" any).
.\"
.\" Copyright 1999-2004 University of Chicago and The University of
.\" Southern California. All rights reserved.
.\"
.\" $Id$
.\"
.\" Authors: Jens-S. Vöckler, Yong Zhao
.\"
.\"
.TH "pegasus\-invoke" "1" "3.2.0" "Pegasus WMS"
.SH "NAME"
pegasus\-invoke \- invokes a command from a file
.SH "SYNTAX"
.B pegasus\-invoke ( app | @fn ) [ arg | @fn [..]]
.SH "DESCRIPTION"
The 
.B pegasus\-invoke
tool invokes a single application with as many arguments as your Unix
permits (128k characters for Linux). Arguments are come from two places,
either the command-line as regular arguments, or from a special file, 
which contains one argument per line. 
.PP
The
.B pegasus\-invoke
tool became necessary to work around the 4k argument length limit in
Condor. It also permits to use arguments inside argument files without
worry about shell, Condor or Globus escape necessities. All argument
file contents are passed as is, one line per argument entry. 
.SH "ARGUMENTS"
.TP
.B \-d
This option increases the debug level. Currently, only debugging or
no debugging is distinguished. Debug message are generated on 
.IR stdout .
.IP
By default, debugging is disabled.
.TP
.B \-h
This option prints the help message and exits the program.
.TP
.B \-\-
This option stops any option processing. It may only be necessary,
if the application is stated on the command-line, and starts with
a hyphen itself. 
.LP
The first argument must either be the application to run as
fully-specified location (either absolute, or relative to current wd),
or a file containing one argument per line. The 
.I PATH
environment variables is 
.B not
used to locate an application.
.PP
Subsequent arguments may either be specified explicitely on the
commandline. Any argument that starts with an at (@) sign is taken
to introduce a filename, which contains one argument per line. 
.PP
The textual file may contain long arguments and filenames. However,
Unices still impose limits on the maximum length of a directory name,
and the maximum length of a file name. These lengths are not checked, 
because 
.B pegasus\-invoke
is oblivious of the application (e.g. what argument is a filename, and
what argument is a mere string resembling a filename). 
.SH "RETURN VALUE"
The
.B pegasus\-invoke
tool returns 127, if it was unable to find the application. It returns
126, if there was a problem parsing the file. All other exit status,
including 126 and 127, come from the application. 
.SH "SEE ALSO"
.BR pegasus\-kickstart (1).
.SH "EXAMPLE"
.nf
\f(CB
$ echo "/bin/date" > X
$ echo "-Isec" >> X
$ pegasus\-invoke @X
2005-11-03T15:07:01-0600
\fP
.fi
.PP
Recursion is also possible. Please mind not to use circular inclusions.
Also note how duplicating the initial at (@) sign will escape its
meaning as inclusion symbol.
.nf
\f(CB
$ cat test.3
This is test 3

$ cat test.2
/bin/echo
@test.3
@@test.3

$ pegasus\-invoke @test.2
This is test 3 @test.3
\fP
.fi
.SH "RESTRICTIONS"
While the arguments themselves may contain files with arguments to
parse, starting with an at (@) sign as before, the maximum recursion
limit is 32 levels of inclusions. It is not possible (yet) to use
.I stdin
as source of inclusion.
.SH "HISTORY"
As you may have noticed,
.B pegasus\-invoke
had the name
.B invoke
in previous incantations. We are slowly moving to the new name to avoid
clashes in a larger OS installation setting. However, there is no
pertinent need to change the internal name, too, as no name clashes are
expected.
.SH "RETIRED AUTHORS"
Mike Wilde <wilde at mcs dot anl dot gov>
.SH "AUTHORS"
Jens-S. Vöckler <voeckler at isi dot edu>
.PP
Pegasus 
.BR http://pegasus.isi.edu/
