#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH

rm -rf montage-workflow-v3
git clone https://github.com/pegasus-isi/montage-workflow-v3.git

echo
echo

cd montage-workflow-v3
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.5 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

# custom site catalog
echo
echo "Creating the site catalog..."
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "CCG"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    env:
      MONTAGE_HOME: "/ccg/software/montage/current"
      GLOBUS_LOCATION: "/ccg/software/globus/default"
      http_proxy: "workflow.isi.edu:3128"
    condor:
      requirements: "(TARGET.FileSystemDomain =!= \"\")"
      should_transfer_files: "Yes"
      when_to_transfer_output: "ON_EXIT"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$PWD/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/outputs"
   -
    type: "sharedScratch"
    path: "$PWD/scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$PWD/scratch"
  grids:
   -
    type: "gt2"
    contact: "localhost/jobmanager-fork"
    scheduler: "fork"
    jobtype: "auxillary"
  profiles:
    env:
      GLOBUS_LOCATION: "/ccg/software/globus/default"
      GLOBUS_TCP_PORT_RANGE: "40000,50000"
      http_proxy: "workflow.isi.edu:3128"
 -
  name: "CCGData"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "/data/scratch/ptesting"
    fileServers:
     -
      operation: "all"
      url: "gsiftp://obelix.isi.edu/data/scratch/ptesting"
EOF

cp ../pegasus.properties .

echo "Planning and submitting the workflow..."
pegasus-plan \
    --sites CCG \
    --staging-site CCGData \
    --dir work \
    --output-site local \
    --cleanup leaf \
    --dax data/montage-workflow.yml \
    --cluster horizontal \
    --submit \
    | tee $TOP_DIR/plan.out
