#!/bin/bash

set -e

TOP_DIR=`pwd`

# download rosetta binary - this is to save space in the Pegasus distribution
if [ ! -e rosetta.exe ]; then
   wget -q http://pegasus.isi.edu/wms/example-workflows/rosetta/rosetta.exe
   chmod 755 rosetta.exe
fi

# do we have the required minirosetta_database?
if [ ! -e minirosetta_database ]; then
   wget -q http://pegasus.isi.edu/wms/example-workflows/rosetta/minirosetta_database.tar.gz
   tar xzf minirosetta_database.tar.gz
   rm minirosetta_database.tar.gz
fi

# what about the required pdbs?
if [ ! -e pdbs ]; then
   wget -q http://pegasus.isi.edu/wms/example-workflows/rosetta/pdbs.tar.gz
   tar xzf pdbs.tar.gz
   rm pdbs.tar.gz
fi

# figure out where Pegasus is installed
export PEGASUS_BIN_DIR=`pegasus-config --bin`
if [ "x$PEGASUS_BIN_DIR" = "x" ]; then
    echo "Please make sure pegasus-plan is in your path"
    exit 1
fi

# build the dax generator
javac RosettaDAX.java

# generate the dax
java RosettaDAX dax.xml

#empty replica catalog
touch rc.data

# site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "condor_pool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    env:
      PATH: "/ccg/software/irods/4.1.4/bin:/usr/bin:/bin"
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "staging_site"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "/nara-renci-irods/home/rynge/workflows/scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "get"
      url: "irods:///nara-renci-irods/home/rynge/workflows/scratch"
     -
      operation: "put"
      url: "irods:///nara-renci-irods/home/rynge/workflows/scratch"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "localStorage"
    path: "$TOP_DIR/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOP_DIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOP_DIR/scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOP_DIR/scratch"
  profiles:
    env:
      PATH: "$PEGASUS_BIN_DIR:/ccg/software/irods/4.1.4/bin:/usr/bin:/bin"
EOF

echo
echo
echo "The site catalog is:"
cat sites.yml

echo
echo
echo "Planning the workflow..."
pegasus-plan \
    --conf pegasusrc \
    --dir submit \
    --sites condor_pool \
    --staging-site staging_site \
    --output-sites local \
    dax.xml \
    | tee $TOP_DIR/plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/^pegasus-run[ ]+//'`
cd $WORK_DIR

echo
echo
echo "Starting the workflow..."
pegasus-run $WORK_DIR
