#!/bin/bash

set -e
set -v


TOPDIR=`pwd`

# unique directory for this run
RUN_ID=`/bin/date +'%F_%H%M%S'`
RUN_DIR=`pwd`/work/submit/$RUN_ID

# generate the input file
echo "This is sample input to KEG" > f.a

# output directory
mkdir -p outputs

# build the dax generator
export CLASSPATH=.:`pegasus-config --classpath`
javac BlackDiamondDAX.java

# generate the dax
java BlackDiamondDAX /usr blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/work"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/work"
  profiles:
    env:
      PEGASUS_HOME: "/usr"
      GLOBUS_LOCATION: "/ccg/software/globus/default"
EOF

# plan and submit the  workflow
pegasus-plan \
    -Dpegasus.code.generator=Shell \
    --conf pegasusrc \
    --sites local \
    --dir work/submit \
    --relative-submit-dir ${RUN_ID} \
    --output-site local \
    --cleanup leaf \
    --dax blackdiamond.dax \
    --submit | tee plan.out
