#!/bin/bash

set -e

export PYTHONPATH=`pegasus-config --python`

echo "Generating sleep workflow"
# writes the file "inner_sleep_workflow.yml" which is referenced in
# workflow.py 
python3 generate_inner_sleep_workflow.py

echo "Running workflow.py"
python3 workflow.py

