#!/bin/bash

set -e


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`


#A output directory
mkdir -p outputs

# build the dax generator
PYTHONPATH=$(pegasus-config --python) $testdir/dax-generator.py

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "sharedScratch"
    path: "$TOPDIR/local/shared-scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/local/shared-scratch"
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
EOF

# plan the  workflow
pegasus-plan \
    --conf pegasusrc \
    --sites condorpool \
    --dir submit \
    --cleanup none \
    dax.yml \
     | tee $TOPDIR/plan.out


WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

#check if planner did the right thing
set +e
grep +TransferOutput *sub | grep -v test.sh_ID0000001 1> /dev/null 2>&1
EC=$?
set -e

if [ $EC -eq 0 ]; then
    echo "+TransferOutput should be associated only with the compute job in the DAX test.sh_ID0000001"
    exit 1
fi

#now submit the workflow to run
pegasus-run  $WORK_DIR
