######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : hierarchical-workflow, Index = 0, Count = null
# SUBMIT FILE NAME : curl_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=06031cb1-d2e1-41d8-9e8b-45c9a77e3eb8 PEGASUS_WF_LABEL=hierarchical-workflow PEGASUS_DAG_JOB_ID=curl_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003//00/00/curl_ID0000001.err
executable = /home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003/00/00/curl_ID0000001.sh
initialdir = /home/mzalam/hierar/hierarichal-sample-wf/work/local-site/scratch/mzalam/pegasus/hierarchical-workflow/run0003
log = /home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003/hierarchical-workflow-0.log
notification = NEVER
output = /home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003//00/00/curl_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 10
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = /home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003/pegasus-worker-5.0.5-x86_64_rhel_8.tar.gz,/home/mzalam/hierar/hierarichal-sample-wf/submit/mzalam/pegasus/hierarchical-workflow/run0003/pegasus-lite-common.sh
transfer_output_files = pegasus.html
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "06031cb1-d2e1-41d8-9e8b-45c9a77e3eb8"
+pegasus_wf_uuid = "06031cb1-d2e1-41d8-9e8b-45c9a77e3eb8"
+pegasus_version = "5.0.5"
+pegasus_wf_name = "hierarchical-workflow-0"
+pegasus_wf_time = "20230304T115603-0800"
+pegasus_wf_xformation = "curl"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "curl_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
