#!/bin/bash

set -e
set -v

if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`

# generate the input file
echo "This is sample input to KEG" > f.a

# output directory
mkdir -p outputs

# build the dax generator
export PYTHONPATH=`pegasus-config --python`
$testdir/blackdiamond.py /usr > blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "CCG"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "sharedStorage"
    path: "/lizard/scratch-90-days/bamboo/outputs"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days/bamboo/outputs"
   -
    type: "sharedScratch"
    path: "/lizard/scratch-90-days"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days"
  profiles:
    condor:
      getenv: "True"
      requirements: "(TARGET.FileSystemDomain =!= \"\")"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "sharedStorage"
    path: "/lizard/scratch-90-days/bamboo/outputs"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days/bamboo/outputs"
   -
    type: "sharedScratch"
    path: "/lizard/scratch-90-days"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days"
  grids:
   -
    type: "condor"
    contact: "ccg-testing1.isi.edu"
    scheduler: "condor"
    jobtype: "compute"
   -
    type: "condor"
    contact: "ccg-testing1.isi.edu"
    scheduler: "condor"
    jobtype: "auxillary"
  profiles:
    condor:
      getenv: "True"
      requirements: "(TARGET.FileSystemDomain =!= \"\")"
    pegasus:
      style: "condor"
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites local \
    --output-sites local \
    --dir work \
    --cleanup leaf \
    --cluster horizontal \
    --dax blackdiamond.dax \
    -vvvv \
    --submit | tee plan.out

