#!/bin/bash

set -e

function remove_quotes {
    STR=$1
    echo ${STR:1:${#STR}-2}
}

LOG_FILE=build.log

type R >/dev/null 2>&1 || { echo >&2 "R is not available. Skipping R documentation."; exit 0; }

echo "Generating documentation..."
PKG_FILE=`ls $1/*.tar.gz`

R CMD check $PKG_FILE &> $LOG_FILE

if [ $? -ne 0 ]; then
    cat $LOG_FILE >&2
    exit 1
fi

LOG_DIR_STR=`cat $LOG_FILE | grep "log directory" | awk '{print $5}'`
LOG_DIR=$(remove_quotes $LOG_DIR_STR)

#DOC_FILE_STR=`cat $LOG_FILE | grep "this is package" | awk '{print $5}'`
#DOC_FILE=$(remove_quotes $DOC_FILE_STR)-manual.pdf
#mv $LOG_DIR/$DOC_FILE $2/

rm -rf $LOG_FILE
rm -rf $LOG_DIR

echo "R DAX API documentation successfully generated."
