#!/bin/bash

set -e

# this variable is expanded by the planner when
# parsing in the sites.xml file in the conf directory
TOPDIR=`pwd`
export TOPDIR

# pegasus bin directory is needed to find keg
BIN_DIR=`pegasus-config --bin`
PEGASUS_LOCAL_BIN_DIR=$BIN_DIR
export PEGASUS_LOCAL_BIN_DIR

# determine TEST_NAME to setup site catalog
if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
fi
TESTDIR=$(cd $testdir && pwd)
TEST_NAME=`basename $TESTDIR`
export TEST_NAME



# generate the input file
input_dir=/lizard/scratch-90-days/${TEST_NAME}
mkdir -p input_dir
fa="file:///${input_dir}/f.a"
echo "This is sample input to KEG" >$fa
shacmd=`sha256sum $fa`

sha=`echo $shacmd | sed -E 's/([a-z0-9]*).*/\1/'`
cat >./conf/rc.data<<EOF
$fa site="condorpool" checksum.type="sha256" checksum.value="$sha"

EOF

# generate the input file
echo "This is sample input to KEG" >f.a
shacmd=`sha256sum f.a`

sha=`echo $shacmd | sed -E 's/([a-z0-9]*).*/\1/'`
cat >./conf/rc.data<<EOF
f.a file://$TOPDIR/f.a site="condorpool" checksum.type="sha256" checksum.value="$sha"

EOF


# generate the dax
export PYTHONPATH=`pegasus-config --python`
./blackdiamond.py $BIN_DIR > blackdiamond.dax

# plan and submit the  workflow
pegasus-plan \
    --conf ./pegasusrc \
    --sites condorpool \
    --staging-site condorpool \
    --output-site local \
    --dir dags \
    --dax blackdiamond.dax \
    --force \
    -v \
     | tee $TOPDIR/plan.out


WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

# check if planner did the right things
#  find . -name "*sh" -exec grep  -A 1 pegasus-integrity {} \; | grep f.a
for SH in `find $WORK_DIR -name \*.sh`; do
    if grep -A 1 pegasus-integrity $SH | grep f.a >/dev/null 2>&1; then
	echo "Error: $SH has file f.a that is integrity checked"
        exit 1
    fi
done

# now we are good to submit
echo "Submitting the workflow for execution"

# now submit the workflow for execution
pegasus-run $WORK_DIR

