'\" t
.\"     Title: pegasus-statistics
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/01/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-STATISTICS" "1" "06/01/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-statistics \- A tool to generate statistics about the workflow run\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-statistics\fR [\fB\-h\fR|\fB\-\-help\fR]
                   [\fB\-o\fR|\fB\-\-output\fR \fIdir\fR]
                   [\fB\-c\fR|\fB\-\-conf\fR \fIpropfile\fR]
                   [\fB\-p\fR|\fB\-\-statistics\-level\fR \fIlevel\fR]
                   [\fB\-t\fR|\fB\-\-time\-filter\fR \fIfilter\fR]
                   [\fB\-i\fR|\fB\-\-ignore\-db\-inconsistency\fR]
                   [\fB\-v\fR|\fB\-\-verbose\fR]
                   [\fB\-q\fR|\fB\-\-quiet\fR]
                   [\fIsubmitdir\fR]
.fi
.SH "DESCRIPTION"
.sp
pegasus\-statistics generates statistics about the workflow run like total jobs/tasks/sub workflows ran , how many succeeded/failed etc\&. It generates job instance statistics like run time, condor queue delay etc\&. It generates invocation statistics information grouped by transformation name\&. It also generates job instance and invocation statistics information grouped by time and host\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a usage summary with all the available command\-line options\&.
.RE
.PP
\fB\-o\fR \fIdir\fR, \fB\-\-output\fR \fIdir\fR
.RS 4
Writes the output to the given directory\&.
.RE
.PP
\fB\-c\fR \fIpropfile\fR, \fB\-\-conf\fR \fIpropfile\fR
.RS 4
The properties file to use\&. This option overrides all other property files\&.
.RE
.PP
\fB\-s\fR \fIlevel\fR, \fB\-\-statistics\-level\fR \fIlevel\fR
.RS 4
Specifies the statistics information to generate\&. Valid levels are:
\fBall\fR,
\fBsummary\fR,
\fBwf_stats\fR,
\fBjb_stats\fR,
\fBtf_stats\fR, and
\fBti_stats\fR\&. Default is
\fBsummary\fR\&. The output generated by pegasus\-statistics is based on the the
\fIlevel\fR
set:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBall\fR: generates all the statistics information\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBsummary\fR: generates the workflow statistics summary\&. In the case of a hierarchical workflow the summary is across all sub workflows\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBwf_stats\fR: generates the workflow statistics information of each individual workflow\&. In case of a hierarchical workflow the workflow statistics are created for each sub workflow\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBjb_stats\fR: generates the job statistics information of each individual workflow\&. In case of hierarchical workflow the job statistics is created for each sub workflows\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBtf_stats\fR: generates the invocation statistics information of each individual workflow grouped by transformation name \&.In case of hierarchical workflow the transformation statistics is created for each sub workflows\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBti_stats\fR: generates the job instance and invocation statistics like total count and runtime grouped by time and host\&.
.RE
.RE
.PP
\fB\-t\fR \fIfilter\fR, \fB\-\-time\-filter\fR \fIfilter\fR
.RS 4
Specifies the time filter to group the time statistics\&. Valid
\fIfilter\fR
values are:
\fBmonth\fR,
\fBweek\fR,
\fBday\fR,
\fBhour\fR\&. Default is
\fBday\fR\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-db\-inconsistency\fR
.RS 4
Turn off the the check for database consistency\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increases the log level\&. If omitted, the default level will be set to WARNING\&. When this option is given, the log level is changed to INFO\&. If this option is repeated, the log level will be changed to DEBUG\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Decreases the log level\&. If omitted, the default level will be set to WARNING\&. When this option is given, the log level is changed to ERROR\&.
.RE
.SH "EXAMPLE"
.sp
Runs pegasus\-statistics and writes the output to the given directory:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-statistics  \-o /scratch/statistics /scratch/grid\-setup/run0001
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
Prasanth Thomas
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
