'\" t
.\"     Title: pegasus-version
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/01/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-VERSION" "1" "06/01/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-version \- print or match the version of the toolkit\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-version\fR [\fB\-D\fR\fIproperty=value\fR] [\fB\-m\fR [\fB\-q\fR]] [\fB\-V\fR] [\fB\-f\fR] [\fB\-l\fR]
.fi
.SH "DESCRIPTION"
.sp
This program prints the version string of the currently active Pegasus toolkit on \fIstdout\fR\&.
.sp
pegasus\-version is a simple command\-line tool that reports the version number of the Pegasus distribution being used\&. In its most basic invocation, it will show the current version of the Pegasus software you have installed:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-version
3\&.1\&.0cvs
.fi
.if n \{\
.RE
.\}
.sp
If you want to know more details about the installed version, i\&.e\&. which system it was compiled for and when, use the long or full mode:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-version \-f
3\&.1\&.0cvs\-x86_64_cent_5\&.6\-20110706191019Z
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\fB\-D\fR\fIproperty=value\fR
.RS 4
The
\fB\-D\fR
option allows an experienced user to override certain properties which influence the program execution, among them the default location of the user\(cqs properties file and the
\fBPEGASUS_HOME\fR
location\&. One may set several CLI properties by giving this option multiple times\&.
.sp
The
\fB\-D\fR
option(s) must be the first option on the command line\&. CLI properties take precedence over the file\-based properties of the same key\&.
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
The
\fB\-\-full\fR
mode displays internal build metrics, like OS type and libc version, addition to the version number\&. It appends the build time as time stamp to the version\&. The time stamp uses ISO 8601 format, and is a UTC stamp\&.
.RE
.PP
\fB\-l\fR, \fB\-\-long\fR
.RS 4
This option is an alias for
\fB\-\-full\fR\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Displays the version of the Pegasus planner you are using\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
is ignored in this tool\&. However, to provide a uniform interface for all tools, the option is recognized and will not trigger an error\&.
.RE
.SH "RETURN VALUE"
.sp
The program will usually return with success (0)\&. In match mode, if the internal version does not match the external installation, an exit code of 1 is returned\&. If run\-time errors are detected, an exit code of 2 is returned, 3 for fatal errors\&.
.SH "ENVIRONMENT VARIABLES"
.PP
\fBJAVA_HOME\fR
.RS 4
should be set and point to a valid location to start the intended Java virtual machine as
\fI$JAVA_HOME/bin/java\fR\&.
.RE
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-version
3\&.1\&.0cvs

$ pegasus\-version \-f
3\&.1\&.0cvs\-x86_64_cent_5\&.6\-20110706191019Z
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
Jens\-S\&. Vöckler <voeckler at isi dot edu>
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
