'\" t
.\"     Title: pegasus-dashboard
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/25/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-DASHBOARD" "1" "11/25/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-dashboard \- Starts the Pegasus monitoring dashboard\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-dashboard\fR [\fB\-\-help\fR|\fB\-h\fR] [\fB\-\-host\fR|\fB\-n\fR] [\fB\-\-port\fR|\fB\-p\fR]
                 [\fB\-\-masterdburl\fR|\fB\-m\fR \fIdatabase url\fR]
.fi
.SH "DESCRIPTION"
.sp
\fBpegasus\-dashboard\fR is a command\-line utility to start the \fBPegasus\fR monitoring dashboard\&. The dashboard allows users to monitor status of workflows using a browser\&. The workflow status information is retrieved from a STAMPEDE database\&. The STAMPEDE database is populated in a \fBSQLite\fR, or \fBMySQL\fR database as per your configuration, when a workflow is planned or run
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a usage summary with all the available command\-line options\&.
.RE
.PP
\fB\-n\fR, \fB\-\-host\fR
.RS 4
Only print the the output and error filenames instead of their contents\&.
.RE
.PP
\fB\-p\fR, \fB\-\-port\fR
.RS 4
Get jobs\*(Aq output and error filenames from the job\(cqs submit file\&.
.RE
.PP
\fB\-m\fR, \fB\-\-masterdburl\fR
.RS 4
The Pegasus dashboard uses a user specific master database, to identify which workflows have been run\&. By default this database is created in the \&.pegasus directory in the user\(cqs home directory, when a workflow is planned\&. The \-m option allows the user to specify a custom database\&.
.RE
.sp
Note: The dashboard can only track workflows, which are listed in the master database\&.
.SH "ENVIRONMENT VARIABLES"
.sp
\fBpegasus\-dashboard\fR does not require that any environmental variables be set\&. It locates its required Python modules based on its own location, and therefore should not be moved outside of Pegasus\*(Aq bin directory\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-dashboard
$ pegasus\-dashboard \-n 127\&.0\&.0\&.1 \-p 8080
$ pegasus\-dashboard \-n localhost \-p 80
$ pegasus\-dashboard \-m sqlite:///lfs/scratch//workflow\&.db
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
pegasus\-status(1), pegasus\-statistics(1)\&.
.SH "AUTHORS"
.sp
Rajiv Mayani <mayani at isi dot edu>
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
