'\" t
.\"     Title: pegasus-plots
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/28/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-PLOTS" "1" "02/28/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-plots \- A tool to generate graphs and charts to visualize workflow run\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-plots\fR [\fB\-h\fR|\fB\-\-help\fR]
              [\fB\-o\fR|\fB\-\-output\fR \fIoutdir\fR]
              [\fB\-c\fR|\fB\-\-conf\fR \fIpropfile\fR]
              [\fB\-m\fR|\fB\-\-max\-graph\-nodes\fR \fImax\fR]
              [\fB\-p\fR|\fB\-\-plotting\-level\fR \fIlevel\fR]
              [\fB\-i\fR|\fB\-\-ignore\-db\-inconsistency\fR]
              [\fB\-v\fR|\fB\-\-verbose\fR]
              [\fB\-q\fR|\fB\-\-quiet\fR]
              [\fIsubmitdir\fR]
.fi
.SH "DESCRIPTION"
.sp
pegasus\-plots generates graphs and charts to visualize workflow run\&. It generates workflow execution Gantt chart, job over time chart, time chart, dax and dag graph\&. It uses executable \*(Aqdot\e\*(Aq to generate graphs\&. pegasus\-plots looks for the executable in your path and generates graphs based on it\(cqs availability \&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a usage summary with all the available command\-line options\&.
.RE
.PP
\fB\-o\fR \fIoutdir\fR, \fB\-\-output\fR \fIoutdir\fR
.RS 4
Writes the output to the given directory
.RE
.PP
\fB\-c\fR \fIpropfile\fR, \fB\-\-conf\fR \fIpropfile\fR
.RS 4
The properties file to use\&. This option overrides all other property files\&.
.RE
.PP
\fB\-m\fR \fImax\fR, \fB\-\-max\-graph\-nodes\fR \fImax\fR
.RS 4
Maximum limit on the number of tasks/jobs in the dax/dag up to which the graph should be generated\&. The default value is 100\&.
.RE
.PP
\fB\-p\fR \fIlevel\fR, \fB\-\-plotting\-level\fR \fIlevel\fR
.RS 4
Specifies the charts and graphs to generate\&. Valid levels are:
\fBall\fR,
\fBall_charts\fR,
\fBall_graphs\fR,
\fBdax_graph\fR,
\fBdag_graph\fR,
\fBgantt_chart\fR,
\fBhost_chart\fR,
\fBtime_chart\fR,
\fBbreakdown_chart\fR\&. Default is
\fBall_charts\fR\&. The output generated by
\fBpegasus\-plots\fR
is based on the
\fIlevel\fR
set:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBall\fR: generates all charts and graphs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBall_charts\fR: generates all charts\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBall_graphs\fR: generates all graphs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBdax_graph\fR: generates dax graph\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBdag_graph\fR: generates dag graph\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBgantt_chart\fR: generates the workflow execution Gantt chart\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBhost_chart\fR: generates the host over time chart\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBtime_chart\fR: generates the time chart which shows the job instance/invocation count and runtime over time\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBbreakdown_chart\fR: generates the breakdown chart which shows the invocation count and runtime grouped by transformation name\&.
.RE
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-db\-inconsistency\fR
.RS 4
Turn off the the check for database consistency\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increases the log level\&. If omitted, the default level will be set to WARNING\&. When this option is given, the log level is changed to INFO\&. If this option is repeated, the log level will be changed to DEBUG\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Decreases the log level\&. If omitted, the default level will be set to WARNING\&. When this option is given, the log level is changed to ERROR\&.
.RE
.SH "EXAMPLE"
.sp
Runs pegasus\-plots and writes the output to the given directory:
.sp
.if n \{\
.RS 4
.\}
.nf
pegasus\-plots  \-o /scratch/plot /scratch/grid\-setup/run0001
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
Prasanth Thomas
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
