'\" t
.\"     Title: pegasus-analyzer
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/27/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-ANALYZER" "1" "02/27/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-analyzer \- debugs a workflow\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-analyzer\fR [\fB\-\-help\fR|\fB\-h\fR] [\fB\-\-quiet\fR|\fB\-q\fR] [\fB\-\-strict\fR|\fB\-s\fR]
                 [\fB\-\-monitord\fR|\fB\-m\fR|\fB\-t\fR] [\fB\-\-verbose\fR|\fB\-v\fR]
                 [\fB\-\-output\-dir\fR|\fB\-o\fR \fIoutput_dir\fR]
                 [\fB\-\-dag\fR \fIdag_filename\fR] [\fB\-\-dir\fR|\fB\-d\fR|\fB\-i\fR \fIinput_dir\fR]
                 [\fB\-\-print\fR|\fB\-p\fR \fIprint_options\fR] [\fB\-\-debug\-job\fR \fIjob\fR]
                 [\fB\-\-debug\-dir\fR \fIdebug_dir\fR] [\fB\-\-type\fR \fIworkflow_type\fR]
                 [\fB\-\-conf\fR|\fB\-c\fR \fIproperty_file\fR] [\fB\-\-files\fR]
                 [\fB\-\-top\-dir\fR \fIdir_name\fR] [\fIworkflow_directory\fR]
.fi
.SH "DESCRIPTION"
.sp
\fBpegasus\-analyzer\fR is a command\-line utility for parsing the \fIjobstate\&.log\fR file and reporting successful and failed jobs\&. When executed without any options, it will query the \fBSQLite\fR or \fBMySQL\fR database and retrieve failed job information for the particular workflow\&. When invoked with the \fB\-\-files\fR option, it will retrieve information from several log files, isolating jobs that did not complete successfully, and printing their \fIstdout\fR and \fIstderr\fR so that users can get detailed information about their workflow runs\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a usage summary with all the available command\-line options\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Only print the the output and error filenames instead of their contents\&.
.RE
.PP
\fB\-s\fR, \fB\-\-strict\fR
.RS 4
Get jobs\*(Aq output and error filenames from the job\(cqs submit file\&.
.RE
.PP
\fB\-m\fR, \fB\-t\fR, \fB\-\-monitord\fR
.RS 4
Invoke
\fBpegasus\-monitord\fR
before analyzing the
\fIjobstate\&.log\fR
file\&. Although
\fBpegasus\-analyzer\fR
can be executed during the workflow execution as well as after the workflow has already completed execution,
\fBpegasus\-monitord"\fR
is always invoked with the
\fB\-\-replay\fR
option\&. Since multiple instances of
\fBpegasus\-monitord"\fR
should not be executed simultaneously in the same workflow directory, the user should ensure that no other instances of
\fBpegasus\-monitord\fR
are running\&. If the
\fIrun_directory\fR
is writable,
\fBpegasus\-analyzer\fR
will create a
\fIjobstate\&.log\fR
file there, rotating an older log, if it is found\&. If the
\fIrun_directory\fR
is not writable (e\&.g\&. when the user debugging the workflow is not the same user that ran the workflow),
\fBpegasus\-analyzer\fR
will exit and ask the user to provide the
\fB\-\-output\-dir\fR
option, in order to provide an alternative location for
\fBpegasus\-monitord\fR
log files\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Sets the log level for
\fBpegasus\-analyzer\fR\&. If omitted, the default
\fIlevel\fR
will be set to
\fIWARNING\fR\&. When this option is given, the log level is changed to
\fIINFO\fR\&. If this option is repeated, the log level will be changed to
\fIDEBUG\fR\&.
.RE
.PP
\fB\-o\fR \fIoutput_dir\fR, \fB\-\-output\-dir\fR \fIoutput_dir\fR
.RS 4
This option provides an alternative location for all monitoring log files for a particular workflow\&. It is mainly used when an user does not have write privileges to a workflow directory and needs to generate the log files needed by
\fBpegasus\-analyzer\fR\&. If this option is used in conjunction with the
\fB\-\-monitord\fR
option, it will invoke
\fBpegasus\-monitord\fR
using
\fIoutput_dir\fR
to store all output files\&. Because workflows can have sub\-workflows,
\fBpegasus\-monitord\fR
will create its files prepending the workflow
\fIwf_uuid\fR
to each filename\&. This way, multiple workflow files can be stored in the same directory\&.
\fBpegasus\-analyzer\fR
has built\-in logic to find the specific
\fIjobstate\&.log\fR
file by looking at the workflow
\fIbraindump\&.txt\fR
file first and figuring out the corresponding
\fIwf_uuid\&.\fR
If
\fIoutput_dir\fR
does not exist, it will be created\&.
.RE
.PP
\fB\-\-dag\fR \*(Aqdag_filename
.RS 4
In this option,
\fIdag_filename\fR
specifies the path to the
\fIDAG\fR
file to use\&.
\fBpegasus\-analyzer\fR
will get the directory information from the
\fIdag_filename\fR\&. This option overrides the
\fB\-\-dir\fR
option below\&.
.RE
.PP
\fB\-d\fR \fIinput_dir\fR, \fB\-i\fR \fIinput_dir\fR, \fB\-\-dir\fR \fIinput_dir\fR
.RS 4
Makes
\fBpegasus\-analyzer\fR
look for the
\fIjobstate\&.log\fR
file in the
\fIinput_dir\fR
directory\&. If this option is omitted,
\fBpegasus\-analyzer\fR
will look in the current directory\&.
.RE
.PP
\fB\-p\fR \fIprint_options\fR, \fB\-\-print\fR \fIprint_options\fR
.RS 4
Tells
\fBpegasus\-analyzer\fR
what extra information it should print for failed jobs\&.
\fIprint_options\fR
is a comma\-delimited list of options, that include
\fIpre\fR,
\fIinvocation\fR, and/or
\fIall\fR, which activates all printing options\&. With the
\fIpre\fR
option,
\fBpegasus\-analyzer\fR
will print the
\fIpre\-script\fR
information for failed jobs\&. For the
\fIinvocation\fR
option,
\fBpegasus\-analyzer\fR
will print the
\fIinvocation\fR
command, so users can manually run the failed job\&.
.RE
.PP
\fB\-\-debug\-job\fR \fIjob\fR
.RS 4
When given this option,
\fBpegasus\-analyzer\fR
turns on its
\fIdebug_mode\fR, when it can be used to debug a particular job\&. In this mode,
\fBpegasus\-analyzer\fR
will create a shell script in the
\fIdebug_dir\fR
(see below, for specifying it) and copy all necessary files to this local directory and then execute the job locally\&.
.RE
.PP
\fB\-\-debug\-dir\fR \fIdebug_dir\fR
.RS 4
When in
\fIdebug_mode\fR,
\fBpegasus\-analyzer\fR
will create a temporary debug directory\&. Users can give this option in order to specify a particular
\fIdebug_dir\fR
directory to be used instead\&.
.RE
.PP
\fB\-\-type\fR \fIworkflow_type\fR
.RS 4
In this options, users specify what
\fIworkflow_type\fR
they want to debug\&. At this moment, the only
\fIworkflow_type\fR
available is
\fBcondor\fR
and it is the default value if this option is not specified\&.
.RE
.PP
\fB\-c\fR \fIproperty_file\fR, \fB\-\-conf\fR \fIproperty_file\fR
.RS 4
This option is used to specify an alternative property file, which may contain the path to the database to be used by
\fBpegasus\-analyzer\fR\&. If this option is not specified, the config file specified in the
\fBbraindump\&.txt\fR
file will take precedence\&.
.RE
.PP
\fB\-\-files\fR
.RS 4
This option allows users to run
\fBpegasus\-analyzer\fR
using the files in the workflow directory instead of the database as the source of information\&.
\fBpegasus\-analyzer\fR
will output the same information, this option only changes where the data comes from\&.
.RE
.PP
\fB\-\-top\-dir\fR \fIdir_name\fR
.RS 4
This option enables
\fBpegasus\-analyzer\fR
to show information about sub\-workflows when using the database mode\&. When debugging a top\-level workflow with failures in sub\-workflows, the analyzer will automatically print the command users should use to debug a failed sub\-workflow\&. This allows the analyzer to find the database it needs to access\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
\fBpegasus\-analyzer\fR does not require that any environmental variables be set\&. It locates its required Python modules based on its own location, and therefore should not be moved outside of Pegasus\*(Aq bin directory\&.
.SH "EXAMPLE"
.sp
The simplest way to use \fBpegasus\-analyzer\fR is to go to the \fIrun_directory\fR and invoke the analyzer:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-analyzer \&.
.fi
.if n \{\
.RE
.\}
.sp
which will cause \fBpegasus\-analyzer\fR to print information about the workflow in the current directory\&.
.sp
\fBpegasus\-analyzer\fR output contains a summary, followed by detailed information about each job that either failed, or is in an unknown state\&. Here is the summary section of the output:
.sp
.if n \{\
.RS 4
.\}
.nf
**************************Summary***************************

 Total jobs         :     75 (100\&.00%)
 # jobs succeeded   :     41 (54\&.67%)
 # jobs failed      :      0 (0\&.00%)
 # jobs unsubmitted :     33 (44\&.00%)
 # jobs unknown     :      1 (1\&.33%)
.fi
.if n \{\
.RE
.\}
.sp
\fIjobs_succeeded\fR are jobs that have completed successfully\&. \fIjobs_failed\fR are jobs that have finished, but that did not complete successfully\&. \fIjobs_unsubmitted\fR are jobs that are listed in the \fIdag_file\fR, but no information about them was found in the \fIjobstate\&.log\fR file\&. Finally, \fIjobs_unknown\fR are jobs that have started, but have not reached completion\&.
.sp
After the summary section, \fBpegasus\-analyzer\fR will display information about each job in the \fIjob_failed\fR and \fIjob_unknown\fR categories\&.
.sp
.if n \{\
.RS 4
.\}
.nf
******************Failed jobs\*(Aq details**********************

=======================findrange_j3=========================

  last state: POST_SCRIPT_FAILURE
        site: local
 submit file: /home/user/diamond\-submit/findrange_j3\&.sub
 output file: /home/user/diamond\-submit/findrange_j3\&.out\&.000
  error file: /home/user/diamond\-submit/findrange_j3\&.err\&.000

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-Task #1 \- Summary\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

 site        : local
 hostname    : server\-machine\&.domain\&.com
 executable  : (null)
 arguments   : \-a findrange \-T 60 \-i f\&.b2 \-o f\&.c2
 error       : 2
 working dir :
.fi
.if n \{\
.RE
.\}
.sp
In the example above, the \fIfindrange_j3\fR job has failed, and the analyzer displays information about the job, showing that the job finished with a \fIPOST_SCRIPT_FAILURE\fR, and lists the \fIsubmit\fR, \fIoutput\fR and \fIerror\fR files for this job\&. Whenever \fBpegasus\-analyzer\fR detects that the output file contains a kickstart record, it will display the breakdown containing each task in the job (in this case we only have one task)\&. Because \fBpegasus\-analyzer\fR was not invoked with the \fB\-\-quiet\fR flag, it will also display the contents of the \fIoutput\fR and \fIerror\fR files (or the stdout and stderr sections of the kickstart record), which in this case are both empty\&.
.sp
In the case of \fISUBDAG\fR and \fIsubdax\fR jobs, \fBpegasus\-analyzer\fR will indicate it, and show the command needed for the user to debug that sub\-workflow\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
=================subdax_black_ID000009=====================

  last state: JOB_FAILURE
        site: local
 submit file: /home/user/run1/subdax_black_ID000009\&.sub
 output file: /home/user/run1/subdax_black_ID000009\&.out
  error file: /home/user/run1/subdax_black_ID000009\&.err
  This job contains sub workflows!
  Please run the command below for more information:
  pegasus\-analyzer \-d /home/user/run1/blackdiamond_ID000009\&.000

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-subdax_black_ID000009\&.out\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Executing condor dagman \&.\&.\&.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-subdax_black_ID000009\&.err\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
.fi
.if n \{\
.RE
.\}
.sp
tells the user the \fIsubdax_black_ID000009\fR sub\-workflow failed, and that it can be debugged by using the indicated \fBpegasus\-analyzer\fR command\&.
.SH "SEE ALSO"
.sp
pegasus\-status(1), pegasus\-monitord(1), pegasus\-statistics(1)\&.
.SH "AUTHORS"
.sp
Fabio Silva <fabio at isi dot edu>
.sp
Karan Vahi <vahi at isi dot edu>
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
