'\" t
.\"     Title: pegasus-tc-client
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/01/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-TC\-CLIENT" "1" "06/01/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-tc-client \- A full featured generic client to handle adds, deletes and queries to the Transformation Catalog (TC)\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-tc\-client\fR [\fB\-D\fR\fIproperty=value\fR\&...] [\fI\-h\fR] [\fI\-v\fR] [\fI\-V\fR]
                  \fIOPERATION\fR \fITRIGGERS\fR [\fIOPTIONS\fR]
.fi
.SH "DESCRIPTION"
.sp
The \fBpegasus\-tc\-client\fR command is a generic client that performs the three basic operation of adding, deleting and querying of any Transformation Catalog implemented to the TC API\&. The client implements all the operations supported by the TC API\&. It is up to the TC implementation whether they support all operations or modes\&.
.sp
The following 3 operations are supported by the \fBpegasus\-tc\-client\fR\&. One of these operations have to be specified to run the client\&.
.PP
\fBADD\fR
.RS 4
This operation allows the client to add or update entries in the Transformation Catalog\&. Entries can be added one by one on the command line or in bulk by using the
\fIBULK\fR
Trigger and providing a file with the necessary entries\&. Also Profiles can be added to either the logical transformation or the physical transformation\&.
.RE
.PP
\fBDELETE\fR
.RS 4
This operation allows the client to delete entries from the Transformation Catalog\&. Entries can be deleted based on logical transformation, by resource, by transformation type as well as the transformation system information\&. Also Profiles associated with the logical or physical transformation can be deleted\&.
.RE
.PP
\fBQUERY\fR
.RS 4
This operation allows the client to query for entries from the Transformation Catalog\&. Queries can be made for printing all the contents of the Catalog or for specific entries, for all the logical transformations or resources etc\&.
.RE
.sp
See the \fBTRIGGERS\fR and \fBVALID COMBINATIONS\fR section for more details\&.
.SH "OPERATIONS"
.sp
To select one of the 3 operations\&.
.PP
\fB\-a, \-\-add\fR
.RS 4
Perform addition operations on the TC\&.
.RE
.PP
\fB\-d, \-\-delete\fR
.RS 4
Perform delete operations on the TC\&.
.RE
.PP
\fB\-q, \-\-query\fR
.RS 4
Perform query operations on the TC\&.
.RE
.SH "TRIGGERS"
.sp
Triggers modify the behavior of an \fBOPERATION\fR\&. For example, if you want to perform a bulk operation you would use a \fIBULK\fR Trigger or if you want to perform an operation on a Logical Transformation then you would use the \fILFN\fR Trigger\&.
.sp
The following 7 Triggers are available\&. See the \fBVALID COMBINATIONS\fR section for the correct grouping and usage\&.
.PP
\fB\-B\fR
.RS 4
Triggers a bulk operation\&.
.RE
.PP
\fB\-L\fR
.RS 4
Triggers an operation on a logical transformation\&.
.RE
.PP
\fB\-P\fR
.RS 4
Triggers an operation on a physical transformation
.RE
.PP
\fB\-R\fR
.RS 4
Triggers an operation on a resource\&.
.RE
.PP
\fB\-E\fR
.RS 4
Triggers an operation on a Profile\&.
.RE
.PP
\fB\-T\fR
.RS 4
Triggers an operation on a Type\&.
.RE
.PP
\fB\-S\fR
.RS 4
Triggers an operation on a System information\&.
.RE
.SH "OPTIONS"
.sp
The following options are applicable for all the operations\&.
.PP
\fB\-D\fR\fIproperty=value\fR
.RS 4
The \-D options allows an experienced user to override certain properties which influence the program execution, among them the default location of the user\(cqs properties file and the PEGASUS home location\&. One may set several CLI properties by giving this option multiple times\&. The
\fB\-D\fR
option(s) must be the first option on the command line\&. A CLI property take precedence over the properties file property of the same key\&.
.RE
.PP
\fB\-l, \-\-lfn\fR \fIlogical\fR
.RS 4
The logical transformation to be added\&. The format is:
\fBNAMESPACE::NAME:VERSION\fR\&. The name is always required, namespace and version are optional\&.
.RE
.PP
\fB\-p, \-\-pfn\fR \fIphysical\fR
.RS 4
The physical transformation to be added\&. For INSTALLED executables its a local file path, for all others its a url\&.
.RE
.PP
\fB\-t, \-\-type\fR \fItype\fR
.RS 4
The type of physical transformation\&. Valid values are: INSTALLED, STATIC_BINARY, DYNAMIC_BINARY, SCRIPT, SOURCE, PACMAN_PACKAGE\&.
.RE
.PP
\fB\-r, \-\-resource\fR \fIresource\fR
.RS 4
The resourceID where the transformation is located\&.
.RE
.PP
\fB\-e, \-\-profile\fR \fIprofiles\fR
.RS 4
The profiles for the transformation\&. Multiple profiles of same namespace can be added simultaneously by separating them with a comma
\fB","\fR\&. Each profile section is written as
\fBNAMESPACE::KEY=VALUE,KEY2=VALUE2\fR
e\&.g\&.
ENV::JAVA_HOME=/usr/bin/java2,PEGASUS_HOME=/usr/local/pegasus\&. To add multiple namespaces you need to repeat the \-e option for each namespace\&. e\&.g\&.
\-e ENV::JAVA_HOME=/usr/bin/java \-e GLOBUS::JobType=MPI,COUNT=10
.RE
.PP
\fB\-s, \-\-system\fR \fIsysteminfo\fR
.RS 4
The architecture, os, osversion and glibc if any for the executable\&. Each system info is written in the form
\fBARCH::OS:OSVER:GLIBC\fR
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Displays the output in verbose mode (Lots of Debugging info)\&.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Displays the Pegasus version\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Generates help
.RE
.SH "OTHER OPTIONS"
.PP
\fB\-o, \-\-oldformat\fR
.RS 4
Generates the output in the old single line format
.RE
.PP
\fB\-c, \-\-conf\fR
.RS 4
path to property file
.RE
.SH "VALID COMBINATIONS"
.sp
The following are valid combinations of \fBOPERATIONS, TRIGGERS, OPTIONS\fR for the \fBpegasus\-tc\-client\fR\&.
.SS "ADD"
.PP
\fBAdd TC Entry\fR
.RS 4
\-a \-l
\fIlfn\fR
\-p
\fIpfn\fR
\-t
\fItype\fR
\-r
\fIresource\fR
\-s
\fIsystem\fR
[\-e
\fIprofiles\fR\&...]
.sp
Adds a single entry into the transformation catalog\&.
.RE
.PP
\fBAdd PFN Profile\fR
.RS 4
\-a \-P \-E \-p
\fIpfn\fR
\-t
\fItype\fR
\-r
\fIresource\fR
\-e
\fIprofiles\fR
\&...
.sp
Adds profiles to a specified physical transformation on a given resource and of a given type\&.
.RE
.PP
\fBAdd LFN Profile\fR
.RS 4
\-a \-L \-E \-l
\fIlfn\fR
\-e
\fIprofiles\fR
\&...
.sp
Adds profiles to a specified logical transformation\&.
.RE
.PP
\fBAdd Bulk Entries\fR
.RS 4
\-a \-B \-f
\fIfile\fR
.sp
Adds entries in bulk mode by supplying a file containing the entries\&. The format of the file contains 6 columns\&. E\&.g\&.
.sp
.if n \{\
.RS 4
.\}
.nf
#RESOURCE   LFN         PFN      TYPE      SYSINFO      PROFILES
#
isi NS::NAME:VER  /bin/date  INSTALLED  ARCH::OS:OSVERS:GLIBC  NS::KEY=VALUE,KEY=VALUE;NS2::KEY=VALUE,KEY=VALUE
.fi
.if n \{\
.RE
.\}
.RE
.SS "DELETE"
.PP
\fBDelete all TC\fR
.RS 4
\-d \-BPRELST
.sp
Deletes the entire contents of the TC\&.
.sp
\fBWARNING : USE WITH CAUTION\&.\fR
.RE
.PP
\fBDelete by LFN\fR
.RS 4
\-d \-L \-l
\fIlfn\fR
[\-r
\fIresource\fR] [\-t
\fItype\fR]
.sp
Deletes entries from the TC for a particular logical transformation and additionally a resource and or type\&.
.RE
.PP
\fBDelete by PFN\fR
.RS 4
\-d \-P \-l
\fIlfn\fR
\-p
\fIpfn\fR
[\-r
\fIresource\fR] [\-t
\fItype\fR]
.sp
Deletes entries from the TC for a given logical and physical transformation and additionally on a particular resource and or of a particular type\&.
.RE
.PP
\fBDelete by Type\fR
.RS 4
\-d \-T \-t
\fItype\fR
[\-r
\fIresource\fR]
.sp
Deletes entries from TC of a specific type and/or on a specific resource\&.
.RE
.PP
\fBDelete by Resource\fR
.RS 4
\-d \-R \-r
\fIresource\fR
.sp
Deletes the entries from the TC on a particular resource\&.
.RE
.PP
\fBDelete by SysInfo\fR
.RS 4
\-d \-S \-s
\fIsysinfo\fR
.sp
Deletes the entries from the TC for a particular system information type\&.
.RE
.PP
\fBDelete Pfn Profile\fR
.RS 4
\-d \-P \-E \-p
\fIpfn\fR
\-r
\fIresource\fR
\-t
\fItype\fR
[\-e
\fIprofiles\fR
\&.\&.]
.sp
Deletes all or specific profiles associated with a physical transformation\&.
.RE
.PP
\fBDelete Lfn Profile\fR
.RS 4
\-d \-L \-E \-l
\fIlfn\fR
\-e
\fIprofiles\fR
\&...\&.
.sp
Deletes all or specific profiles associated with a logical transformation\&.
.RE
.SS "QUERY"
.PP
\fBQuery Bulk\fR
.RS 4
\-q \-B
.sp
Queries for all the contents of the TC\&. It produces a file format TC which can be added to another TC using the bulk option\&.
.RE
.PP
\fBQuery LFN\fR
.RS 4
\-q \-L [\-r
\fIresource\fR] [\-t
\fItype\fR]
.sp
Queries the TC for logical transformation and/or on a particular resource and/or of a particular type\&.
.RE
.PP
\fBQuery PFN\fR
.RS 4
\-q \-P \-l
\fIlfn\fR
[\-r
\fIresource\fR] [\-t
\fItype\fR]
.sp
Queries the TC for physical transformations for a give logical transformation and/or on a particular resource and/or of a particular type\&.
.RE
.PP
\fBQuery Resource\fR
.RS 4
\-q \-R \-l
\fIlfn\fR
[\-t
\fItype\fR]
.sp
Queries the TC for resources that are registered and/or resources registered for a specific type of transformation\&.
.RE
.PP
\fBQuery LFN Profile\fR
.RS 4
\-q \-L \-E \-l
\fIlfn\fR
.sp
Queries for profiles associated with a particular logical transformation
.RE
.PP
\fBQuery Pfn Profile\fR
.RS 4
\-q \-P \-E \-p
\fIpfn\fR
\-r
\fIresource\fR
\-t
\fItype\fR
.sp
Queries for profiles associated with a particular physical transformation
.RE
.SH "PROPERTIES"
.sp
These are the properties you will need to set to use either the \fBFile\fR or \fBDatabase\fR TC\&.
.sp
For more details please check the \fB$PEGASUS_HOME/etc/sample\&.properties\fR file\&.
.PP
\fBpegasus\&.catalog\&.transformation\fR
.RS 4
Identifies what impelemntation of TC will be used\&. If relative name is used then the path org\&.griphyn\&.cPlanner\&.tc is prefixed to the name and used as the class name to load\&. The default value if
\fBText\fR\&. Other supported mode is
\fBFile\fR
.RE
.PP
\fBpegasus\&.catalog\&.transformation\&.file\fR
.RS 4
The file path where the text based TC is located\&. By default the path
\fB$PEGASUS_HOME/var/tc\&.data\fR
is used\&.
.RE
.SH "FILES"
.PP
\fB$PEGASUS_HOME/var/tc\&.data\fR
.RS 4
is the suggested location for the file corresponding to the Transformation Catalog
.RE
.PP
\fB$PEGASUS_HOME/etc/properties\fR
.RS 4
is the location to specify properties to change what Transformation Catalog Implementation to use and the implementation related
\fBPROPERTIES\fR\&.
.RE
.PP
\fBpegasus\&.jar\fR
.RS 4
contains all compiled Java bytecode to run the Pegasus planner\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
\fBPEGASUS_HOME\fR
.RS 4
Path to the PEGASUS installation directory\&.
.RE
.PP
\fBJAVA_HOME\fR
.RS 4
Path to the JAVA 1\&.4\&.x installation directory\&.
.RE
.PP
\fBCLASSPATH\fR
.RS 4
The classpath should be set to contain all necessary PEGASUS files for the execution environment\&. To automatically add the
\fICLASSPATH\fR
to you environment, in the
\fI$PEGASUS_HOME\fR
directory run the script
\fIsource setup\-user\-env\&.csh\fR
or
\fIsource setup\-user\-env\&.sh\fR\&.
.RE
.SH "AUTHORS"
.sp
Gaurang Mehta <gmehta at isi dot edu>
.sp
Karan Vahi <vahi at isi dot edu>
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
