'\" t
.\"     Title: pegasus-dax-validator
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/23/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-DAX\-VALIDA" "1" "02/23/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-dax-validator \- determines if a given DAX file is valid\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-dax\-validator\fR \fIdaxfile\fR [\fIverbose\fR]
.fi
.SH "DESCRIPTION"
.sp
The \fBpegasus\-dax\-validator\fR is a simple application that determines, if a given DAX file is valid XML\&. For this, it parses the file with as many XML validity checks that the Apache Xerces XML parser framework supports\&.
.SH "OPTIONS"
.PP
\fIdaxfile\fR
.RS 4
The location of the file containing the DAX\&.
.RE
.PP
\fIverbose\fR
.RS 4
If any kind of second argument was specified, not limited to the string
\fIverbose\fR, the verbose output mode is switched on\&.
.RE
.SH "RETURN VALUE"
.sp
If the DAX was parsed successfully, or only \fIwarning\(cqs were issued, the exit code is 0\&. Any \*(Aqerror\fR or \fIfatal error\fR will result in an exit code of 1\&.
.sp
Additionally, a summary statistics with counts of warnings, errors, and fatal errors will be displayed\&.
.SH "EXAMPLE"
.sp
The following shows the parsing of a DAX file that uses the wrong kind of value for certain enumerations\&. The output shows the errors with the respective line number and column number of the input DAX file, so that one can find and fix them more easily\&. (The lines in the example were broken to fit the manpage format\&.)
.sp
.if n \{\
.RS 4
.\}
.nf
$ pegasus\-dax\-validator bd\&.dax
ERROR in line 14, col 110: cvc\-enumeration\-valid: Value \*(Aqi386\*(Aq is not
 facet\-valid with respect to enumeration \*(Aq[x86, x86_64, ppc, ppc_64,
 ia64, sparcv7, sparcv9, amd64]\*(Aq\&. It must be a value from the
 enumeration\&.
ERROR in line 14, col 110: cvc\-attribute\&.3: The value \*(Aqi386\*(Aq of
 attribute \*(Aqarch\*(Aq on element \*(Aqexecutable\*(Aq is not valid with respect to
 its type, \*(AqArchitectureType\*(Aq\&.
ERROR in line 14, col 110: cvc\-enumeration\-valid: Value \*(Aqdarwin\*(Aq is
 not facet\-valid with respect to enumeration \*(Aq[aix, sunos, linux, macosx,
 windows]\*(Aq\&. It must be a value from the enumeration\&.
ERROR in line 14, col 110: cvc\-attribute\&.3: The value \*(Aqdarwin\*(Aq of
 attribute \*(Aqos\*(Aq on element \*(Aqexecutable\*(Aq is not valid with respect to
 its type, \*(AqOSType\*(Aq\&.

0 warnings, 4 errors, and 0 fatal errors detected\&.
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
Apache Xerces\-J \m[blue]\fBhttp://xerces\&.apache\&.org/xerces2\-j/\fR\m[]
.SH "AUTHORS"
.sp
Jens\-S\&. Vöckler <voeckler at isi dot edu>
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu/\fR\m[]
