'\" t
.\"     Title: pegasus-config
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/23/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-CONFIG" "1" "02/23/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-config \- The authority for where parts of the Pegasus system exists on the filesystem\&. pegasus\-config can be used to find libraries such as the DAX generators\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-config\fR [\fB\-h\fR] [\fB\-\-help\fR] [\fB\-V\fR] [\fB\-\-version\fR]
               [\fB\-\-perl\-dump\fR] [\fB\-\-perl\-hash\fR] [\fB\-\-python\-dump\fR] [\fB\-\-sh\-dump\fR]
               [\fB\-\-bin\fR] [\fB\-\-conf\fR] [\fB\-\-java\fR] [\fB\-\-perl\fR] [\fB\-\-python\fR]
               [\fB\-\-python\-externals\fR] [\fB\-\-schema\fR] [\fB\-\-classpath\fR]
               [\fB\-\-local\-site\fR] [\fB\-\-full\-local\fR]
.fi
.SH "DESCRIPTION"
.sp
\fBpegasus\-config\fR is used to find locations of Pegasus system components\&. The tool is used internally in Pegasus and by users who need to find paths for DAX generator libraries and schemas\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints help and exits\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Prints Pegasus version information
.RE
.PP
\fB\-\-perl\-dump\fR
.RS 4
Dumps all settings in perl format as separate variables\&.
.RE
.PP
\fB\-\-perl\-hash\fR
.RS 4
Dumps all settings in perl format as single perl hash\&.
.RE
.PP
\fB\-\-python\-dump\fR
.RS 4
Dumps all settings in python format\&.
.RE
.PP
\fB\-\-sh\-dump\fR
.RS 4
Dumps all settings in shell format\&.
.RE
.PP
\fB\-\-bin\fR
.RS 4
Print the directory containing Pegasus binaries\&.
.RE
.PP
\fB\-\-conf\fR
.RS 4
Print the directory containing configuration files\&.
.RE
.PP
\fB\-\-java\fR
.RS 4
Print the directory containing the jars\&.
.RE
.PP
\fB\-\-perl\fR
.RS 4
Print the directory to include into your PERL5LIB\&.
.RE
.PP
\fB\-\-python\fR
.RS 4
Print the directory to include into your PYTHONLIB\&.
.RE
.PP
\fB\-\-python\-externals\fR
.RS 4
Print the directory to the external Python libraries\&.
.RE
.PP
\fB\-\-schema\fR
.RS 4
Print the directory containing schemas\&.
.RE
.PP
\fB\-\-classpath\fR
.RS 4
Builds a classpath containing the Pegasus jars\&.
.RE
.PP
\fB\-\-noeoln\fR
.RS 4
Do not produce a end\-of\-line after output\&. This is useful when being called from non\-shell backticks in scripts\&.
.RE
.PP
\fB\-\-local\-site\fR [d]
.RS 4
Create a site catalog entry for site "local"\&. This is only an XML snippet without root element nor XML headers\&. The optional argument "d" points to the mount point to use\&. If not specified, defaults to the user\(cqs $HOME directory\&.
.RE
.PP
\fB\-\-full\-local\fR [d]
.RS 4
Create a complete site catalog with only site "local"\&. The an XML snippet without root element nor XML headers\&. The optional argument "d" points to the mount point to use\&. If not specified, defaults to the user\(cqs $HOME directory\&.
.RE
.SH "EXAMPLE"
.sp
To set the PYTHONPATH for using the Python DAX API:
.sp
.if n \{\
.RS 4
.\}
.nf
export PYTHONPATH=`pegasus\-config \-\-python \-\-noeoln`
.fi
.if n \{\
.RE
.\}
.sp
To set the same path inside Python:
.sp
.if n \{\
.RS 4
.\}
.nf
# Use pegasus\-config to find our Pegasus environment
bin_dir = os\&.path\&.normpath(os\&.path\&.join(os\&.path\&.dirname(sys\&.argv[0])))
pegasus_config = os\&.path\&.join(bin_dir, "pegasus\-config") + " \-\-python\-dump"
config = subprocess\&.Popen(pegasus_config, stdout=subprocess\&.PIPE, shell=True)\&.communicate()[0]
exec config
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
