'\" t
.\"     Title: pegasus-tc-converter
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/27/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PEGASUS\-TC\-CONVERT" "1" "02/27/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pegasus-tc-converter \- A client to convert transformation catalog from one format to another format\&.
.SH "SYNOPSIS"
.sp
.nf
\fBpegasus\-tc\-converter\fR [\fB\-D\fR\fIproperty=value\fR\&...] [\fB\-v\fR] [\fB\-q\fR] [\fB\-V\fR] [\fB\-h\fR]
                     [\fB\-I\fR \fIfmt\fR] [\fB\-O\fR \fIfmt\fR]
                     [\fB\-N\fR \fIdbusername\fR] [\fB\-P\fR \fIdbpassword\fR] [\fB\-U\fR \fIdburl\fR] [\fB\-H\fR \fIdbhost\fR]
                     \fB\-i\fR \fIinfile\fR[,\fIinfile\fR,\&...] \fB\-o\fR \fIoutfile\fR
.fi
.SH "DESCRIPTION"
.sp
The tc\-convert program is used to convert the transformation catalog from one format to another\&.
.sp
Currently, the following formats of transformation catalog exist:
.PP
\fBText\fR
.RS 4
This is a easy to read multi line textual format\&.
.sp
A sample entry in this format looks as follows:
.sp
.if n \{\
.RS 4
.\}
.nf
tr example::keg:1\&.0 {
        site isi {
        profile env "JAVA_HOME" "/bin/java\&.1\&.6"
        pfn "/path/to/keg"
        arch  "x86"
        os    "linux"
        osrelease "fc"
        osversion "4"
        type "installed"
    }
}
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBFile\fR
.RS 4
This is a tuple based format which contains 6 columns\&.
.sp
.if n \{\
.RS 4
.\}
.nf
RESOURCE  LFN  PFN  TYPE  SYSINFO  PROFILES
.fi
.if n \{\
.RE
.\}
.sp
A sample entry in this format looks as follows
.sp
.if n \{\
.RS 4
.\}
.nf
isi  example::keg:1\&.0  /path/to/keg  INSTALLED  INTEL32::LINUX:fc_4:  env::JAVA_HOME="/bin/java\&.1\&.6"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBDatabase\fR
.RS 4
Only MySQL is supported for the time being\&.
.RE
.SH "OPTIONS"
.PP
\fB\-D\fR\fIproperty=value\fR
.RS 4
The
\fB\-D\fR
option allows an experienced user to override certain properties which influence the program execution, among them the default location of the user\(cqs properties file and the
\fBPEGASUS_HOME\fR
location\&. One may set several CLI properties by giving this option multiple times\&.
.sp
The
\fB\-D\fR
option(s) must be the first option on the command line\&. CLI properties take precedence over the file\-based properties of the same key\&.
.RE
.PP
\fB\-I\fR \fIfmt\fR, \fB\-\-iformat\fR \fIfmt\fR
.RS 4
The input format of the input files\&. Valid values for the input format are:
\fBFile\fR,
\fBText\fR, and
\fBDatabase\fR\&.
.RE
.sp
\fB\-O\fR \fIfmt\fR \fB\-\-oformat\fR \fIfmt\fR The output format of the output file\&. Valid values for the output format are: \fBFile\fR, \fBText\fR, and \fBDatabase\fR\&.
.sp
\fB\-i\fR \fIinfile\fR[,\fIinfile\fR,\&...] \fB\-\-input\fR \fIinfile\fR[,\fIinfile\fR,\&...] The comma separated list of input files that need to be converted to a file in the format specified by the \fB\-\-oformat\fR option\&.
.PP
\fB\-o\fR \fIoutfile\fR, \fB\-\-output\fR \fIoutfile\fR
.RS 4
The output file to which the output needs to be written out to\&.
.RE
.SS "Other Options"
.PP
\fB\-N\fR \fIdbusername\fR, \fB\-\-db\-user\-name\fR \fIdbusername\fR
.RS 4
The database user name\&.
.RE
.PP
\fB\-P\fR \fIdbpassword\fR, \fB\-\-db\-user\-pwd\fR \fIdbpassword\fR
.RS 4
The database user password\&.
.RE
.PP
\fB\-U\fR \fIdburl\fR, \fB\-\-db\-url\fR \fIdburl\fR
.RS 4
The database url\&.
.RE
.PP
\fB\-H\fR \fIdbhost\fR, \fB\-\-db\-host\fR \fIdbhost\fR
.RS 4
The database host\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increases the verbosity of messages about what is going on\&. By default, all FATAL ERROR, ERROR , CONSOLE and WARNINGS messages are logged\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Decreases the verbosity of messages about what is going on\&. By default, all FATAL ERROR, ERROR , CONSOLE and WARNINGS messages are logged\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Displays the current version number of the Pegasus Workflow Planner Software\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Displays all the options to the
\fBpegasus\-tc\-converter\fR
command\&.
.RE
.SH "EXAMPLE"
.PP
Text to file format conversion
.RS 4
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
pegasus\-tc\-converter \-i tc\&.data \-I File \-o tc\&.txt  \-O Text \-v
.fi
.if n \{\
.RE
.\}
.PP
File to Database(new) format conversion
.RS 4
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
pegasus\-tc\-converter \-i tc\&.data \-I File \-N mysql_user \-P mysql_pwd \-U jdbc:mysql://localhost:3306/tc \-H localhost \-O Database \-v
.fi
.if n \{\
.RE
.\}
.PP
Database (username, password, host, url specified in properties file) to text format conversion
.RS 4
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
pegasus\-tc\-converter \-I Database \-o tc\&.txt \-O Text \-vvvvv
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
Prasanth Thomas
.sp
Pegasus Team \m[blue]\fBhttp://pegasus\&.isi\&.edu\fR\m[]
