#!/bin/sh
#
# parse the returned invocation record and optionally pass 
# into the database. Make the parser return a non-zero exitcode
# on remote application failures. 
# $Id$
#
no_heap_setup=1
. `dirname $0`/../bin/common.sh

# run java program
${JAVA} "-Dpegasus.home=${PEGASUS_HOME}" $addon edu.isi.pegasus.planner.client.ExitCode "$@"
