#!/bin/sh
#
# parse the returned invocation record and optionally pass 
# into the database. Make the parser return a non-zero exitcode
# on remote application failures. 
# $Id$
#
no_heap_setup=1
save=$CLASSPATH
. `dirname $0`/../bin/common.sh
CLASSPATH=$save; export CLASSPATH
unset save

# run java program
${JAVA_HOME}/bin/java "-Dpegasus.home=${PEGASUS_HOME}" $addon edu.isi.pegasus.planner.client.ExitCode "$@"
