[tox]

default_base_python = 3.14, 3.13, 3.12, 3.11, 3.10

envlist = py310, py311, py312, py313, py314, py315
skip_missing_interpreters = True
minversion = 3.4.0


[testenv]

commands     = pytest --junit-xml test-reports/pyunit.xml --cov --cov-branch --cov-report term --cov-report html:test-reports/htmlcov --cov-report xml:test-reports/coverage.xml --no-cov-on-fail --cov-fail-under 48 {posargs:test}

passenv      =
    USER
    CPATH

setenv       =
    PYTHONUNBUFFERED = yes
    PYTHONHASHSEED   = 3104489401

skip_install = {env:SKIP_INSTALL:False}

deps         =
    pytest
    pytest-mock
    coverage
    pytest-cov
    ../pegasus-python


[testenv:lint]

skipsdist               = True

skip_install            = True

commands                =
    ruff check  --target-version py310
    ruff format --target-version py310

deps                    =
    ruff
