#!/bin/bash

set -e

export TOPDIR=`pwd`

# generate the dax
PYTHONPATH=$(pegasus-config --python) ./dax-gen.py

# site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "condor_pool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    env:
      PEGASUS_TRANSFER_ERROR_RATE: "5"
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "staging_site"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "${TOPDIR}/staging-site/scratch/043-integrity-synthetic-with-errors"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "scp://bamboo@bamboo.isi.edu${TOPDIR}/staging-site/scratch/043-integrity-synthetic-with-errors"
  profiles:
    pegasus:
      ssh_private_key: "/scitech/shared/home/bamboo/.ssh/workflow_id_rsa"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "${TOPDIR}/LOCAL/shared-storage"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file:///${TOPDIR}/LOCAL/shared-storage"
   -
    type: "sharedScratch"
    path: "${TOPDIR}/LOCAL/shared-scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file:///${TOPDIR}/LOCAL/shared-scratch"
EOF

echo
echo
echo "Planning and submitting the workflow..."
pegasus-plan \
    --conf pegasusrc \
    --dir submitflow \
    --sites condor_pool \
    --staging-site staging_site \
    --output-sites local \
    --submit \
    dax.yml
