#!/bin/sh
### BEGIN INIT INFO
# Provides:          pegasus-service
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts and stops the Pegasus web dashboard service
### END INIT INFO


RUNAS=root
NAME=pegasus-service
PORT=5000

# for RPM installs
PEGASUS_INSTALL_DIR=/usr
DAEMON=$PEGASUS_INSTALL_DIR/bin/$NAME

PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME);
  then
    echo "Service $NAME already running" >&2
    return 1
  fi
  echo "Starting service $NAME" >&2
  local CMD="$DAEMON -v -p $PORT --host 0.0.0.0 &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo "Service started - $NAME" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -s SIGTERM $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
