#' Representation of a Pegasus Workflow
#'
#' @param name The name of the workflow
#' @return An object with a Workflow
#' @export
#'
#' @examples
#' # Example of a black diamond workflow
#' # Create a Workflow
#' diamond <- Workflow("diamond")
#'
#' # Add some metadata
#' diamond <- Metadata(diamond, "name", "diamond")
#' diamond <- Metadata(diamond, "createdby", "Rafael Ferreira da Silva")
#'
#' # Add input file to the DAX-level replica catalog
#' a <- File("f.a")
#' a <- AddPFN(a, PFN("gsiftp://site.com/inputs/f.a", "site"))
#' a <- Metadata(a, "size", "1024")
#' diamond <- AddFile(diamond, a)
#'
#' # Add executables to the DAX-level replica catalog
#' e.preprocess <- Executable(namespace="bd",name="process",version="4.0",os="linux",arch="x86_64")
#' e.preprocess <- Metadata(e.preprocess,"size","2048")
#' e.preprocess <- AddPFN(e.preprocess, PFN("gsiftp://site.com/bin/preprocess", "site"))
#' diamond <- AddExecutable(diamond, e.preprocess)
#'
#' e.findrange <- Executable(namespace="bd",name="frange",version="4.0",os="linux",arch="x86_64")
#' e.findrange <- AddPFN(e.findrange, PFN("gsiftp://site.com/bin/findrange", "site"))
#' diamond <- AddExecutable(diamond, e.findrange)
#'
#' e.analyze <- Executable(namespace="bd",name="analyze",version="4.0",os="linux",arch="x86_64")
#' e.analyze <- AddPFN(e.analyze, PFN("gsiftp://site.com/bin/analyze", "site"))
#' diamond <- AddExecutable(diamond, e.analyze)
#'
#' # Add a preprocess job
#' preprocess <- Job(e.preprocess)
#' preprocess <- Metadata(preprocess, "time", "60")
#' b1 <- File("f.b1")
#' b2 <- File("f.b2")
#' preprocess <- AddArguments(preprocess, list("-a","preprocess","-T","3","-i",a,"-o",b1,b2))
#' preprocess <- Uses(preprocess, a, link=Pegasus.Link$INPUT)
#' preprocess <- Uses(preprocess, b1, link=Pegasus.Link$OUTPUT, transfer=TRUE)
#' preprocess <- Uses(preprocess, b2, link=Pegasus.Link$OUTPUT, transfer=TRUE)
#' diamond <- AddJob(diamond, preprocess)
#'
#' # Add left Findrange job
#' frl <- Job(e.findrange)
#' frl <- Metadata(frl, "time", "60")
#' c1 <- File("f.c1")
#' frl <- AddArguments(frl, list("-a","findrange","-T","3","-i",b1,"-o",c1))
#' frl <- Uses(frl, b1, link=Pegasus.Link$INPUT)
#' frl <- Uses(frl, c1, link=Pegasus.Link$OUTPUT, transfer=TRUE)
#' diamond <- AddJob(diamond, frl)
#'
#' # Add right Findrange job
#' frr <- Job(e.findrange)
#' frr <- Metadata(frr, "time", "60")
#' c2 <- File("f.c2")
#' frr <- AddArguments(frr, list("-a","findrange","-T","3","-i",b2,"-o",c2))
#' frr <- Uses(frr, b2, link=Pegasus.Link$INPUT)
#' frr <- Uses(frr, c2, link=Pegasus.Link$OUTPUT, transfer=TRUE)
#' diamond <- AddJob(diamond, frr)
#'
#' # Add Analyze job
#' analyze <- Job(e.analyze)
#' analyze <- Metadata(analyze, "time", "60")
#' d <- File("f.d")
#' analyze <- AddArguments(analyze, list("-a","analyze","-T","3","-i",c1,c2,"-o",d))
#' analyze <- Uses(analyze, c1, link=Pegasus.Link$INPUT)
#' analyze <- Uses(analyze, c2, link=Pegasus.Link$INPUT)
#' analyze <- Uses(analyze, d, link=Pegasus.Link$OUTPUT, transfer=TRUE)
#' diamond <- AddJob(diamond, analyze)
#'
#' # Add dependencies
#' diamond <- Depends(diamond, parent=preprocess, child=frl)
#' diamond <- Depends(diamond, parent=preprocess, child=frr)
#' diamond <- Depends(diamond, parent=frl, child=analyze)
#' diamond <- Depends(diamond, parent=frr, child=analyze)
#'
#' # Get generated diamond dax
#' WriteYAML(diamond, stdout())
#'
#' @export
Workflow <- function(name) {
  if (!IsDefined(name)) {
    stop(paste("Invalid workflow name:", name))
  }
  object <- list(name=name, sequence=1, jobs=list(), files=c(),
                 executables=c(), dependencies=c(), transformations=c(),
                 invoke.mixin=InvokeMixin(), metadata.mixin=MetadataMixin())
  class(object) <- "Workflow"
  return (object)
}

#' Get an autogenerated ID for the next job
#'
#' @param workflow Workflow object
#' @return Abstract workflow object with updated sequence number and the next.id in list format: \code{list(Workflow, next.id)}
#' @seealso \code{\link{Workflow}}
NextJobID <- function(workflow) {
  next.id <- NULL
  while (is.null(next.id) || next.id %in% names(workflow$jobs)) {
    next.id <- paste("ID", sprintf("%07d", workflow$sequence), sep="")
    workflow$sequence <- workflow$sequence + 1
  }
  return(list(workflow=workflow, next.id=next.id))
}

#' Get a Job/DAG/Workflow
#'
#' @param workflow Workflow object
#' @param jobid Job identification
#' @return Job/DAG/Workflow object
#' @seealso \code{\link{Workflow}}, \code{\link{HasJob}}
#' @export
GetJob <- function(workflow, jobid) {
  if (!(jobid %in% names(workflow$jobs))) {
    stop(paste("Job not found:", jobid))
  }
  return(workflow$jobs[jobid])
}

#' Add a job to the Workflow
#'
#' @param workflow Workflow object
#' @param job Job object
#' @return Workflow object with the job appended
#' @seealso \code{\link{Workflow}}, \code{\link{RemoveJob}}
#' @export
AddJob <- function(workflow, job) {
  # Add an auto-generated ID if the job doesn't have one
  if (HasJob(workflow, job)) {
    stop(paste("Duplicate job:", job))
  }
  if (!IsDefined(job$abstract.job$id)) {
    l <- NextJobID(workflow)
    job$abstract.job$id <- l$next.id
    workflow <- l$workflow
  }
  workflow$jobs[[job$abstract.job$id]] <- job
  return(workflow)
}

#' Test to see if job is in this Workflow
#'
#' @description
#' The job parameter can be an object or a job ID.
#'
#' @param workflow Workflow object
#' @param job Job/DAG/Workflow object
#' @return If the Job/DAG/Workflow is in the Workflow
#' @seealso \code{\link{Workflow}}, \code{\link{GetJob}}
HasJob <- function(workflow, job) {
  if (class(job) == "Job" || class(job) == "DAG" || class(job) == "DAX") {
    for (j in workflow$jobs) {
      if (Equals(j, job)) {
        return(TRUE)
      }
    }
    return(FALSE)
  } else {
    return(job %in% names(workflow$jobs))
  }
}

#' Remove job from the Workflow
#'
#' @param workflow Workflow object
#' @param job Job/DAG/Workflow object
#' @return The Workflow object without the Job/DAG/Workflow
#' @seealso \code{\link{Workflow}}, \code{\link{AddJob}}, \code{\link{ClearJobs}}
#' @export
RemoveJob <- function(workflow, job) {
  if (!HasJob(workflow, job)) {
    stop("Job not found", job)
  }
  if (class(job) == "Job" || class(job) == "DAG" || class(job) == "DAX") {
    workflow$jobs[job$abstract.job$id] <- NULL
  } else {
    workflow$jobs[job] <- NULL
  }
  return(workflow)
}

#' Remove all jobs
#'
#' @param workflow Workflow object
#' @return The Workflow object with no jobs
#' @seealso \code{\link{Workflow}}, \code{\link{RemoveJob}}, \code{\link{AddJob}}
#' @export
ClearJobs <- function(workflow) {
  workflow$jobs <- list()
  return(workflow)
}

#' Add a sub-DAX (synonym for addJob)
#'
#' @param workflow Workflow object
#' @param dax Sub-DAX to be appended
#' @return The Workflow object with the sub-DAX appended
#' @seealso \code{\link{Workflow}}, \code{\link{AddJob}}, \code{\link{DAX}}
#' @export
AddDAX <- function(workflow, dax) {
  if (class(dax) != "DAX") {
    stop(paste("Not a DAX", dax))
  }
  workflow <- AddJob(workflow, dax)
  return(workflow)
}

#' Add a sub-DAG (synonym for addJob)
#'
#' @param workflow Workflow object
#' @param dag Sub-DAG to be appended
#' @return The Workflow object with the sub-DAG appended
#' @seealso \code{\link{Workflow}}, \code{\link{AddJob}}, \code{\link{DAG}}
#' @export
AddDAG <- function(workflow, dag) {
  if (class(dag) != "DAG") {
    stop(paste("Not a DAG", dag))
  }
  workflow <- AddJob(workflow, dag)
  return(workflow)
}

#' Add a file to the Workflow
#'
#' @param workflow Workflow object
#' @param file File object
#' @return The Workflow object with the file appended
#' @seealso \code{\link{Workflow}}, \code{\link{File}}, \code{\link{RemoveFile}}, \code{\link{ClearFiles}}
#' @export
AddFile <- function(workflow, file) {
  if (class(file) != "File") {
    stop(paste("Invalid file:", file$catalog.type$name))
  }
  if (HasFile(workflow, file)) {
    stop(paste("Duplicate file:", file$catalog.type$name))
  }
  workflow$files <- AppendToList(workflow$files, file)
  return(workflow)
}

#' Check to see if file is in the Workflow
#'
#' @param workflow Workflow object
#' @param file File object
#' @return If the Workflow object contains the file
#' @seealso \code{\link{Workflow}}, \code{\link{File}}
HasFile <- function(workflow, file) {
  for (f in workflow$files) {
    if (Equals(f, file)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

#' Remove file from this Workflow
#'
#' @param workflow Workflow object
#' @param file File object
#' @return The Workflow object without the file
#' @seealso \code{\link{Workflow}}, \code{\link{File}}, \code{\link{AddFile}}, \code{\link{ClearFiles}}
#' @export
RemoveFile <- function(workflow, file) {
  if (length(workflow$files) > 0) {
    for (i in 1:length(workflow$files)) {
      o <- workflow$files[[i]]
      if (Equals(o, file)) {
        workflow$files[i] <- NULL
        return(workflow)
      }
    }
  }
  stop(paste("File not found:", file))
}

#' Remove all files
#'
#' @param workflow Workflow object
#' @return The Workflow object with no files
#' @seealso \code{\link{Workflow}}, \code{\link{File}}, \code{\link{AddFile}}, \code{\link{RemoveFile}}
#' @export
ClearFiles <- function(workflow) {
  workflow$files <- c()
  return(workflow)
}

#' Add an executable to the Workflow
#'
#' @param workflow Workflow object
#' @param executable Executable object
#' @return The Workflow object with the executable appended
#' @seealso \code{\link{Workflow}}, \code{\link{Executable}},
#'  \code{\link{RemoveExecutable}}, \code{\link{ClearExecutables}}
#' @export
AddExecutable <- function(workflow, executable) {
  if (HasExecutable(workflow, executable)) {
    stop(paste("Duplicate executable:", executable$catalog.type$name))
  }
  workflow$executables <- AppendToList(workflow$executables, executable)
  return(workflow)
}

#' Check if executable is in this Workflow
#'
#' @param workflow Workflow object
#' @param executable Executable object
#' @return If the executable is in the Workflow
#' @seealso \code{\link{Workflow}}, \code{\link{Executable}}
HasExecutable <- function(workflow, executable) {
  for (e in workflow$executables) {
    if (Equals(e, executable)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

#' Remove executable from the Workflow
#'
#' @param workflow Workflow object
#' @param executable Executable object
#' @return The Workflow object without the executable
#' @seealso \code{\link{Workflow}}, \code{\link{Executable}},
#'  \code{\link{AddExecutable}}, \code{\link{ClearExecutables}}
#' @export
RemoveExecutable <- function(workflow, executable) {
  if (length(workflow$executables) > 0) {
    for (i in 1:length(workflow$executables)) {
      o <- workflow$executables[[i]]
      if (Equals(o, executable)) {
        workflow$executables[i] <- NULL
        return(workflow)
      }
    }
  }
  stop(paste("Executable not found:", file))
}

#' Remove all executables
#'
#' @param workflow Workflow object
#' @return The Workflow object with no executables
#' @seealso \code{\link{Workflow}}, \code{\link{Executable}},
#'  \code{\link{AddExecutable}}, \code{\link{RemoveExecutable}}
#' @export
ClearExecutables <- function(workflow) {
  workflow$executables <- c()
  return(workflow)
}

#' Add a transformation to the Workflow
#'
#' @param workflow Workflow object
#' @param transformation Transformation object
#' @return The Workflow object with the transformation appended
#' @seealso \code{\link{Workflow}}, \code{\link{Transformation}},
#'  \code{\link{RemoveTransformation}}, \code{\link{ClearTransformations}}
#' @export
AddTransformation <- function(workflow, transformation) {
  if (HasTransformation(workflow, transformation)) {
    stop(paste("Duplicate transformation:", transformation))
  }
  workflow$transformations <- AppendToList(workflow$transformations, transformation)
  return(workflow)
}

#' Check to see if transformation is in the Workflow
#'
#' @param workflow Workflow object
#' @param transformation Transformation object
#' @return If the Workflow has the transformation
#' @seealso \code{\link{Workflow}}, \code{\link{Transformation}}
HasTransformation <- function(workflow, transformation) {
  for (t in workflow$transformations) {
    if (Equals(t, transformation)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

#' Remove transformation from the Workflow
#'
#' @param workflow Workflow object
#' @param transformation Transformation object
#' @return The Workflow object without the transformation
#' @seealso \code{\link{Workflow}}, \code{\link{Transformation}},
#'  \code{\link{AddTransformation}}, \code{\link{ClearTransformations}}
#' @export
RemoveTransformation <- function(workflow, transformation) {
  if (length(workflow$transformations) > 0) {
    for (i in 1:length(workflow$transformations)) {
      o <- workflow$transformations[[i]]
      if (Equals(o, transformation)) {
        workflow$transformations[i] <- NULL
        return(workflow)
      }
    }
  }
  stop(paste("Transformation not found:", file))
}

#' Remove all transformations
#'
#' @param workflow Workflow object
#' @return The Workflow object with no transformations
#' @seealso \code{\link{Workflow}}, \code{\link{Transformation}},
#'  \code{\link{AddTransformation}}, \code{\link{RemoveTransformation}}
#' @export
ClearTransformations <- function(workflow) {
  workflow$transformations <- c()
  return(workflow)
}

#' Add a dependency to the workflow
#'
#' @param workflow The Workflow object
#' @param child The child job/dax/dag or id
#' @param parent The parent job/dax/dag or id
#' @param edge.label A label for the edge (optional)
#' @return The Workflow object with the dependency appended
#' @seealso \code{\link{Workflow}}, \code{\link{Dependency}}, \code{\link{AddDependency}}
#' @export
Depends <- function(workflow, child, parent, edge.label=NULL) {
  # find jobs to fix ID
  p.parent <- NULL
  p.child <- NULL
  for (j in workflow$jobs) {
    if (Equals(parent, j)) {
      p.parent <- j
    } else if (Equals(child, j)) {
      p.child <- j
    }
    if (!is.null(p.parent) && !is.null(p.child)) {
      break
    }
  }
  d <- Dependency(p.parent, p.child, edge.label)
  workflow <- AddDependency(workflow, d)
  return(workflow)
}

#' Add a dependency to the workflow
#'
#' @param workflow The Workflow object
#' @param dep The dependency object
#' @return The Workflow object containing the dependency
#' @seealso \code{\link{Workflow}}, \code{\link{Dependency}},
#'  \code{\link{Depends}}, \code{\link{RemoveDependency}}
#' @export
AddDependency <- function(workflow, dep) {
  if (HasDependency(workflow, dep)) {
    stop(paste("Duplicate dependency:", dep))
  }
  # Check the jobs
  if (!(dep$parent %in% names(workflow$jobs))) {
    stop(paste("Parent not found:", dep$parent))
  }
  if (!(dep$child %in% names(workflow$jobs))) {
    stop(paste("Child not found:", dep$child))
  }
  workflow$dependencies <- AppendToList(workflow$dependencies, dep)
  return(workflow)
}

#' Check to see if dependency exists
#'
#' @param workflow The Workflow object
#' @param dep The dependency object
#' @return If the Workflow contains the dependency
#' @seealso \code{\link{Workflow}}, \code{\link{Dependency}}
HasDependency <- function(workflow, dep) {
  for (d in workflow$dependencies) {
    if (Equals(d, dep)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

#' Remove dependency from workflow
#'
#' @param workflow The Workflow object
#' @param dep The dependency object
#' @return The Workflow object without the dependency
#' @seealso \code{\link{Workflow}}, \code{\link{Dependency}},
#'  \code{\link{Depends}}, \code{\link{AddDependency}}
#' @export
RemoveDependency <- function(workflow, dep) {
  if (length(workflow$dependencies) > 0) {
    for (i in 1:length(workflow$dependencies)) {
      o <- workflow$dependencies[[i]]
      if (Equals(o, dep)) {
        workflow$dependencies[i] <- NULL
        return(workflow)
      }
    }
  }
  stop(paste("Dependency not found:", file))
}

#' Remove all dependencies
#'
#' @param workflow The Workflow object
#' @return The Workflow object with no dependencies
#' @seealso \code{\link{Workflow}}, \code{\link{Dependency}},
#'  \code{\link{Depends}}, \code{\link{AddDependency}},
#'  \code{\link{RemoveDependency}}
#' @export
ClearDependencies <- function(workflow) {
  workflow$dependencies <- c()
  return(workflow)
}

#' Write the Workflow to a YAML file
#'
#' @param workflow The Workflow object
#' @param filename Name of the file
#' @seealso \code{\link{Workflow}}, \code{\link{WriteYAML}}
#' @export
WriteYAMLFile <- function(workflow, filename) {
  WriteYAML(workflow, filename)
}

#' Write the Workflow as YAML to a stream
#'
#' @examples
#' workflow <- Workflow('diamond')
#' WriteYAML(workflow, stdout())
#' WriteYAML(workflow, 'diamond.yml')
#'
#' @param workflow The Workflow object
#' @param out The stream object (e.g., \code{stdout()}, or a filename)
#' @seealso \code{\link{Workflow}}
#' @export
WriteYAML <- function(workflow, out) {
  sink(out)
  
  cat('pegasus: "5.0"\n')
  cat(paste('name: ', workflow$name, '\n', sep=''))
  
  # x-Pegasus
  cat('x-pegasus:\n')
  cat(paste('  createdBy: "', Sys.info()[['user']], '"\n', sep=''))
  cat(paste('  createdOn: "', Sys.time(),'"\n', sep=''))
  cat('  apiLang: "R"\n')
  
  # Metadata
  if (length(workflow$metadata.mixin$metadata.l) > 0) {
    cat('metadata:\n')
    for(m in workflow$metadata.mixin$metadata.l) {
      cat(paste('  ', m$key, ': "', m$value, '"\n', sep=''))
    }
  }

  # Jobs
  if (length(workflow$jobs) > 0) {
    cat('jobs:\n')
    keys <- sort(names(workflow$jobs))
    for (jobid in keys) {
      job <- workflow$jobs[[jobid]]
      ajob <- job$abstract.job
      cat('- type: "job"\n')
      cat(paste('  name: "', job$name, '"\n', sep=''))
      cat(paste('  id: "', ajob$id, '"\n', sep=''))
      
      # Arguments
      if (length(ajob$arguments) > 0) {
        cat('  arguments:\n')
        for (arg in ajob$arguments) {
          if (is.list(arg)) {
            cat(paste('  - "', arg$catalog.type$name, '"\n', sep=''))
          } else if (nchar(trimws(arg)) > 0) {
            cat(paste('  - "', arg, '"\n', sep=''))
          }
        }
      }
      
      # Uses
      if (length(ajob$use.mixin$used) > 0) {
        cat('  uses:\n')
        for (use in ajob$use.mixin$used) {
          cat(paste('  - lfn: "', use$name$catalog.type$name, '"\n', sep=''))
          cat(paste('    type: "', use$link, '"\n', sep=''))
          if (use$link == 'output') {
            cat(paste('    stageOut: "', tolower(use$transfer), '"\n', sep=''))
            cat(paste('    registerReplica: "', tolower(use$register), '"\n', sep=''))
          }
        }
      }
    }
  }
  
  # Job Dependencies
  cat('jobDependencies:\n')
  parents <- list()
  for(dep in workflow$dependencies) {
    if(!(dep$parent %in% names(parents))) {
      parents[[dep$parent]] <- list()
    }
    parents[[dep$parent]] <- AppendToList(parents[[dep$parent]], dep$child)
  }

  # Now output in sorted order by parent, then child
  if (length(parents) > 0) {
    keys <- sort(names(parents))
    for(parent in keys) {
      cat(paste('- id: "', parent, '"\n', sep=''))
      cat('  children:\n')
      for (child in parents[[parent]]) {
        cat(paste('  - "', child, '"\n', sep=''))
      }
    }
  }
  
  if(is.character(out)) {
    sink()
  }
}

# ###############################
# Add-in functions for R
# ###############################

#' @rdname AddInvoke
#' @method AddInvoke Workflow
#' @seealso \code{\link{Workflow}}
#' @export
AddInvoke.Workflow <- function(obj, invoke) {
  obj$invoke.mixin <- AddInvokeMixin(obj$invoke.mixin, invoke)
  return(obj)
}

#' @rdname Metadata
#' @method Metadata Workflow
#' @seealso \code{\link{Workflow}}
#' @export
Metadata.Workflow <- function(obj, key, value) {
  obj$metadata.mixin <- AddMetadataDeclarative(obj$metadata.mixin, key, value)
  return(obj)
}
