<?xml version="1.0" encoding="UTF-8"?>
<!-- generated: 2005-08-19T11:05:58-05:00 -->
<adag xmlns="http://www.griphyn.org/chimera/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.griphyn.org/chimera/DAX http://www.griphyn.org/chimera/dax-1.10.xsd" version="1.10" count="1" index="0" name="vds-config" jobCount="1" fileCount="1" childCount="0">
<!-- part 1: list of all referenced files (may be empty) -->
  <filename file="hw.txt" link="output"/>
<!-- part 2: definition of all jobs (at least one) -->
  <job id="ID000001" namespace="tut" name="echo" level="1" dv-namespace="tut" dv-name="hello">
    <argument>Hello World </argument>
    <stdout file="hw.txt" link="output" varname="file"/>
    <uses file="hw.txt" link="output" dontRegister="false" dontTransfer="false"/>
  </job>
<!-- part 3: list of control-flow dependencies (may be empty) -->
</adag>
