#!/bin/bash

set -e

TOP_DIR=`pwd`

rm -rf build-results
mkdir -p build-results
cd build-results
tar xzf ../results.tar.gz

echo
echo "Files in result set:"
find . -type f -exec ls -l -h {} \;

# upload to pegasus.isi.edu
scp -r * nmibuild@pegasus.isi.edu:/lfs1/webspace/pegasus/wms/download/nightly/

