#!/usr/bin/env perl

use strict;

# some platforms only get worker packages
my $lite = 0;
if ( $ENV{NMI_PLATFORM} =~ /rhas_4/ ) {
    $lite = 1;
}

open( LIST, ">tasklist.nmi" ) || die "Can't open tasklist.nmi: $!\n";

# builds
if ( ! $lite ) {
    print LIST "build-binary\n";
    print LIST "build-wms\n";
}
print LIST "build-worker\n";

# clean
print LIST "clean-sources\n";

# rpms/ debs
if ( ! $lite ) {
    if ($ENV{NMI_PLATFORM} =~ /deb/ || $ENV{NMI_PLATFORM} =~ /ubuntu/) {
        print LIST "build-deb\n";
    }
    if ($ENV{NMI_PLATFORM} =~ /rhas/ || $ENV{NMI_PLATFORM} =~ /rhap/) {
        print LIST "build-rpm\n";
    }
}

# tests
if ( ! $lite ) {
    print LIST "test-binary\n";
    print LIST "test-wms\n";
}
print LIST "test-worker\n";

close( LIST );

