#!/bin/bash

set -e

#######################################################################
#
#  Settings
#

DEGREES=0.5

#######################################################################

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH

# unique directory for this run
RUN_ID=`/bin/date +'%F_%H%M%S'`
RUN_DIR=`pwd`/work/$RUN_ID

rm -rf montage-workflow-v2
git clone https://github.com/pegasus-isi/montage-workflow-v2.git

echo
cd montage-workflow-v2
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.1 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

cat pegasus.properties >> ../pegasusrc

# site catalog
echo
echo "Creating the site catalog..."
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$RUN_DIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$RUN_DIR/outputs"
   -
    type: "sharedScratch"
    path: "$RUN_DIR/scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$RUN_DIR/scratch"
  profiles:
    env:
      MONTAGE_HOME: "/ccg/software/montage/current"
      http_proxy: "http://workflow.isi.edu:3128"
    condor:
      universe: "local"
    pegasus:
      style: "condor"

EOF

pegasus-plan \
        --conf ../pegasusrc \
        --dir work \
        --relative-dir `date +'%s'` \
        --dax data/montage.dax \
        --sites local \
        --output-site local \
        --cluster horizontal \
        --submit \
        | tee $TOP_DIR/plan.out

