pegasus: "5.0"
name: diamond

hooks:
  shell:
    - _on: all
      cmd: /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-BNT-T1F/test/core/blackdiamond/my-notify.sh

replicaCatalog:
  replicas:
    - lfn: f.a
      pfns:
        - {site: blueridge, pfn: "http://isis.isi.edu/k/f.a"}

transformationCatalog:
  transformations:
    - namespace: diamond
      name: preprocess
      version: "4.0"
      sites:
        - {name: blueridge, pfn: "file:///usr/bin/pegasus-keg", type: stageable, arch: x86, os.type: linux}
    - namespace: diamond
      name: analyze
      version: "4.0"
      sites:
        - {name: blueridge, pfn: "file:///usr/bin/pegasus-keg", type: stageable, arch: x86, os.type: linux}
    - namespace: diamond
      name: findrange
      version: "4.0"
      sites:
        - {name: blueridge, pfn: "file:///usr/bin/pegasus-keg", type: stageable, arch: x86, os.type: linux}

jobs:
  - type: job
    id: ID0000001
    name: preprocess
    namespace: diamond
    version: "4.0"
    arguments:
      - -a preprocess -T5 -i f.a -o f.b1 f.b2
    uses:
      - {lfn: f.b1, type: output}
      - {lfn: f.a, type: input}
      - {lfn: f.b2, type: output}
  - type: job
    id: ID0000002
    name: findrange
    namespace: diamond
    version: "4.0"
    arguments:
      - -a findrange -T5 -i f.b1 -o f.c1
    profiles:
      pegasus:
        enable_for_data_reuse: "true"
    uses:
      - {lfn: f.c1, type: output}
      - {lfn: f.b1, type: input}
  - type: job
    id: ID0000003
    name: findrange
    namespace: diamond
    version: "4.0"
    arguments:
      - -a findrange -T5 -i f.b2 -o f.c2
    uses:
      - {lfn: f.c2, type: output, stageOut: true}
      - {lfn: "f.c2'", type: output, stageOut: false}
      - {lfn: f.b2, type: input}
  - type: job
    id: ID0000004
    name: analyze
    namespace: diamond
    version: "4.0"
    arguments:
      - -a analyze -T5 -i f.c1 f.c2 -o f.d
    hooks:
      shell:
        - _on: at_end
          cmd: /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-BNT-T1F/test/core/blackdiamond/my-notify.sh
    uses:
      - {lfn: f.c2, type: input}
      - {lfn: "f.c2'", type: input}
      - {lfn: f.d, type: output, registerReplica: true}
      - {lfn: f.c1, type: input}

jobDependencies:
  - id: ID0000001
    children:
      - ID0000002
      - ID0000003
  - id: ID0000002
    children:
      - ID0000004
  - id: ID0000003
    children:
      - ID0000004
