pegasus: "5.0"
name: pipeline

hooks:
  shell:
    - _on: all
      cmd: /local-scratch/rynge/git/pegasus/dist/pegasus-4.4.0cvs/bin/../share/pegasus/notification/email

replicaCatalog:
  replicas:
    - lfn: chromosome.txt
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/chromosome.txt"}
    - lfn: HN001_FCD1P1JACXX_L6_SZAIPI024836-36_2.fq
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/NguyenLab_April2013_25genome_sequencing/Clean/HN001_FCD1P1JACXX_L6_SZAIPI024836-36_2.fq"}
    - lfn: reduced_reads.list
      pfns:
        - {site: local, pfn: "scp://rynge@workflow.isi.edu//local-scratch/rynge/soykb/20140307-173857/reduced_reads.list"}
    - lfn: Gmax_275_v2.0.fa.bwt
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.bwt"}
    - lfn: Gmax_275_v2.0.fa
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa"}
    - lfn: Gmax_275_v2.0.fa.fai
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.fai"}
    - lfn: Gmax_275_v2.0.fa.ann
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.ann"}
    - lfn: Gmax_275_v2.0.dict
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.dict"}
    - lfn: Gmax_275_v2.0.fa.amb
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.amb"}
    - lfn: Gmax_275_v2.0.fa.pac
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.pac"}
    - lfn: software.tar.gz
      pfns:
        - {site: local, pfn: "scp://rynge@workflow.isi.edu//local-scratch/rynge/soykb/20140307-173857/software.tar.gz"}
    - lfn: HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/NguyenLab_April2013_25genome_sequencing/Clean/HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq"}
    - lfn: Gmax_275_v2.0.fa.sa
      pfns:
        - {site: irods_iplant, pfn: "irods://taccCorralRes/iplant/home/shared/digbio/NGS_Nguyen/Soybean_RefGenome/Gmax_275_Wm82.a2.v1/Assembly/Gmax_275_v2.0.fa.sa"}

transformationCatalog:
  transformations:
    - name: unified_genotyper_snp
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: unified_genotyper_indel
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: software-wrapper
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/software-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: indel_realign
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: filtering_snp
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: dedup
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/picard-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: sort_sam
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/picard-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: realign_target_creator
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: reduce_reads
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: add_replace
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/picard-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: filtering_indel
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/gatk-wrapper", type: stageable, arch: x86_64, os.type: linux}
    - name: alignment_to_reference
      sites:
        - {name: local, pfn: "scp://rynge@workflow.isi.edu//nfs/asd2/rynge/git/Soybean-Workflow/wrappers/bwa-wrapper", type: stageable, arch: x86_64, os.type: linux}

jobs:
  - type: job
    id: ID0000001
    name: software-wrapper
    arguments:
      - ""
    profiles:
      condor:
        request_memory: "1000"
        request_cpus: "1"
      pegasus:
        label: default
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "1000"
    uses:
      - {lfn: software.tar.gz, type: input}
  - type: job
    id: ID0000002
    name: reduce_reads
    arguments:
      - -T ReduceReads -R Gmax_275_v2.0.fa -I HN001_indel_realigned.bam -o HN001_reduced_reads.bam
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "1"
      pegasus:
        label: largemem
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "10000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: HN001_indel_realigned.bai, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: HN001_reduced_reads.bai, type: output, stageOut: false}
      - {lfn: chromosome.txt, type: input}
      - {lfn: HN001_reduced_reads.bam, type: output, stageOut: false}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: HN001_indel_realigned.bam, type: input}
  - type: job
    id: ID0000003
    name: indel_realign
    arguments:
      - -T IndelRealigner -R Gmax_275_v2.0.fa -I HN001_addrepl.bam -targetIntervals HN001_intervals.list -o HN001_indel_realigned.bam
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "1"
      pegasus:
        label: largemem
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "10000"
    uses:
      - {lfn: HN001_addrepl.bai, type: input}
      - {lfn: HN001_intervals.list, type: input}
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: HN001_indel_realigned.bai, type: output, stageOut: false}
      - {lfn: HN001_addrepl.bam, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: HN001_indel_realigned.bam, type: output, stageOut: false}
  - type: job
    id: ID0000004
    name: realign_target_creator
    arguments:
      - -T RealignerTargetCreator -nt 16 -R Gmax_275_v2.0.fa -I HN001_addrepl.bam -o HN001_intervals.list
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "16"
      pegasus:
        label: largemem
        cores: "16"
        pmc_request_cpus: "16"
        pmc_request_memory: "10000"
    uses:
      - {lfn: HN001_addrepl.bai, type: input}
      - {lfn: HN001_intervals.list, type: output, stageOut: false}
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: HN001_addrepl.bam, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
  - type: job
    id: ID0000005
    name: add_replace
    arguments:
      - "AddOrReplaceReadGroups.jar MAX_RECORDS_IN_RAM=5000000 TMP_DIR=. I=HN001_deduped_reads.bam O=HN001_addrepl.bam RGID=HN001 LB=HN001 PL=\"Illumina\" SM=HN001 CN=BGI RGPU=HN001 VALIDATION_STRINGENCY=LENIENT SORT_ORDER=coordinate CREATE_INDEX=TRUE"
    profiles:
      condor:
        request_memory: "22000"
        request_cpus: "1"
      pegasus:
        label: largemem
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "22000"
    uses:
      - {lfn: HN001_addrepl.bai, type: output, stageOut: false}
      - {lfn: software.tar.gz, type: input}
      - {lfn: HN001_addrepl.bam, type: output, stageOut: false}
      - {lfn: HN001_deduped_reads.bai, type: input}
      - {lfn: HN001_deduped_reads.bam, type: input}
  - type: job
    id: ID0000006
    name: dedup
    arguments:
      - MarkDuplicates.jar CREATE_INDEX=TRUE MAX_RECORDS_IN_RAM=5000000 TMP_DIR=. I=HN001_sorted_reads.bam O=HN001_deduped_reads.bam METRICS_FILE=HN001_deduped.metrics VALIDATION_STRINGENCY=LENIENT
    profiles:
      condor:
        request_memory: "22000"
        request_cpus: "1"
      pegasus:
        label: largemem
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "22000"
    uses:
      - {lfn: HN001_sorted_reads.bai, type: input}
      - {lfn: HN001_deduped.metrics, type: output, stageOut: false}
      - {lfn: HN001_deduped_reads.bai, type: output, stageOut: false}
      - {lfn: HN001_deduped_reads.bam, type: output, stageOut: false}
      - {lfn: software.tar.gz, type: input}
      - {lfn: HN001_sorted_reads.bam, type: input}
  - type: job
    id: ID0000007
    name: sort_sam
    arguments:
      - SortSam.jar CREATE_INDEX=TRUE MAX_RECORDS_IN_RAM=5000000 TMP_DIR=. I=HN001_aligned_reads.sam O=HN001_sorted_reads.bam SO=coordinate VALIDATION_STRINGENCY=LENIENT
    profiles:
      condor:
        request_memory: "22000"
        request_cpus: "1"
      pegasus:
        label: largemem
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "22000"
    uses:
      - {lfn: HN001_sorted_reads.bai, type: output, stageOut: false}
      - {lfn: software.tar.gz, type: input}
      - {lfn: HN001_sorted_reads.bam, type: output, stageOut: false}
      - {lfn: HN001_aligned_reads.sam, type: input}
  - type: job
    id: ID0000008
    name: alignment_to_reference
    arguments:
      - mem -t 12 -M Gmax_275_v2.0.fa HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq HN001_FCD1P1JACXX_L6_SZAIPI024836-36_2.fq
    stdout: HN001_aligned_reads.sam
    profiles:
      condor:
        request_memory: "8000"
        request_cpus: "8"
      pegasus:
        label: bwa
        cores: "8"
        pmc_request_cpus: "8"
        pmc_request_memory: "8000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: HN001_aligned_reads.sam, type: output, stageOut: false}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: HN001_FCD1P1JACXX_L6_SZAIPI024836-36_2.fq, type: input}
  - type: job
    id: ID0000009
    name: unified_genotyper_snp
    arguments:
      - -T UnifiedGenotyper -nt 16 -R Gmax_275_v2.0.fa -glm SNP -I reduced_reads.list -o raw_snp.vcf
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "16"
      pegasus:
        label: largemem_uni
        cores: "16"
        pmc_request_cpus: "16"
        pmc_request_memory: "10000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: reduced_reads.list, type: input}
      - {lfn: HN001_reduced_reads.bai, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: HN001_reduced_reads.bam, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: raw_snp.vcf, type: output, stageOut: false}
  - type: job
    id: ID0000010
    name: filtering_snp
    arguments:
      - "-T VariantFiltration -R Gmax_275_v2.0.fa -V raw_snp.vcf --filterExpression 'QD < 2.0 || FS > 60.0 || MQ < 40.0' --filterName my_snp_filter -o filtered_snp.vcf"
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "1"
      pegasus:
        label: largemem_uni
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "10000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: filtered_snp.vcf, type: output, stageOut: true}
      - {lfn: chromosome.txt, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: raw_snp.vcf, type: input}
  - type: job
    id: ID0000011
    name: unified_genotyper_indel
    arguments:
      - -T UnifiedGenotyper -nt 16 -R Gmax_275_v2.0.fa -glm INDEL -I reduced_reads.list -o raw_indel.vcf
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "16"
      pegasus:
        label: largemem_uni
        cores: "16"
        pmc_request_cpus: "16"
        pmc_request_memory: "10000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: reduced_reads.list, type: input}
      - {lfn: HN001_reduced_reads.bai, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: HN001_reduced_reads.bam, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: raw_indel.vcf, type: output, stageOut: false}
  - type: job
    id: ID0000012
    name: filtering_indel
    arguments:
      - "-T VariantFiltration -R Gmax_275_v2.0.fa -V raw_indel.vcf --filterExpression 'QD < 2.0 || ReadPosRankSum < -20.0 || InbreedingCoeff < -0.8 || FS > 200.0' --filterName my_indel_filter -o filtered_indel.vcf"
    profiles:
      condor:
        request_memory: "10000"
        request_cpus: "1"
      pegasus:
        label: largemem_uni
        cores: "1"
        pmc_request_cpus: "1"
        pmc_request_memory: "10000"
    uses:
      - {lfn: Gmax_275_v2.0.fa.fai, type: input}
      - {lfn: Gmax_275_v2.0.fa.bwt, type: input}
      - {lfn: Gmax_275_v2.0.fa, type: input}
      - {lfn: Gmax_275_v2.0.fa.ann, type: input}
      - {lfn: Gmax_275_v2.0.fa.amb, type: input}
      - {lfn: chromosome.txt, type: input}
      - {lfn: Gmax_275_v2.0.dict, type: input}
      - {lfn: software.tar.gz, type: input}
      - {lfn: Gmax_275_v2.0.fa.pac, type: input}
      - {lfn: Gmax_275_v2.0.fa.sa, type: input}
      - {lfn: raw_indel.vcf, type: input}
      - {lfn: filtered_indel.vcf, type: output, stageOut: true}

jobDependencies:
  - id: ID0000001
    children:
      - ID0000008
  - id: ID0000002
    children:
      - ID0000009
      - ID0000011
  - id: ID0000003
    children:
      - ID0000002
  - id: ID0000004
    children:
      - ID0000003
  - id: ID0000005
    children:
      - ID0000003
      - ID0000004
  - id: ID0000006
    children:
      - ID0000005
  - id: ID0000007
    children:
      - ID0000006
  - id: ID0000008
    children:
      - ID0000007
  - id: ID0000009
    children:
      - ID0000010
  - id: ID0000011
    children:
      - ID0000012
