#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH
export PYTHONPATH=`pegasus-config --python`

rm -rf montage-workflow-v3
git clone https://github.com/pegasus-isi/montage-workflow-v3.git

echo
echo

cd montage-workflow-v3
./montage-workflow.py --center "275.196290 -16.171530" \
                      --degrees 0.5 \
                      --band 2mass:j:green \
                      --band 2mass:h:blue \
                      --band 2mass:k:red

echo
echo
ls -lh data/
echo
echo
                      
pegasus-plan \
        --dir work \
        --dax data/montage-workflow.yaml \
        --output-site local \
        --cluster horizontal \
        --submit \
        | tee $TOP_DIR/plan.out


