#!/bin/bash

set -e

echo "Running blackdiamond.py"
export PYTHONPATH=`pegasus-config --python`
python3 dax-generator.py 2>&1 | tee plan.out

WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

echo "WORK_DIR is $WORK_DIR"

pegasus-run $WORK_DIR
