#!/bin/bash

set -e

TOP_DIR=`pwd`
WORK_DIR=$TOP_DIR/work

export PATH=/ccg/software/montage/current/bin:$PATH

export GLOBUS_LOCATION=/ccg/software/globus/default

cp ccg-test.config.template ccg-test.config
perl -p -i -e "s:\[WORK_DIR\]:$WORK_DIR:g" ccg-test.config
perl -p -i -e "s/\[USER\]/$USER/g" ccg-test.config

export PEGASUS_VERSION=`pegasus-version`

./galactic-plane ccg-test.config | tee plan.out

