######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Drug-Combination-Therapy, Index = 0, Count = null
# SUBMIT FILE NAME : clean_up_local_level_4_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PATH=/home/mzalam/pegasus-5.0.5/bin:/home/mzalam/wf/condor/bin:/home/mzalam/wf/condor/sbin:/home/mzalam/wf/bin:/home/mzalam/.local/bin:/home/mzalam/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin PYTHONPATH=/home/mzalam/pegasus-5.0.5/lib64/python3.6/site-packages CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7a53210c-eb8a-4986-8c14-80e6e523598f PEGASUS_WF_LABEL=Drug-Combination-Therapy PEGASUS_DAG_JOB_ID=clean_up_local_level_4_0 PEGASUS_SITE=local"
arguments = " -n pegasus::cleanup -N null -i - -R local  -L Drug-Combination-Therapy -T 2023-03-05T09:10:05-08:00 /home/mzalam/pegasus-5.0.5/bin/../bin/pegasus-transfer "
error = /home/mzalam/covid/mzalam/pegasus/Drug-Combination-Therapy/run0013//00/00/clean_up_local_level_4_0.err
executable = /home/mzalam/pegasus-5.0.5/bin/../bin/pegasus-kickstart
input = /home/mzalam/covid/mzalam/pegasus/Drug-Combination-Therapy/run0013//00/00/clean_up_local_level_4_0.in
log = /home/mzalam/covid/mzalam/pegasus/Drug-Combination-Therapy/run0013/Drug-Combination-Therapy-0.log
notification = NEVER
output = /home/mzalam/covid/mzalam/pegasus/Drug-Combination-Therapy/run0013//00/00/clean_up_local_level_4_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7a53210c-eb8a-4986-8c14-80e6e523598f"
+pegasus_wf_uuid = "7a53210c-eb8a-4986-8c14-80e6e523598f"
+pegasus_version = "5.0.5"
+pegasus_wf_name = "Drug-Combination-Therapy-0"
+pegasus_wf_time = "20230305T091006-0800"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_4_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
