#!/bin/bash

set -e


if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

if [[ -z "$CI_COMMIT_SHORT_SHA" ]]; then
    CI_COMMIT_SHORT_SHA=`git rev-parse --short HEAD`
fi

TOPDIR=`pwd`

CONDOR_POOL_SHARED_FS=/scitech/shared/scratch-90-days/bamboo
mkdir -p $CONDOR_POOL_SHARED_FS/inputs

# generate the input file
echo "This is sample input to KEG" > f.a
echo "This is sample input to KEG" > $CONDOR_POOL_SHARED_FS/inputs/f.a1

#A output directory
mkdir -p outputs
mkdir -p work

export REMOTE_PEGASUS_HOME=/scitech/shared/scratch-90-days/bamboo/installs/pegasus-$CI_COMMIT_SHORT_SHA

# build the dax generator
PYTHONPATH=$(pegasus-config --python) $testdir/blackdiamond.py $REMOTE_PEGASUS_HOME $CONDOR_POOL_SHARED_FS/inputs > blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "${CONDOR_POOL_SHARED_FS}/shared-scratch"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "scp://bamboo@bamboo.isi.edu/${CONDOR_POOL_SHARED_FS}/shared-scratch"
  profiles:
    condor:
      universe: "vanilla"
    pegasus:
      ssh_private_key: "/scitech/shared/home/bamboo/.ssh/workflow_id_rsa"
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  os.release: "rhel"
  os.version: "7"
  directories:
   -
    type: "sharedScratch"
    path: "$TOPDIR/work"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/work"
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
EOF

# plan the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites condorpool \
    --output-sites local \
    --dir submit \
    --cleanup leaf \
    blackdiamond.dax \
     | tee $TOPDIR/plan.out


WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

# check if planner did the right thing
set +e
find $WORK_DIR -name "stage_in_remote*.in" | grep -e ".*" 1> /dev/null 2>&1
EC=$?
set -e

if [ $EC -ne 0 ]; then
    echo "Planner did not create any remote stagein jobs"
    exit 1
fi

set +e
grep 'f.a1\b' `find $WORK_DIR -name "stage_in_remote*in"`  1> /dev/null 2>&1
EC=$?
set -e


if [ $EC -ne 0 ]; then
    echo "remote stage in job does not stagein file f.a1"
    exit 1
fi

set +e
grep 'f.a\b' `find $WORK_DIR -name "stage_in_local*in"` 1> /dev/null 2>&1
EC=$?
set -e


if [ $EC -ne 0 ]; then
    echo "local stage in job does not stagein file f.a"
    exit 1
fi


#now submit the workflow to run
pegasus-run  $WORK_DIR
