#!/bin/bash

set -e
set -v

if [[ -z "$CI_COMMIT_SHORT_SHA" ]]; then
    CI_COMMIT_SHORT_SHA=`git rev-parse --short HEAD`
fi

TOPDIR=`pwd`

# generate the input file
echo "This is sample input to KEG" >f.a

# output directory
mkdir -p outputs

# build the dax generator
CLASSPATH=.:$(pegasus-config --classpath) javac BlackDiamondDAX.java

# generate the dax
CLASSPATH=.:$(pegasus-config --classpath) java BlackDiamondDAX /scitech/shared/scratch-90-days/bamboo/installs/pegasus-$CI_COMMIT_SHORT_SHA blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    env:
      PEGASUS_HOME: "/scitech/shared/scratch-90-days/bamboo/installs/pegasus-$CI_COMMIT_SHORT_SHA"
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/shared-scratch"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/shared-scratch"

EOF

# plan and submit the  workflow
pegasus-plan \
    --conf pegasusrc \
    --sites condorpool \
    --staging-site local \
    --dir submit \
    --output-sites local \
    --cleanup leaf \
    --submit \
    --randomdir \
    blackdiamond.dax \
    | tee plan.out
