.\"
.\" This file or a portion of this file is licensed under the terms of
.\" the Globus Toolkit Public License, found in file GTPL, or at
.\" http://www.globus.org/toolkit/download/license.html. This notice must
.\" appear in redistributions of this file, with or without modification.
.\"
.\" Redistributions of this Software, with or without modification, must
.\" reproduce the GTPL in: (1) the Software, or (2) the Documentation or
.\" some other similar material which is provided with the Software (if
.\" any).
.\"
.\" Copyright 1999-2004 University of Chicago and The University of
.\" Southern California. All rights reserved.
.\"
.\" $Id$
.\"
.\" Authors: Jens-S. Vöckler, Yong Zhao
.\"
.\"
.TH keg 1 "September, 18th 2002"
.SH NAME
keg \- kanonical executable for grids
.SH SYNOPSIS
.B keg
[\-a\~appname] [\-t\~interval |\-T\~ interval] [\-l\~logname] [\-P\~prefix]
[\-o\~fn [..]] [\-i\~fn [..]] [\-G\~sz] [\-C] [\-e\~env [..]] [\-p\~parm [..]]
.PP
.B keg.condor
[\-a\~appname] [\-t\~interval |\-T\~ interval] [\-l\~logname] [\-P\~prefix]
[\-o\~fn [..]] [\-i\~fn [..]] [\-G\~sz] [\-C] [\-e\~env [..]] [\-p\~parm [..]]
.SH DESCRIPTION
The kanonical executable is a stand-in for regular binaries in a DAG -
but not for their arguments. It allows to trace the shape of the
execution of a DAG, and thus is an aid to debugging DAG related issues.
.PP
Key feature of
.B keg
is that it can copy any number of input files, including the
.I generator
case, to any number of output files, including the
.I datasink
case. In addition, it protocols the IPv4 and hostname of the host it
ran upon, the current timestamp, and the run time from start til the
point of logging the information, the current working directory and
some information on the system environment. 
.B keg
will also report all input files, the current output files and any
requested string and environment value.
.PP
.B keg
comes in two flavors, as binary
.I keg
which runs in the Condor 
.I vanilla
universe, and as binary
.I keg.condor
which runs in the Condor
.I standard
universe.
.SH ARGUMENTS
The
.BR \-e ,
.BR \-i ,
.B \-o 
and
.B \-p
arguments allow lists with arbitrary number of arguments. These options
may also occur repeatedly on the command line. The file options may be
provided with the special filename \- to indicate
.I stdout
in append mode for writing, or
.I stdin
for reading. The
.BR \-a ,
.BR \-l ,
.BR \-P ,
.B \-T
and
.B \-t
arguments should only occur a single time with a single argument.
.PP
If 
.B keg 
is called without any arguments, it will display its usage and exit with
success.
.TP
.B \-a appname
This option allows 
.B keg
to display a different name as its applications. This mode of operation
is useful in make-believe mode. 
.IP
The default is the basename of 
.IR argv[0] .
.TP
.B \-e env [..]
This option names any number of environment variables, whose value
should be reported as part of the data dump.
.IP
By default, no environment variables are reported.
.TP
.B \-i infile [..]
The
.B keg
binary can work on any number of input files. For each output file,
every input file will be opened, and its content copied to the output
file. Textual input files are assumed. Each input line is indented by
two spaces. The input file content is bracketed between an start and
end section, see below.
.IP
By default, 
.B keg
operates in 
.I generator
mode.
.TP
.B \-l logfile
The 
.I logfile
is the name of a file to append atomically the self-info, see below. 
The atomic write guarantees that the multi-line information will not
interleave with other processes that simultaneously write to the same
file.
.IP
The default is not to use any log file.
.TP
.B \-o outfile [..]
The
.B keg
can work on any number of output files. For each output file, every
input file will be opened, and its content copied to the output file.
Textual input files are assumed. Each input line is indented by two
spaces. The input file content is bracketed between an start and end
section, see 2nd example.
.IP
After all input files are copied, the data dump from this instance
of 
.B keg
is appended to the output file.
.IP
Without output files, 
.B keg
operates in 
.I data sink
mode.
.TP
.B \-G size
If you want 
.B keg
to generate a lot of output, the generator option will do that for you.
Just specify how much, in bytes, you want. 
.IP
This option is off by default. 
.TP
.B \-C 
This option causes
.B keg
to list all environment variables that start with the prefix
.IR _CONDOR .
The option is useful, if 
.B keg
is run as (part of) a Condor job. 
.IP
This option is off by default. 
.TP
.B \-p string [..]
Any number of parameters can be reported, without being specific
on their content. Effectively, these strings are copied straight from
the command line.
.IP
By default, no extra arguments are shown.
.TP
.B \-P prefix
Each line from every input file is indented with a prefix string to 
visually emphasize the provenance of an input files through multiple
instances of
.BR keg .
.IP
By default, two spaces are used as prefix string.
.TP
.B \-t interval
The interval is an amount of sleep time that the 
.B keg
executable is to sleep. This can be used to emulate light work without
straining the pool resources. If used together with the 
.I \-T
spin option, the sleep interval comes before the spin interval.
.IP
The default is no sleep time.
.TP
.B \-T interval
The interval is an amount of busy spin time that the 
.B keg
executable is to simulate intense computation. The simulation is done by
random julia set calculations. This option can be used to emulate an intense
work to strain pool resources. If used together with the 
.I \-t
sleep option, the sleep interval comes before the spin interval.
.IP
The default is no spin time.
.SH "RETURN VALUE"
Execution as planned will return 0. The failure to open an input file
will return 1, the failure to open an output file, including the log
file, will return with exit code 2.
.SH "SEE ALSO"
.BR condor_submit_dag (1).
.SH EXAMPLE
The example shows the bracketing of an input file, and the copy
produced on the output file. For illustration purposes, the output
file is connected to
.IR stdout :
.nf
\f(CB
$ date > xx
$ keg -i xx -p a b c -o -
--- start xx ----
  Thu May  5 10:55:45 PDT 2011
--- final xx ----
Timestamp Today: 20110505T105552.910-07:00 (1304618152.910;0.000)
Applicationname: keg [3661M] @ 128.9.xxx.xxx (xxx.isi.edu)
Current Workdir: /opt/pegasus/default/bin/keg
Systemenvironm.: x86_64-Linux 2.6.18-238.9.1.el5
Processor Info.: 4 x Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz @ 2660.068
Load Averages  : 0.298 0.135 0.104
Memory Usage MB: 11970 total, 8089 free, 0 shared, 695 buffered
Swap Usage   MB: 12299 total, 12299 free
Filesystem Info: /                        ext3    62GB total,    20GB avail
Filesystem Info: /lfs/balefire            ext4  1694GB total,  1485GB avail
Filesystem Info: /boot                    ext2   493MB total,   447MB avail
Output Filename: -
Input Filenames: xx
Other Arguments: a b c
\fP
.fi
.SH RESTRICTIONS
The input file must be textual files. The behaviour with binary files
is unspecified.
.PP
The host address is determined from the primary interface. If there is
no active interface besides loopback, the host address will default to
0.0.0.0. If the host address is within a
.I virtual private network
address range, only 
.I (VPN)
will be displayed as hostname, and no reverse address lookup will be
attempted. 
.PP
The 
.B processor info
line is only available on Linux systems. The line will be missing on
other operating systems. Its information is assuming symmetrical multi
processing, reflecting the CPU name and speed of the last CPU available
in 
.IR /dev/cpuinfo .
.PP
There is a limit of 
.I 4 * page size
to the output buffer of things that
.B keg
can report in its self-info dump. There is no such restriction on the
input to output file copy. 
.SH AUTHORS
Jens-S. Vöckler <voeckler@cs.uchicago.edu>,
.\"Jens-S. V\*:ockler 
.br
Mike Wilde <wilde@mcs.anl.gov>,
.br
Yong Zhao <yongzh@cs.uchicago.edu>.
.PP
Chimera
.B http://www.griphyn.org/chimera/
.br
GriPhyN
.BR http://www.griphyn.org/
