#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/montage/current/bin:$PATH

rm -rf montage-workflow-v3
git clone https://github.com/pegasus-isi/montage-workflow-v3.git

echo
echo

cd montage-workflow-v3

singularity exec \
            --bind $PWD:/srv \
            library://rynge/default/montage:latest \
            /srv/montage-workflow.py \
                --work-dir /srv \
                --tc-target container \
                --center "275.196290 -16.171530" \
                --degrees 0.5 \
                --band 2mass:j:green \
                --band 2mass:h:blue \
                --band 2mass:k:red

# rc needs to have paths "outside" the image
#perl -p -i -e "s;/srv/data;$PWD/data;g" data/rc.txt

pegasus-plan \
        --dir work \
        --dax data/montage-workflow.yml \
        --cluster horizontal \
        --submit \
        | tee $TOP_DIR/plan.out


