#!/bin/bash

set -e
set -o pipefail

# this variable is expanded by the planner when
# parsing in the sites.xml file in the conf directory
TOPDIR=`pwd`
export TOPDIR

if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

# determine TEST_NAME to setup site catalog
TESTDIR=$(cd $testdir && pwd)
TEST_NAME=`basename $TESTDIR`
export TEST_NAME

# pegasus bin directory is needed to find keg
BIN_DIR=`pegasus-config --bin`
PEGASUS_LOCAL_BIN_DIR=$BIN_DIR
export PEGASUS_LOCAL_BIN_DIR

# generate the input file
export HOSTNAME=`hostname -f`
echo "This is sample input to KEG" >f.a

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./blackdiamond.py $BIN_DIR > blackdiamond.dax

# kickstart wrapper location
KS_WRAPPER=/nfs/ccg3/software/bamboo/kickstart-wrapper
export KS_WRAPPER

# plan and submit the  workflow
pegasus-plan \
    --conf ./pegasusrc \
    --sites condorpool \
    --output-sites local \
    --dir dags \
    --force \
    -v \
    blackdiamond.dax \
     | tee $TOPDIR/plan.out


WORK_DIR=`cat plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'`

#check if planner did the right things
for SUB in `find ${WORK_DIR} -name "*sub" -exec grep -l -P "pegasus_site\s*=\s*\"condorpool\"" {} \;` ; do

    if grep -E '\bexecutable' $SUB | grep $KS_WRAPPER 1> /dev/null 2>&1 ; then
	:
    else
	echo "Job $SUB not launched by kickstart-wrapper"
	exit 1
    fi
    SUBMIT_FILE_FOUND=True
done

if [ X${SUBMIT_FILE_FOUND} = X ]; then
    echo "No jobs scheduled for site condorpool in submit directory ${WORK_DIR}"
    exit 1
fi 

# now submit the workflow for execution
pegasus-run $WORK_DIR

