#!/bin/bash

set -e

TOP_DIR=`pwd`

rm -rf montage-workflow-v2
git clone https://github.com/pegasus-isi/montage-workflow-v2.git

echo
echo

cd montage-workflow-v2

# Create the workflow inside a Singularity container, but note
# that this image has Pegasus installed as we need the DAX API.
singularity exec \
    --bind $PWD:/srv \
    shub://pegasus-isi/montage-workflow-v2 \
    /srv/montage-workflow.py --work-dir /srv \
                             --tc-target container \
                             --center "56.7 24.00" \
                             --degrees 1.0 \
                             --band dss:DSS2B:blue \
                             --band dss:DSS2R:red

cat pegasus.properties >> ../pegasusrc

# rc needs to have paths "outside" the image
perl -p -i -e "s;/srv/data;$PWD/data;g" data/rc.txt

# custom site catalog
cp ../sites.xml sites.xml

# run in nonsharedfs mode
perl -p -i -e 's/condorio/nonsharedfs/' ../pegasusrc

pegasus-plan \
        --conf ../pegasusrc \
        --dir work \
        --relative-dir `date +'%s'` \
        --sites condor_pool \
        --staging-site staging \
        --output-sites local \
        --submit \
	data/montage.dax \
        | tee $TOP_DIR/plan.out


