#!/bin/bash

set -e

TOP_DIR=`pwd`

export PATH=/ccg/software/singularity/default/bin:$PATH

rm -rf montage-workflow-v2
git clone https://github.com/pegasus-isi/montage-workflow-v2.git

echo
echo

cd montage-workflow-v2

# Create the workflow inside a Singularity container, but note
# that this image has Pegasus installed as we need the DAX API.
# The actual workflow execution is using an image without
# Pegasus to trigger the automatic worker package deployment.
    #shub://pegasus-isi/montage-workflow-v2 \
singularity exec \
    --bind $PWD:/srv --workdir /srv \
    /tmp/5b2887177e39a804904a186eb4b0a278.img \
    /srv/montage-workflow.py --tc-target container \
                             --center "275.196290 -16.171530" \
                             --degrees 0.5 \
                             --band 2mass:j:green \
                             --band 2mass:h:blue \
                             --band 2mass:k:red

# update the tc with an image which does not have Pegasus
# already installed
perl -p -i -e 's/montage-workflow-v2/fedora-montage/' data/tc.txt

# custom site catalog
cp ../sites.xml sites.xml

# run in nonsharedfs mode
perl -p -i -e 's/condorio/nonsharedfs/' pegasus.properties

pegasus-plan \
        --dir work \
        --relative-dir `date +'%s'` \
        --dax data/montage.dax \
        --sites condor_pool \
        --staging-site staging \
        --output-site local \
        --cluster horizontal \
        --submit \
        | tee $TOP_DIR/plan.out


