#!/bin/bash

echo
echo
echo
echo "The current HTCondor version is:"
echo

condor_version

echo
echo 
echo "The current test environment is:"
echo

/usr/bin/env | sort

echo
echo 

if [ "x$CLASSPATH" != "x" ]; then
    echo "Please run the tests without CLASSPATH!" >&2
    exit 1
fi

if [ "x$PYTHONPATH" != "x" ]; then
    echo "Please run the tests without PYTHONPATH!" >&2
    exit 1
fi


