#!/bin/bash

set -e
set -v

if [ X${testdir} = "X" ]; then
    testdir=`dirname  $0`
    export testdir
fi

TOPDIR=`pwd`

# generate the input file
echo "This is sample input to KEG" > f.a

# output directory
mkdir -p outputs

# build the dax generator
export PYTHONPATH=`pegasus-config --python`
$testdir/blackdiamond.py /usr > blackdiamond.dax

# create the site catalog
cat > sites.yml <<EOF
pegasus: "5.0"
sites:
 -
  name: "isi-condorc"
  arch: "x86_64"
  os.type: "linux"
  grids:
   -
    type: "condor"
    contact: "ccg-testing1.isi.edu"
    scheduler: "condor"
    jobtype: "auxillary"
   -
    type: "condor"
    contact: "ccg-testing1.isi.edu"
    scheduler: "condor"
    jobtype: "compute"
  profiles:
    env:
      PATH: "/opt/python/2.6/bin:/usr/bin:/bin"
    condor:
      universe: "vanilla"
    pegasus:
      clusters.num: "1"
      style: "condorc"
 -
  name: "cartman-data"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "${TOPDIR}/staging-site/scratch"
    fileServers:
     -
      operation: "all"
      url: "gsiftp://bamboo.isi.edu${TOPDIR}/staging-site/scratch"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/work"
    fileServers:
     -
      operation: "all"
      url: "file://$TOPDIR/work"
EOF

# plan and submit the  workflow
pegasus-plan \
    --conf $testdir/pegasusrc \
    --sites isi-condorc \
    --staging-site cartman-data \
    --output-site local \
    --dir work \
    --cleanup leaf \
    --cluster horizontal \
    --dax blackdiamond.dax \
    --submit | tee plan.out
