.\"  Copyright 2010-2011 University Of Southern California
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"  http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing,
.\"  software distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.\" 
.\" $Id$
.TH "pegasus-bug-report" "1" "1.3.10" "GriPhyN PEGASUS Planner"
.SH "NAME"
.LP 
pegasus\-bug\-report \- aide the support to collect a workflow for bug reports
.SH "SYNTAX"
.LP 
.B pegasus\-bug\-report \-\-help
.LP
.B pegasus\-bug\-report \-\-version
.LP 
.B pegasus\-bug\-report [\-Dprops] [\-v] \-d dax rundir [file [..]]
.SH "DESCRIPTION"
.LP 
This script aides a user to provide all interesting information to the
support team. The script creates a compressed tarball of all files in
the workflow's run directory on the submit host, the dax file, several
ancilliary files and an information file. Additional files or
directories may be added by specifying them after the run directory on
the command-line.
.SH "ARGUMENTS"
.TP
.B \-Dprop
The -D options allows an experienced user to override certain properties
which influence the program execution, among them the default location of
the user's properties file and the PEGASUS home location. One may set several
CLI properties by giving this option multiple times.
.I The -D option(s) must be the first option on the command line. 
CLI properties take precedence over the file-based properties of the
same key. 
.TP
.B \-\-verbose
.PD 0
.TP
.PD 1
.B \-v
raises debug level. A higher debug level will increase the verbosity of
the output messages on
.IR stderr .
This is a multi\-option, each specification will increase the debug
level by 1.
.IP 
There is no verbosity implemented at the moment. 
.TP
.B \-\-version
.PD 0
.TP
.PD 1
.B \-V
display a short version message and exits.
.TP
.B \-\-help
.PD 0
.TP
.PD 1
.B \-h
shows a brief help message on the usage and exits. 
.TP
.B \-\-dax fn
.PD 0
.TP
.PD 1
.B \-d fn
is a mandatory option. It points to the DAX file that contains the
abstract workflow which was planned. 
.IP
If and only if you no longer have your dax file, you can use 
.IR /dev/null .
We do not encourage arbitrary use of a by-pass.
.TP
.B rundir
is a mandatory argument. It points to the working directory on the
submit host, where the Condor DAGMan's .dag file resides. Subdirectories
will be automatically collected. 
.TP
.B [file [..]]
It is possible to provide additional files and directory contents you
think useful to aide support finding the cause of your problem. These
files and directories are listed on the command-line after the run
directory. 
.SH "RETURN VALUE"
If the tar ball could be created, 
.I pegasus\-bug\-report
returns with an exit code of 0. However, in case of error, a non-zero
exit code indicates problems. An error message clearly marks the cause. 
.SH "ENVIRONMENT VARIABLES"
.TP
.B PEGASUS_HOME
points to the installation base directory of your the PEGASUS execution
environment. 
.TP
.B PERL5LIB
is a path-like variable. It must include to the PEGASUS perl module
installation. 
.TP
.B PATH
should include the Condor binaries. 
.SH "EXAMPLES"
.LP
The following example has many messages removed:
.nf 
\f(CB
$ pegasus-bug-report -d blackdiamond.dax ivdgl1/black-diamond/run0001
#
# PEGASUS basics
#
pegasus-bug-report 1.11

 [...]

I have collected information about the directory and your system.
Please send bug.jcl4nt.tar.gz as a proper binary attachment to

	pegasus-support@griphyn.org

Remember to include your bug description in the regular email body.

\fP
.fi 
.SH "AUTHORS"
.LP 
Jens\-S. Vöckler <voeckler at cs dot uchicago dot edu>
.PP 
PEGASUS
.B http://pegasus.isi.edu
.br 
GriPhyN
.BR http://www.griphyn.org/
