.\"  Copyright 2010-2011 University Of Southern California
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"  http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing,
.\"  software distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.\"
.\" $Id$
.\"
.\" Authors: Jens-S. Vöckler
.\"
.\"
.TH pegasus-verify 1 "August, 11th 2005"
.SH NAME
pegasus-verify \- checks for foreseeable pitfalls before you trip. 
.SH SYNOPSIS
.B pegasus-verify [-Dprops] [--debug | --quiet] (--pegasus | --euryale) daxfile
.br
.B pegasus-verify --help
.SH DESCRIPTION
The verify program checks for pitfalls that frequently occur when
attempting to plan, or even run, a large workflow. The current check
list includes, albeit all local to the submit host:
.TP
* environment setup and path check
.TP
* essential executable accessibility check
.TP
* property file parsing and sanity
.TP
* PEGASUS catalog sanity checks
.TP
* Perl module availability and version check
.TP
* XML parsability of the DAX file
.TP
* dangling dependency DAX check
.TP
* DAX input files existence check (RC)
.TP
* DAX transformation existence check (TC)
.SH ARGUMENTS
.TP
.B \-Dprop
The -D options allows an experienced user to override certain properties
which influence the program execution, among them the default location of
the user's properties file and the PEGASUS home location. One may set several
CLI properties by giving this option multiple times.
.I The -D option(s) must be the first option on the command line. 
CLI properties take precedence over the file-based properties of the
same key. 
.TP
.B \-d 
.PD 0
.TP
.PD 1
.B \-\-debug 
The debug option specifies the amount of verbosity accompanying actions.
It may be specified multiple times to increase verbosity. 
.TP
.B \-q
.PD 0
.TP
.PD 1
.B \-\-quiet
If the quiet option is chosen, only warnings and errors will be
displayed.
.TP
.B \-e
.PD 0
.TP
.PD 1
.B \-\-euryale
This option specifies that the checks specific for the Euryale concrete
planner are activated. The planner-specific checks include only a small
subset of the overall-checks, limited to the Java properties. 
.IP
You must specify either \-\-pegasus or \-\-euryale.
.TP
.B \-p
.PD 0
.TP
.PD 1
.B \-\-pegasus
This option specifies that the checks specific for the Pegasus concrete
planner are activated. The planner-specific checks include only a small
subset of the overall-checks, limited to the Java properties. 
.IP
You must specify either \-\-pegasus or \-\-euryale.
.TP
.B \-h
.PD 0
.TP
.PD 1
.B \-\-help
shows a concise usage output.
.TP
.B \-E enc
.PD 0
.TP
.PD 1
.B \-\-encoding enc
permits to use a different character encoding for the DAX file. 
.IP
By default, the XML file is assumed to be in 
.I ISO-8859-1 
format. 
.SH "RETURN VALUE"
The program will return with success, if the checks turn out OK. It may
have displayed warnings along the way. If problems were encountered, an
exit code of 1 will follow the error message.
.SH EXAMPLE
The following invocation checks a setup for a subsequent Euryale run.
.nf
\f(CB
$ pegasus-verify --euryale ~/work/blackdiamond.dax 
WARNING [pro]: transformation catalog style old is deprecated

All is well that ends well.

\fP
.fi
The property settings trigger a warning that the old style TC will fall
prey to bit rot. The final message shows that no problem was perceived
when attempting the workflow. A significantly more verbose output can be
gained using the debug option.
.SH "ENVIRONMENT VARIABLES"
.TP
.B PEGASUS_HOME
points to the installation base directory of your the PEGASUS execution
environment. 
.TP
.B PERL5LIB
is a path-like variable. It must include to the PEGASUS perl module
installation. 
.TP
.B PATH
should include the Condor, Globus and PEGASUS binaries. 
.TP
.B GLOBUS_LOCATION
should point to the root of your Globus installation.
.TP
.B JAVA_HOME
must point to the root of your Java installation (JRE suffices). 
.SH AUTHORS
Jens-S. Vöckler <voeckler at cs dot uchicago dot edu>,
.br
Gaurang Mehta <gmehta at isi dot edu>,
.PP
PEGASUS
.B http://pegasus.isi.edu
.br
GriPhyN
.BR http://www.griphyn.org/
