#!/bin/bash

TOP_DIR=`pwd`
TEST=`echo $1 | awk -F " - " '{print $3}'`
shift

cd test/core/$TEST

echo "TEST is $TEST"
pwd

#Launch the test
./run-bamboo-test "$@"

STATUS=$?
if [ $STATUS != 0 ]; then
   echo "Test failed!"
   exit $STATUS
fi

exit
