.\"
.\" This file or a portion of this file is licensed under the terms of
.\" the Globus Toolkit Public License, found in file GTPL, or at
.\" http://www.globus.org/toolkit/download/license.html. This notice must
.\" appear in redistributions of this file, with or without modification.
.\"
.\" Redistributions of this Software, with or without modification, must
.\" reproduce the GTPL in: (1) the Software, or (2) the Documentation or
.\" some other similar material which is provided with the Software (if
.\" any).
.\"
.\" Copyright 1999-2004 University of Chicago and The University of
.\" Southern California. All rights reserved.
.\"
.\" $Id$
.\"
.\" Authors: Gaurang Mehta, Jens-S. Vöckler
.\"
.\"
.TH "pegasus-status" "1" "3.1.0" "PEGASUS Status"
.SH NAME
pegasus\-status \- Pegasus workflow- and run\-time status
.SH SYNOPSIS
.B pegasus\-status
\-h|\-\-help
.PP
.B pegasus\-status
\-V|\-\-version
.PP
.B pegasus\-status 
[\-w|\-\-watch\~[s]] [\-L|\-\-[no]legend] [\-Q|\-\-[no]queue] [\-v|\-\-verbose]
[\-d|\-\-debug] [\-u|\-\-user\~name] [\-i|\-\-[no]idle] [\-\-[no]held]
[\-\-[no]heavy] [\-j|\-\-jobtype\~jt] [\-s|\-\-site\~sid] [\-l|\-\-long]
[\-S|\-\-[no]success] [rundir]
.SH "DESCRIPTION"
.SH "ARGUMENTS"
.SH "RETURN VALUE"
.SH "SEE ALSO"
.SH "EXAMPLE"
.SH "RESTRICTIONS"
.SH "AUTHORS"
Jens-S. Vöckler <voeckler at isi dot edu>
.br
Gaurang Mehta <gmehta at isi dot edu>
.PP
Pegasus
.B http://pegasus.isi.edu/
