.\" This file or a portion of this file is licensed under the terms of
.\" the Globus Toolkit Public License, found in file GTPL, or at
.\" http://www.globus.org/toolkit/download/license.html. This notice must
.\" appear in redistributions of this file, with or without modification.
.\"
.\" Redistributions of this Software, with or without modification, must
.\" reproduce the GTPL in: (1) the Software, or (2) the Documentation or
.\" some other similar material which is provided with the Software (if
.\" any).
.\"
.\" Copyright 1999-2004 University of Chicago and The University of
.\" Southern California. All rights reserved.
.\"
.\" $Id$
.\"
.\" Authors: Jens-S. Vöckler, Yong Zhao
.\"
.\"
.TH test-version 1 "July, 9th 2003"
.SH NAME
test-version \- check the execution environment
.SH SYNOPSIS
.B test-version
[\-Dprop [..]]
.SH DESCRIPTION
This script only exists as Bourne script. It is suggested that Windows
users employ the cygwin32 environment. 
.SH ARGUMENTS
The program usually does not take any arguments. However, experienced
users are allowed to adjust certain properties.
.TP
.B \-Dprop
The -D options allows an experienced user to override certain properties
which influence the program execution, among them the default location of
the user's properties file and the VDS home location. One may set several
CLI properties by giving this option multiple times.
.I The -D option(s) must be the first option on the command line. 
A CLI property take precedence over the properties file property 
of the same key.
.SH "RETURN VALUE"
Regular and planned program terminations will result in an exit code of 0.
Abnormal termination will result in a non-zero exit code.
.SH FILES
The process checks the existence of a java executable and various jar
files.
.TP
.B 
.TP
.B
.TP
.B
.SH "ENVIRONMENT VARIABLES"
.TP
.B $VDS_HOME
is the suggested base directory of your the execution environment.
.TP
.B $JAVA_HOME
should be set and point to a valid location to start the intended Java
virtual machine as
.IR $JAVA_HOME/bin/java .
.TP
.B $CLASSPATH
should be set to contain all necessary files for the execution environment.
Please make sure that your 
.I CLASSPATH
includes pointer to the Xerces 2.6.0 classes and, potentially, the
.I gvds.jar
file. It is not a bug, if you are mising the gvds.jar, but do
have the sources available and configured in your 
.IR CLASSPATH .
.SH "SEE ALSO"
.BR vdlx2vdlt (1),
.BR vdlt2vdlx (1),
.BR insertvdc (1),
.BR searchvdc (1),
.BR updatevdc (1).
.SH EXAMPLE
.nf
\f(CB
$ test-version
# checking for JAVA_HOME
# checking for CLASSPATH
# checking for VDS_HOME
# starting java
# Using recommended version of Java, OK
# looking for Xerces
# found /home/voeckler/vds/lib/xercesImpl.jar, OK for now
# found /home/voeckler/vds/lib/xmlParserAPIs.jar, OK for now
# looking for GNU getopt
# found /home/voeckler/vds/lib/java-getopt-1.0.9.jar, OK for now
# looking for JDBC drivers
# found /home/voeckler/vds/lib/postgresql-8.1dev-400.jdbc3.jar, OK for now
# found /home/voeckler/vds/lib/mysql-connector-java-3.0.11-stable-bin.jar, OK for now
# looking for my replica catalogs
# found /home/voeckler/vds/lib/rls.jar, OK for now
# looking for myself
# in developer mode, ignore not finding gvds.jar
# found gvds.jar, OK for now
\fP
.fi
.PP
Please note that an error while searching for gvds.jar is not fatal,
if you have access to the sources, 
.I and
your sources are configured in your
.IR CLASSPATH .
This is typically the case for the developer environment.
.SH RESTRICTIONS
Plenty. 
.SH AUTHORS
Jens-S. Vöckler <voeckler at cs dot uchicago dot edu>,
.\"Jens-S. V\*:ockler 
.br
Mike Wilde <wilde at mcs dot anl dot gov>,
.br
Yong Zhao <yongzh at cs dot uchicago dot edu>.
.PP
Chimera
.B http://www.griphyn.org/chimera/
.br
GriPhyN
.BR http://www.griphyn.org/
