#!/bin/bash

set -e

CONFIG=`basename $1`

if [[ -z "$CI_COMMIT_SHORT_SHA" ]]; then
    CI_COMMIT_SHORT_SHA=`git rev-parse --short HEAD`
fi

if [[ "${CONFIG}" == *"-sharedfs"*  ]]; then
    PEGASUS_KEG="/scitech/shared/scratch-90-days/bamboo/installs/pegasus-$CI_COMMIT_SHORT_SHA/bin/pegasus-keg"
else
    PEGASUS_KEG=`which pegasus-keg`
fi

echo "Running cluster.py"
PYTHONPATH=$(pegasus-config --python) python3 cluster.py "${PEGASUS_KEG}" $CONFIG
