#!/bin/bash

set -e
set -v

TOPDIR=`pwd`

CONFIG=`basename $1`
DAX=horizontal-cluster.dax

# Unique directory for this run
RUN_ID=`/bin/date +'%Y%m%d_%H%M%S%N'`

export REMOTE_PEGASUS_HOME=/lizard/scratch-90-days/bamboo/installs/pegasus-`pegasus-version`

# Read a property from ${CONFIG}/test.config file
properties ()
{
        eval $1=\"`grep "^[\s]*[^#]*$2\s*=" ${CONFIG}/test.config | cut -d"=" -f2 | sed -e 's/^\s*//g' -e 's/\s*$//g'`\"

        local i=\$$1
        eval local temp=$i

        # If property not set or is empty, then check if default value is provided. If Yes set property to default value.
        if [[ -z $temp && ! -z $3 ]]; then
                eval $1=$3
        fi
}

# Read the physical directory where the input file is located.
properties input_file input_file

if [ -z ${input_file} ]; then
        input_file='./f.a'
else
	mkdir -p ${input_file}/$USER/inputs
        input_file=${input_file}/$USER/inputs/f.a
fi

# generate the input file
echo "This is sample input to KEG" > ${input_file}

mkdir -p staging-site

# build the dax generator
export PYTHONPATH=`pegasus-config --python`
./cluster.py /usr $CONFIG > ${DAX}

properties local_site_protocol local_site_protocol file://
properties local_site_url local_site_url

# create the site catalog
cat > sites.yml << EOF
pegasus: "5.0"
sites:
 -
  name: "cartman-data"
  arch: "x86"
  os.type: "linux"
  directories:
   -
    type: "sharedScratch"
    path: "${TOPDIR}/staging-site/scratch"
    fileServers:
     -
      operation: "all"
      url: "gsiftp://bamboo.isi.edu${TOPDIR}/staging-site/scratch"
  profiles:
    env:
      PEGASUS_HOME: "$REMOTE_PEGASUS_HOME"
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "sharedfs"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "/lizard/scratch-90-days/$USER/storage/black-diamond-output/$RUN_ID"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days/$USER/storage/black-diamond-output/$RUN_ID"
   -
    type: "sharedScratch"
    path: "/lizard/scratch-90-days/$USER/scratch/$RUN_ID"
    fileServers:
     -
      operation: "all"
      url: "file:///lizard/scratch-90-days/$USER/scratch/$RUN_ID"
  profiles:
    env:
      PEGASUS_HOME: "$REMOTE_PEGASUS_HOME"
    condor:
      should_transfer_files: "Yes"
      universe: "vanilla"
      when_to_transfer_output: "ON_EXIT"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "sharedStorage"
    path: "$TOPDIR/outputs"
    fileServers:
     -
      operation: "all"
      url: "${local_site_url}$TOPDIR/outputs"
   -
    type: "sharedScratch"
    path: "$TOPDIR/work"
    fileServers:
     -
      operation: "all"
      url: "${local_site_url}$TOPDIR/work"
EOF

# plan and submit the workflow
properties execution_site execution_site local
properties staging_site staging_site local
properties output_site output_site local
properties planner_args planner_args

if [ -e ${TOPDIR}/pegasusrc ]; then
    cat ${TOPDIR}/pegasusrc >> ${CONFIG}/pegasusrc
else
    exit 1
fi

set -x

pegasus-plan \
    --conf ${CONFIG}/pegasusrc \
    --sites ${execution_site} \
    --staging-site $staging_site \
    --output-site $output_site \
    --dir work/submit \
    --cleanup leaf \
    --dax ${DAX} \
    --cluster horizontal \
    --submit ${planner_args}

set +x

