#!/bin/bash

set -e

echo
echo "Setting up virtualenv with cwl-utils and yaml packages for pegasus-cwl-converter"
command -v python3.12 >/dev/null 2>&1 || {
    echo >&2 "Python3.12 is required to create virtual environment, but it is not installed. Aborting."
    exit 1;
}
VIRTUAL_ENV_DIR=cwl_venv
python3.12 -m venv $VIRTUAL_ENV_DIR

source cwl_venv/bin/activate

pip install  "cwl-utils==0.11" "jsonschema==3.2.0" "PyYAML"

echo
echo "Creating input.yml from input.yml.template"
export INPUT_DIR=`pwd`/cwl
envsubst < ./cwl/input.yml.template > ./cwl/input.yml

echo
echo "Setting baseCommand in get_file_sizes.cwl"
envsubst < ./cwl/get_file_sizes.cwl.template > ./cwl/get_file_sizes.cwl

echo
echo "Creating transformation spec file as tr_spec.yml"
cat << EOT >> tr_spec.yml
tar:
    site: condorpool
    is_stageable: False
gcc:
    site: condorpool
    is_stageable: False
get_file_sizes.sh:
    site: local
    is_stageable: True
EOT

echo
echo "Converting the cwl workflow to pegasus yaml format"
export PEGASUS_PYTHON=`which python3`
pegasus-cwl-converter --debug ./cwl/workflow.cwl ./cwl/input.yml tr_spec.yml ./workflow.yml

echo
echo "Cleaning up virtual environment"
deactivate
rm -r $VIRTUAL_ENV_DIR

echo
echo "Setting up work directory"
TOP_DIR=`pwd`
export RUN_ID=047-cwl-to-pegasus-yaml-test-workflow-`date +'%s'`

echo
echo "Creating the site catalog..."
cat > sites.yml << EOF
pegasus: "5.0"
sites:
 -
  name: "condorpool"
  arch: "x86_64"
  os.type: "linux"
  profiles:
    condor:
      universe: "vanilla"
    pegasus:
      style: "condor"
 -
  name: "local"
  arch: "x86_64"
  os.type: "linux"
  directories:
   -
    type: "localStorage"
    path: "$TOP_DIR/outputs/$RUN_ID"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOP_DIR/outputs/$RUN_ID"
   -
    type: "sharedScratch"
    path: "$TOP_DIR/shared-scratch/$RUN_ID"
    sharedFileSystem: false
    fileServers:
     -
      operation: "all"
      url: "file://$TOP_DIR/shared-scratch/$RUN_ID"
EOF

echo
echo "Creating pegasus configuration file"
cat > pegasus.conf << EOF
pegasus.catalog.site.file = sites.yml
pegasus.data.configuration = condorio
EOF

echo
echo "Planning and submitting the converted workflow"
unset PEGASUS_PYTHON
pegasus-plan \
    --conf pegasus.conf \
    --force \
    --dir submit \
    --relative-dir $RUN_ID \
    --sites condorpool \
    --output-sites local \
    --cluster horizontal \
    --submit workflow.yml
