#!/bin/bash

set -e

echo
echo "Setting up virtualenv with cwl-utils and yaml packages for pegasus-cwl-converter"
command -v virtualenv >/dev/null 2>&1 || {
    echo >&2 "virtualenv is required for this test but it is not installed. Aborting."
    exit 1;
}
VIRTUAL_ENV_DIR=cwl_venv
python -m virtualenv -p python3.6 $VIRTUAL_ENV_DIR

source cwl_venv/bin/activate

pip install "cwl-utils==0.3" "jsonschema==3.2.0" "PyYAML"

echo
echo "Creating input.yml from input.yml.template"
export INPUT_DIR=`pwd`/cwl
envsubst < ./cwl/input.yml.template > ./cwl/input.yml

echo
echo "Setting baseCommand in get_file_sizes.cwl"
envsubst < ./cwl/get_file_sizes.cwl.template > ./cwl/get_file_sizes.cwl

echo
echo "Creating transformation spec file as tr_spec.yml"
cat << EOT >> tr_spec.yml
tar:
    site: condorpool
    is_stageable: False
gcc:
    site: condorpool
    is_stageable: False
get_file_sizes.sh:
    site: local
    is_stageable: True
EOT

echo
echo "Converting the cwl workflow to pegasus yaml format"
pegasus-cwl-converter --debug ./cwl/workflow.cwl ./cwl/input.yml tr_spec.yml ./workflow.yml

echo
echo "Cleaning up virtual environment"
deactivate
rm -r $VIRTUAL_ENV_DIR

echo
echo "Setting up work directory"
TOP_DIR=`pwd`
WORK_DIR=$TOP_DIR/work
mkdir -p $WORK_DIR
export RUN_ID=047-cwl-to-pegasus-yaml-test-workflow-`date +'%s'`

echo
echo "Creating the site catalog..."
cat > sites.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">
    <site  handle="local" arch="x86_64">
        <directory type="shared-scratch" path="$WORK_DIR/$RUN_ID">
            <file-server operation="all" url="file://$WORK_DIR/$RUN_ID"/>
        </directory>
        <directory type="local-storage" path="$WORK_DIR/outputs/$RUN_ID">
            <file-server operation="all" url="file://$WORK_DIR/outputs/$RUN_ID"/>
        </directory>
    </site>

    <!-- this is our execution site -->
    <site  handle="condorpool" arch="x86_64" os="LINUX">
        <profile namespace="pegasus" key="style" >condor</profile>
        <profile namespace="condor" key="universe" >vanilla</profile>
    </site>
</sitecatalog>
EOF

echo
echo "Creating pegasus configuration file"
cat > pegasus.conf << EOF
pegasus.catalog.site.file = sites.xml
pegasus.data.configuration = condorio
EOF

echo
echo "Planning and submitting the converted workflow"
pegasus-plan \
    --conf pegasus.conf \
    --force \
    --dir $WORK_DIR \
    --relative-dir $RUN_ID \
    --sites condorpool \
    --output-sites local \
    --dax workflow.yml \
    --cluster horizontal \
    --submit
