#!/bin/bash

set -e

echo "Running blackdiamond.py"
PYTHONPATH=$(pegasus-config --python) python3 blackdiamond.py

SUBMIT_DIR=`cat submit_dir`

echo "SUBMIT_DIR is $SUBMIT_DIR"

# check in the submit directory to make sure that only stage_out and register jobs are generated
set +e
ls $SUBMIT_DIR/*sub | grep -v register | grep -v condor.sub | grep -v stage_out
EC=$?
set -e

if [ $EC -eq 0 ]; then
    echo "ERROR: Test Failed - Submit directory contains jobs other than stageout and register jobs."
    exit 1
fi

#submit the workflow
pegasus-run $SUBMIT_DIR
